### ISSUE TITLE
Bücherregal ausmisten

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#1]
Unser Bücherregal steht seit Jahren voll mit Katalogen. Da könnte man™ mal aufräumen.

**Comment by maikf-donnerdoria** [comment]
:+1:

**Comment by maikf** [comment]
:+1:

**Comment by Don42** [comment]
Bei den Katalogen solltest du mit Dafo reden. Die werden meines Wissens noch als Referenz benutzt.

**Comment by maikf-donnerdoria** [comment]
Wie oft schaut Dafo da rein, um etwas zu bestellen?
Die sind doch sowieso nur eine veraltete Ausgabe des Internet.

**Comment by maikf** [comment]
Wie oft schaut Dafo da rein, um etwas zu bestellen?
Die sind doch sowieso nur eine veraltete Ausgabe des Internet.

**Comment by else** [comment]
Jup. Kann man dann ja zur Not dann Dafo fragen, und er schaut zuhause bei sich nach.

**Comment by slowpoketail** [comment]
Viele der Bücher werden ebenfalls kaum bis gar nicht benutzt, oder sind auch völlig veraltet. Ein paar davon mögen vielleicht historischen Wert haben, einen Grossteil können wir aber auch einfach mal loswerden (wie auch immer wir das anstellen).

**Comment by rzl-tuwat** [comment]
*hust* Einige dieser Bücher habe ich Gespendet/Dauerleihgabt da ich
hoffnungslos der Überzeugung verfallen bin das $leute daraus noch
Elektronik lernen können - gänzlich ohne Microkontroller und
Digitalscheiß :-p

Sollten allerdings mehr $leute als Slowpoke der Meinung sein das die
Bücher nur stören überführe ich sie gerne wieder in meine private
Bibliothek.

Mit freundlichen Grüßen Drahti Andi

**Comment by Bfritz0815** [comment]
Bezüglich der Kataloge evtl auch nochmal mit Feli reden. Der war da bisher immer dahinter her, dass die bleiben. Die Idee ist wohl, dass man dort anhand der Abbildungen Teile identifizieren kann und dadurch auch Die Namen von Teilen wiederfindet. 

e.g.
Ich weiss, dass es eine Art Trafo ist. 
Daher weiss ich, dass ich im Kapitel für Trafos suchen muss. 
Dort finde ich die passende Abbildung und komme so an den passenden Namen. (Mit dem kann ich dann im Partkeepr oder im Netz weiterarbeiten)

Merke: Ohne den korrekten Begriff zu kennen, kann man schlecht den  passenden Begriff in eine Suchmaschine eingeben. 

Falls jemand weiss, wie man das Verfahren ersetzen kann, möge er/sie das bitte mitteilen. Bis dahin sind das Referenzwerke und sollten bleiben.

**Comment by felicitus** [comment]
Die Kataloge sollten auf jeden Fall bleiben. Wenn ein Teil gebraucht wird, ist es wesentlich einfacher, Kataloge durchzuwälzen als Onlinekataloge. Duplikate bzw. alte Auflagen der Kataloge können natürlich weg.

Wegen der Bücher habe ich keine Meinung, ich nutze die nicht.

**Comment by Bfritz0815** [comment]
Vorschlag zu den Büchern:
Wenn jemand ein Buch für veraltet hält, stellt er es einfach auf die ULO-Liste mit  einer Frist von 6 Monaten. (+ mit Link auf ML announcen natürlich!)
Sollte im Buch ein Eigentümer angegeben sein, bitte den auch spezifisch anschreiben. 

Die CT  (von 2007 und 2011) hab ich übrigens mal zum Entsorgen bereitgelegt.

**Comment by maikf** [comment]
Auf dem ersten Format&Reinstall wurde es ausgemistet.
Sämtliche alte c't, COM und Computerbild wurden in die Tonne getreten.

Dafos&Felis Kataloge sind btw Datenblattkataloge, keine Bestellkataloge,
weswegen sie bleiben.
