### ISSUE TITLE
Rundleuchte defekt

### ISSUE THREAD

**Issue by Cheatha** [raumzeitlabor/rzl-tuwat#10]
Leuchte leuchtet bei einem !ping im IRC nicht.

**Comment by slowpoketail** [comment]
Ich schau am Wochenende mal, ob es an der gefrickelten¹ Stromversorgung liegt oder ob es an der Anbindung Lampe←→IRC liegt.

¹ derzeit wird die Lampe von einem ATX-Netzteil betrieben, dass hinten im Rack liegt.

**Comment by maikf** [comment]
Hier der Spoiler:
Die kompletten Funksteckdosen funktionieren zur Zeit nicht, ergo auch die Rundumleuchte nicht.

Aber auf das Netzteil müsste trotzdem mal geschaut werden, um einen hochohmigen Widerstand
auf die 5V-Schiene zu klemmen, damit die etwas Last hat.

@else hat da was vorbereitet, um den aktuellen Krebs (FHEM und die mqtt Integration)
loszuwerden, bräuchte aber noch liebevolles Zureden, damit er weiter. Energie reinsteckt. :heart:

**Comment by yocky96** [comment]
Die Funksteckdose ist defekt (sie reagier auch nicht auf manuelle Eingaben über den Knopf). Wer hat denn diese bestellt, da die Garantie noch zählen müsste.

**Comment by else** [comment]
Rechnung hier: https://lists.raumzeitlabor.de/private/info/attachments/20140511/d6a5c873/attachment-0003.obj (ist ein PDF)

**Comment by s1lvester** [comment]
@maikf hat fhem abgeschossen und durch openhab ersetzt. Funksteckdosen funktionieren nun wieder. Anbindung an den irc bot fehlt noch. Trotzdem erstmal danke dafür!!!

interface: http://infra.rzl:8080
api unter: http://infra.rzl:8080/rest

The possibilities are infinite!

**Comment by else** [comment]
Sehr geil. Und cool, dass es mittlerweile PC301 Bindings für OpenHAB gibt.

**Comment by maikf** [comment]
https://github.com/raumzeitlabor/openhab-config

Bot muss noch angepasst werden.
Bald(tm) mehr.

**Comment by s1lvester** [comment]
@maikf hat alles gefixt. Danke dafür!

**Comment by tabascoeye** [comment]
:+1::+1::+1:

**Comment by s1lvester** [comment]
Geht wieder nicht... Debugging notwendig.

**Comment by s1lvester** [comment]
Okay: Funksteckdose im Serverschrank mal "gepowercyclet" --> tut wieder.
