### ISSUE TITLE
tardis 0x61 entrümpeln

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#102]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Hog vorstellen?

**Comment by tabascoeye** [comment]
Könnte @whilo wissen oder Oko

**Comment by whilo** [comment]
> Hallo Christian,
>
> ich gebe die Sachen, die von mir im RZL liegen, auf.
> Das heisst es kann entweder entsorgt werden, in andere Haende uebergehen oder ich hole es ab und 
> entsorge es selbst.
> 
> Mit freundlichen Grüßen
>
> Roland Fries

**Comment by Bfritz0815** [comment]
@whilo Da du wohl noch Kontakt zu milhouse hast. Könntest du diese Info bitte weiterleiten:

Hi milhouse,
Danke für die Erlaubnis. Entsorgen/herschenken könnten wir das meiste problemlos hier. Ein Teil ist da, wo ich mir nicht sicher bin, ob das auch weg kann: "TBoard V2" (würde ja sicher gerne jemand nehmen aber evtl brauchst du's ja doch noch) Daher hab ich mal ein Photo des Schubladeninhalts gemacht. 

Ich werde das Board erstmal in meiner Schublade parken (0x3d) und in ca 1-2 Monaten public give-away markieren falls ich nichts Gegenteiliges von dir höre. 
Komm doch auch mal wieder vorbei. 

Alles Gute
Bfritz0815

![img_20170425_132917](https://cloud.githubusercontent.com/assets/776715/25383277/aa461aae-29bb-11e7-8f3a-0fed2f5f3cfa.jpg)

**Comment by Bfritz0815** [comment]
labled and entered into wiki as empty
