### ISSUE TITLE
tardis 0x66 wer ist denny?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#103]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Denny vorstellen?

**Comment by tabascoeye** [comment]
"Danny" ist noch Mitglied.

**Comment by Bfritz0815** [comment]
@tabascoeye @dannyedel  ich hab gestern die Wikiseite zur Tardis geupdated. Damit hat sich das Meiste hier erledigt. Ich nehm jetzt einfach mal an, dass die Schublade noch benutzt und gebraucht wird. Man korregiere mich, falls ich mich da irre.
