### ISSUE TITLE
tardis 0x67 is whilo noch da?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#104]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Hog vorstellen?

**Comment by tabascoeye** [comment]
@whilo ist noch Mitglied.

**Comment by whilo** [comment]
Ja, ich lebe noch :)

**Comment by Bfritz0815** [comment]
@whilo Wie stehst du zu den Fragen 2 und 3 in dem Ticket? (Rein freiwillig)

**Comment by whilo** [comment]
Die Schublade würde ich gerne noch behalten. Ich würde bescheid geben, wenn ich sie nicht mehr benötige. Für die Wall-of-Nerds müsste ich wohl mal vorbeikommen und mir das anschauen.
