### ISSUE TITLE
tardis 0x73 move / dispose netzteil

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#107]
@Don42 bezieht sich das "don" aufm etikett auf dich?

**Comment by tabascoeye** [comment]
Ist "don" eingelasert? Dann handelt es sich imho um ein Laptopnetzteil für eines der Sticklaptops.

**Comment by Bfritz0815** [comment]
Nichts gelasert. Isn Einbaunetzteil. Beschriftung is auf Aufkleber.

![img_20170312_200805](https://cloud.githubusercontent.com/assets/776715/23834989/b88b8d8e-075f-11e7-887b-b9176542845c.jpg)

**Comment by Don42** [comment]
Wurde mehrfach in der E-Ecke als Netzteil verwendet und für irgendwelche Blinkenlights auf einem Event.
Ich brauche es nicht mehr.

**Comment by Kunsi** [comment]
Wenn "dispose", bitte mittels Dafo/Hotaru/ranlvor/whoever in Richtung KL schicken.

**Comment by Bfritz0815** [comment]
@Ranlvor Hi, kannst du der Gerät demnächst nach KL mitnehmen? Kunsi würde das wohl wollen. Danke

**Comment by Ranlvor** [comment]
Spedition Ranlvor bestätigt den RaumZeit-Transportauftrag
Von: RaumZeitLabor, 29.04.2017
Nach: Chaos Inkl, 03.05.2017
Zeitreisegebühr entfällt wegen geringer zeitlicher Distanz.

**Comment by Ranlvor** [comment]
@Kunsi ich rate dir dazu dir die Kabel von dem Netzteil mal in Ruhe genau anzugucken. An einem fehlt nämlich ein Molexstecker und wurde durch Isoband ersetzt. Ich weiß nicht, ob du da was saubereres hinmachen möchtest.

**Comment by Kunsi** [comment]
Wheeee … got it. Sauber machen wird überbewertet, ich steh auf schmutzige Dinge 😈
