### ISSUE TITLE
tardis 0x74 ungelabelt, beinhaltet ein kleinteil von abrock

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#108]
bitte um leerung und freigabe (label weg und in wiki als leer eintr)

**Comment by abrock** [comment]
Was für ein Kleinteil genau?

**Comment by Bfritz0815** [comment]
ein Gehäuse mit "Verbatim" drauf
![img_20170312_193752](https://cloud.githubusercontent.com/assets/776715/23834779/4a74da60-075c-11e7-9306-54c2f5867bdf.jpg)

**Comment by abrock** [comment]
ah, ich erinnere mich dunkel, kannst du das in 0x00-0x02 oder 0x90 unterbringen?

**Comment by Bfritz0815** [comment]
@abrock  habs in 0x90 getan. gebe nun die 0x74 frei. Danke.
