### ISSUE TITLE
tardis 0x78 ist zerodtime noch da?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#109]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:zerodtime vorstellen?

**Comment by tabascoeye** [comment]
1. Ja es handelt sich um einen Typ namens "Ingo" aka @pfeyffer

**Comment by s1lvester** [comment]
Eindeutig multi-account. --> kickban! 🤣
