### ISSUE TITLE
Schrott-Entsorgung

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#11]
Einige Instanzen nachweisslichen Schrotts:

- [x] Metallgehäuse/Metallplatten bei auseinandergenommenen Geräten von Elektroteilen trennen
- [x] alter Kühlschrank vorne im Hauptraum
- [x] alter Kühlschrank oben im Getränkelager
- [ ] MRMCD-Leute entsorgen bitte alle Dinge alter MRMCDs, die sie weder weiterverwenden noch herschenken oder mitnehmen wollen
- [x] tardis-Mittelrippen unter den Schränken im textillager auf den Metallschrott
- [x] abrock holt die weiteren Mittelrippen aufm Tisch neben tardis1 ab

**Comment by abrock** [comment]
Ich nehme die Mittelrippen am Samstag oder Sonntag mit, bitte nicht wegwerfen.

**Comment by abrock** [comment]
Ich habe die Mittelrippen mitgenommen.

**Comment by else** [comment]
Dafo fährt nächstes Wochenende zum Schrottplatz.

**Comment by Bfritz0815** [comment]
@abrock wir haben weitere 3-4 Mittelrippen derzeit auf dem Tisch neben Tardis 1 liegen. kannste auch mitnehmen. Thanx

**Comment by abrock** [comment]
@Bfritz0815 Mache ich wenn ich das nächste Mal mit Auto ins RZL komme, danke. Wahrscheinlich nächsten Samstag.

**Comment by abrock** [comment]
Ich habe die Mittelrippen mitgenommen und große Teile des Elektroschrotts entsorgt. Es sind noch die Kühlschränke und der alte Drucker da, soll der alte Drucker entsorgt werden? Wenn er noch funktioniert wäre es ggf. eine Option, ihn über ebay Kleinanzeigen zu verschenken. Selbes Spiel mit den Kühlschränken / dem altem Fernseher?

**Comment by tabascoeye** [comment]
Verschenken geht auf ebay Kleinanzeigen sehr gut. Man wird nur ziemlich zugespammt mit Anfragen...
(Für die Stühle kamen bei mir so 20 Anfragen in einer Stunde)

**Comment by s1lvester** [comment]
done? close? steht eigentlich (tm) nix mehr ohne namensschild rum

**Comment by steeph-k** [comment]
Done for now bis auf den MRMCD-Punkt.

**Comment by Bfritz0815** [comment]
closed, da die tischplatten nun zum mitnachhausenehmen Stapel wandern. Werde zu dem noch eine issue machen mit ner Liste der Sachen und Besitzer.
