### ISSUE TITLE
tardis 0x92 farbe ungelabelt

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#113]
- labeln
- leeren?
- in wiki

@abrock wg farbe frag ich mich: is das dein department?

**Comment by abrock** [comment]
Ist vermutlich vom Tür-Öffner Tag, wird jedes Jahr zum Anmalen von Holzfiguren benutzt.

**Comment by s1lvester** [comment]
beschriftet.
