### ISSUE TITLE
tardis 0xA0 deramon

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#114]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Deramon vorstellen?

**Comment by tabascoeye** [comment]
1. jupp
2. vermutlich

**Comment by s1lvester** [comment]
@Bfritz0815 Werden die ganzen Issues auch geclosed? Oder was passiert mit denen jetzt?

**Comment by Bfritz0815** [comment]
@s1lvester Sobald jemand sich darum gekümmert hat, Frage 3 zu klären gerne. Also: Es-müsste-mal TM jemand TM den Deramon kontaktieren und ne Zusage/Absage o.ä. beschaffen. Allgemein bin ich sehr dafür, issues erst zu closen, wenn alle Fragen darin geklärt sind.

**Comment by s1lvester** [comment]
Kraft meines diktatorischen Größenwahns ist dieses Issue nun gelöst.
