### ISSUE TITLE
RZLGamejam 2017 Orga

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#117]
Wikiseite ist angelegt: https://wiki.raumzeitlabor.de/wiki/RZLGameJam2017

TODO:

- [x] Genaue Startzeit vereinbaren (sonst kann man das niemandem kommunizieren)
- [x] Gibt's nen Eintrittspreis? Falls ja: wieviel? Falls nein: woher kommt das budget für essen/trinken/etc?
- [x] Welches Thema hat der Gamejam?
- [x] Teaser-Text schreiben (1 Absatz)
- [x] Teaser-Text in Wiki-Seite
- [x] Wikiseite: generelle Eventddaten eintragen und Seitenbox-Template nutzen
- [x] Teaser und Zeit-Info als Blogbeitrag einstellen
- [x] Teaser in Kalender-Eintrag
- [x] Was tun wir um die Getränkeversorgung sicherzustellen
- [x] Lebensmittelversorgung?
- [x] Wettbewerber? Preise für Gewinner? Jury?
- [x] Vertwittern mit Einladung als at-Raumzeitlabor
- [x] An Bekannte vertwittern
- [x] HSHD informieren

**Comment by uwap** [comment]
Danke. Steht auch schon alles soweit so auf unserer Todo. Wir kümmern uns.

**Comment by Bfritz0815** [comment]
@uwap @steeph-k wenn die Punkte 1-6 oben erledigt sind (also eine informative Wiki-Seite existiert), kann ich den Event kommunizieren. (An die Hochschule etc) Ansonsten wird es für die Planung anderer Leute zu knapp.

**Comment by uwap** [comment]
@Bfritz0815 Steeph und ich werden uns heute Abend kümmern.

Am 26. März 2017 17:56:23 MESZ schrieb Bfritz0815 <notifications@github.com>:

**Comment by steeph-k** [comment]
Startzeit: Samstag, 29.4., 12 Uhr gemeinsames Mittagessen, 14 Uhr Start

Lebensmittelversorgungsaufgaben sind bereits delegiert. Budget wird auf dem nächsten Plenum beantragt.

Eintritt kostenlos/freiwillige Spende

Thema ist noch nicht ganz klar, soll aber sehr allgemein gehalten werden, sodass bereits vorhandene Ideen nicht ausgeschlossen werden.

Keine richtige Preisverleihung, evtl. spontan festgelegte Kategorien mit honorable mentions

Anmeldeformular geht in den nächsten Tagen online. Twittern/Verbreiten ergibt ab dann mehr Sinn.
