### ISSUE TITLE
Fucking nervige E-Mail Notifications abstellen

### ISSUE THREAD

**Issue by echox** [raumzeitlabor/rzl-tuwat#12]
tuwat ist super aber sollte nicht Github Notifications an die Liste schicken.
Notifications kann man hier ja Problemlos nutzen oder seine persoenlichen Einstellungen anpassen.

raumzeitlabor@ einfach als Dispatcher fuer so Kram zu benutzen ist eher doof.

**Comment by s1lvester** [comment]
+1

**Comment by else** [comment]
Ich find schon, dass das auch an die Liste gehen sollte. Es ermöglich auch Leuten ohne Github Account, darauf zu antworten. Ich gehe davon aus ihr könnt euren Emailclient bedienen?

**Comment by echox** [comment]
Antworten bleiben dann aber auf der Liste und tauchen nicht hier auf, was das nachlesen von Diskussionen eher schwierig macht. Kommunikation dann auf 2 Medien zu verteilen ist auch doof.

Automatisierte Notifications an Mailinglisten zu verschicken, auf der normale Konversation stattfindet ist eher nervig und bisher haben wir auch fuer zum Beispiel Newsletter, Accounts, etc. immer info@ benutzt.

Selbstverstaendlich kann ich meinen E-Mail Client bedienen, du aber bestimmt auch github.

**Comment by else** [comment]
> Antworten bleiben dann aber auf der Liste und tauchen nicht hier auf, was das nachlesen von Diskussionen eher schwierig macht. Kommunikation dann auf 2 Medien zu verteilen ist auch doof.

Falsch, siehe hier: https://github.com/raumzeitlabor/rzl-tuwat/issues/1#issuecomment-153154815

> Automatisierte Notifications an Mailinglisten zu verschicken, auf der normale Konversation stattfindet ist eher nervig und bisher haben wir auch fuer zum Beispiel Newsletter, Accounts, etc. immer info@ benutzt.

Antworten auf Issues würde ich als "Konversation" bezeichnen.

**Comment by echox** [comment]
Cool.

Bestimmt findet hier auch Diskussion statt.
Zum Grossteil werdens das aber wohl Notifications sein, weil jemand das Issue "Kueche aufraeumen - Die Kueche sieht scheisse aus" usw. angelegt hat.

Bei Bedarf kann man das dann ja immer nochmal auf die Liste packen. Haben wir mit der unsaeglichen Diskussion ueber die Homepage und dem kommentarlosen ueberschreiben von Abrocks furchtbaren Pony Postings via git force push ja auch gemacht.
infoscreen, rzl-homepage, etc. sind alles weitere Repos in denen ja durchaus auch Diskussionen und Konversation stattfindet.

**Comment by felicitus** [comment]
Ich bitte auch darum, das weiterleiten an die Liste zu lassen. Ist einfach nur Nervig.

**Comment by schinken** [comment]
Sehe ich auch so. +1

**Comment by silsha** [comment]
Ich finde es sinnvoll. Was hier besprochen geht, geht glaube ich allen auf der Mailingliste was an, auch die, die kein Github haben und es motiviert die Leute watzutun.

**Comment by felicitus** [comment]
Im Moment motiviert es mich eher, die ML abzubestellen. Opt-in ist gut, Zwangsoptin ist schlecht.

**Comment by silsha** [comment]
Ich sehe halt keinen Unterschied zwischen Github mit ML-Anbindung und direkt auf der ML diskutieren. Nur dass letzteres eher selten passiert und es hier auf Github gerade ganz gut läuft.

**Comment by schinken** [comment]
Was @felicitus sagt

**Comment by felicitus** [comment]
Was noch dazu kommt: Auf der raumzeitlabor@ Mailingliste sind vermutlich wesentlich mehr Menschen subscribed als der Raum Mitglieder hat. Ich glaube nicht, daß z.b. @schinken Interesse daran hat, was im Raum zu tun ist.

Wenn das mal über die ML flattert ist OK, aber im Moment ist es reiner Github-Spam.

**Comment by schinken** [comment]
Das ist auch der Grund, weshalb ich das als Spam auffasse. Den Rest von der ML lese ich ja sonst ganz gerne

**Comment by hax404** [comment]
Ich schliese mich @felicitus und @schinken an.

**Comment by thinkJD** [comment]
+1

Hat bei mir nur dazu geführt, dass ich die Mails Richtung Papierkorb filtere. Sie gar nicht erst bekommen wäre feiner.

**Comment by rzl-tuwat** [comment]
Ich hab die Adresse jetzt von der raumzeitlabor@ ML geworfen. Das hat da
nix zu suchen. Auch wenn ich die Todo Liste gut finde, so sollte doch
bitte jeder der möchte das selbst abonnieren.

Gruß Ben

Am Thu, 05 Nov 2015 05:36:17 -0800
schrieb "Timo A. Hummel" <notifications@github.com>:

**Comment by else** [comment]
Ok, sorry NOC :cry:

**Comment by slowpoketail** [comment]
Ich finde Emailbenachrichtigungen ohne Github ganz sinnvoll. Auf raumzeitlabor@ dann aber eher doch nicht. tuwat@ einrichten?

**Comment by maikf** [comment]
Das NOC hat gesprochen, Issue ist geclosed.

@slowpoketail: da man sich dort manuell registrieren müsste, macht es auch keinen Unterschied
ob man das dort (tuwat@) oder hier tut.

**Comment by schneider42** [comment]
Da ich eh alle GitHub-mails wegfiltere hab ich hiervon gar nichts mitbekommen :)
