### ISSUE TITLE
Gewürzregal in der Küche (was: Defrag der Küche)

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#120]
Für nächsten W+D:

- Schubladen entmisten
- E-Geräte sichten
- Gewürze sichten

**Comment by Don42** [comment]
Unklar ob ich es heute ins RZL schaffe. Wenn nicht mache ich das nächsten Samstag.

**Comment by uwap** [comment]
Wie ist da der Stand? Ist das erledigt worden? Ich würd das gerne beim nächsten W+D noch mal tun.

**Comment by Don42** [comment]
Ein Teil wurde gemacht. Bin glaube ich aber nicht über das Gewürzregal hinaus gekommen. Gewürze sollte zumindest ausgemistet sein. Das Regal reinigen müsste man aber bestimmt mal wieder. brainfreeze und ich hatte da glaube ich ein paar Idee für bessere Regale. Genauen Stand weiß ich aber gerade auch nicht mehr.
Wenn das nächste W+D nicht mit der MRMCD kollidiert sollte ich auch wieder da sein.

**Comment by uwap** [comment]
Fürs Gewürzregal würde ich ein recht dünnes Regal vorschlagen, wo Gewürze nicht voreinander, sondern nur nebeneinander stehen können.

**Comment by Ranlvor** [comment]
@Don42 das nächste W+D ist nächsten Sonntag und kollidiert daher nicht mit der MRMCD

**Comment by Don42** [comment]
@uwap Hatten da ein paar Ideen. Unter anderem mehrere Ebenen mit Schräglage. Bräuchte man aber auch entsprechende Behältnisse. Fett vom Kochen ist auch ein Problem, weshalb es vermutlich Sinn macht etwas zuenes zu bauen.
@Ranlvor Ok, da bin ich noch in Kroatien.

**Comment by uwap** [comment]
Fürs Gewürzregal würde ich ein recht dünnes Regal vorschlagen, wo Gewürze nicht voreinander, sondern nur nebeneinander stehen können.

**Comment by Don42** [comment]
Da die Gewürze unterschiedlich groß sind ist das nicht wirklich machbar. Entweder von den kleinen passen mehrere voreinander oder die großen passen nicht mehr drauf. Wir wollten da gerne was mit Türen haben, damit sie nicht so schnell verdrecken.

**Comment by uwap** [comment]
Fixed at W&D
