### ISSUE TITLE
Boden-Erneuerung in der Küche

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#121]
Der Boden ist nicht flächendeckend. Das wird u.A. das Reinigen erschweren. 

Idee:

- "nicht wirklich Laminat" flächig bis an die Wand (ist aktuell nicht gegeben)
- nicht nur bis zur Wand, sondern auch etwas an der Wand hoch (erspart Leiste und schützt die Holzwand zur E-Ecke vor Feuchtigkeit)

**Comment by Don42** [comment]
Der Plan war nicht wirklich Laminat. Genauer Belag noch unklar. Am liebsten etwas Wasserdichtes bis 20cm die Wand hoch.

**Comment by uwap** [comment]
Es gibt auch so Materialien wie Vinyl die dann Laminatähnlich aussehen, aber leicht zu reinigen sind.

**Comment by tabascoeye** [comment]
Mir wäre ein fugenloser Industrie (PVC?) Boden von zB Freudenberg am liebsten

**Comment by Don42** [comment]
Industrieboden hätte definitiv auch meine Stimme.

**Comment by aikinci** [comment]
Ich könnte ein Angebot für einen Epoxyd boden machen falls gewünscht.

**Comment by tabascoeye** [comment]
@aikinci Angebot immer. Die Frage wäre wie kompliziert das werden würde. Wir wollen ja nur die Küche machen. Wir bräuchten also eine Schiene/Begrenzung an 2 Seiten und vermutlich auch eine Abdichtung zu der OSB Wand zur E-Ecke.

**Comment by aikinci** [comment]
Kann jemand mal die Fläche grob ausmessen und mir ein paar bilder von der Küchen und den jeweiligen Ecken machen. Ich kann die tage arbeitsbedingt nicht oft vorbeikommen. Dann könnte ich das Angebot schreiben.

**Comment by aikinci** [comment]
Ich habe mir das letztens mal angesehen. Dort ist ja schon ein PVC boden drin bedeutet man kann drauf gar kein Epoxy machen ohne den PVC rauszunehmen. Was man machen könnte PVC raus und schauen was drunter ist und dann entscheiden z.B. wenn fliesen drunter sind funktioniert epoxy sehr gut.

**Comment by uwap** [comment]
@aikinci Da drunter sind OSB Platten.

**Comment by aikinci** [comment]
Wenn die fest verschraubt oder verklebt auf dem Untergrund sind dann kann man mit Epoxy arbeiten. Falls die nur unzureichend fest draufliegen muss man den Untergrund zuerst bearbeiten z.B. eine dünne nievelliermasse und dann den Epoxy drauf. Wieso sind da OSB platten drauf. Das ist das ungewöhnlichte bodenbelagsmaterial das ich gehört habe. Ausserdem muss ja da drunter auch der Beton bzw der Estrich des gebäudes sein. Dort drauf den Epoxy wäre besser und langelebiger.

**Comment by uwap** [comment]
@aikinci Da scheint irgendein unebener härterer Boden drunter zu sein. Uneben ist ein Problem, oder?

**Comment by aikinci** [comment]
Ja uneben ist nicht geeignet für Epoxy da das nicht unebenheiten ausgleicht sondern nur wie eine dünne wasserfeste Schutzschicht auf die untere Schicht draufkommt. Das macht aber nichts. Man kann auf den unebenen Boden bei kleineren unebenheiten Nieveliermasse draufmachen das gleicht alle unebenheiten aus oder man verlegt gleich einen Estrichboden der dann das gleiche macht und auf diese wird dann der Epoxy verklebt. Das müsste ich mir mal genauer anschauen. Das Hauptproblem wäre nur dass man für solche fundamentale arbeiten am besten die ganze Küche abbauen sollte da man nicht einfach an die Möbel heranarbeiten kann.

**Comment by Don42** [comment]
Wenn ich von den Lücken im Bodenbelag die wir im Raum haben ausgehe, ist da direkt die Beton Decke drunter.

**Comment by Ranlvor** [comment]
![2017-10-03 21 49 10](https://user-images.githubusercontent.com/230440/31152743-b203e9e0-a89d-11e7-80b2-d49f61030917.jpg)
Das links im Bild sieht für mich nach Holz aus. Gibt auch Löscher im Boden wo man mehr davon sieht, hatte dieses eigentlich geschossen wegen dem anderen Material.

**Comment by aikinci** [comment]
Im Bild ist jetzt nicht sehr viel erkennbar für mich aber die Frage ist doch sind wir bereit den Küchenboden komplett aufzumachen um ihn dann zu erneuern oder brauchen wir eine weniger destruktive provisorischere Lösung.

**Comment by tabascoeye** [comment]
zweiteres. Wir als Mieter sollten nicht mehr Kohle in das Gebäude investieren, als unser Vermieter...

**Comment by uwap** [comment]
@tabascoeye Imho sollte da der Vermieter auch Geld investieren müssen. Unser Boden ist kein Zustand sondern eine Zumutung.

**Comment by aikinci** [comment]
Ich denke das wird ein thema fürs Plenum jemand sollte das notieren.

**Comment by uwap** [comment]
Ist erneuert. Vielen vielen Dank an @tabascoeye und @flederrattie
