### ISSUE TITLE
Tardis 0xAC Sebastiaan

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-tuwat#122]
Leider ist Sebastiaan erstmal nicht mehr in Mannheim und deshalb auch ab Juni kein Mitglied mehr.
Seine Schublade gibt er deshalb frei.

- [x] ausräumen falls noch was drin
- [x] entlabeln
- [x] im WIki als frei markieren

**Comment by Bfritz0815** [comment]
done
