### ISSUE TITLE
RZL GameJam Essensreste

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#128]
Es blieb viel Essen von der GameJam über.

- [x] Mail auf die ML: Essen ist Public für jeden
- [ ] Reste an die Tafel bringen

Hat Jemand ein Auto und würde das mit mir nächste Woche erledigen wollen?

**Comment by slowpoketail** [comment]
Brötchen stehen immer noch rum.

Ich hab mal die Packungen, die erst nächsten Monat ablaufen in den Vorratsschrank gepackt.

Der verbleibende Rest läuft morgen (14.05.) ab, sollte also entweder verspeist oder sonstwie verwertet werden. Evtl mache ich morgen einfach Arme Ritter damit.

**Comment by steeph-k** [comment]
On 13.05.2017 16:45, slowpoĸe wrote:
>
> Der verbleibende Rest läuft morgen (14.05.) ab, sollte also entweder 
> verspeist oder sonstwie verwertet werden.
>
Einfrieren geht auch, wenn sie die Tage nicht alle weg gehen.

**Comment by slowpoketail** [comment]
Jo, würde ich dann einfach mit dem Rest machen, zur Tafel bringen ist evtl schlecht wenn die schon abgelaufen sind.

**Comment by uwap** [comment]
Das meiste Zeug ist weg, wenige Sachen sind abgelaufen.
