### ISSUE TITLE
Liste der Ex-Mitglieder-Nicks

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#13]
Damit auch normalsterbliche, nicht-allwissende Leute erkennen können, welche Kisten zu ex-Mitgliedern gehören, wäre eine Übersicht der Ex-Member nice. (Vorbedingung für Aufräum-Aufgaben)

**Comment by else** [comment]
Das kann denke ich nur vorstand@ sehen.

**Comment by Bfritz0815** [comment]
Mail an Vorstand abgesetzt mit den Nicks der Leute, deren Kisten dort lagerten. Die Kisten sind nun  im Hauptraum: vorne an der Tafel oder oben im Hochregal.
