### ISSUE TITLE
Annette will nicht drucken

### ISSUE THREAD

**Issue by BigMacTobi** [raumzeitlabor/rzl-tuwat#131]
![annette druckt nicht](https://cloud.githubusercontent.com/assets/27957985/25978010/ea5d7d6a-36bf-11e7-8269-06e10caa3e4a.png)

Ich wollte etwas ausdrucken aber sie gibt mir immer wieder diese meldung.

**Comment by tabascoeye** [comment]
> Dateiname

Hast du magische Sonderzeichen im Namen der zu druckenden Datei?

**Comment by BigMacTobi** [comment]
Nein, die Datei heißt "Vollmacht", bzw. "Vollmacht1".

**Comment by tabascoeye** [comment]
bist du dir sicher, dass du sowas in einem Hackerspace drucken möchtest?

**Comment by s1lvester** [comment]
🙄

**Comment by BigMacTobi** [comment]
Ja, weil ich sonst nirgendwo drucken kann. habs inzwischen auch geschafft indem ich es als pdf gedruckt hab. andere formate mag annette scheinbar nicht.
