### ISSUE TITLE
Preisbeschriftungen im Kühlschrank

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#132]
An den entsprechenden Gittern im Kühlschrank. Man räumt dann einfach die Getränke da ein, wo sie preislich hingehören, für weniger verwirrung.

**Comment by tabascoeye** [comment]
aber mit Text, damit nicht freundliche Einräumer eine Flora in die 1,00€ Abteilung räumen

**Comment by uwap** [comment]
Du meinst sowas wie "Flora 2,00€, Club Mate 1,50€, Softdrinks (0,5) 1,50€, Softdrinks (2,0L) 2,00€" etc? Klingt sinnvoll.

**Comment by tabascoeye** [comment]
Ja genau (Flora sind 0,3 Flaschen und wir nehmen iirc 1,50€ dafür, weil teuer im Einkauf)

**Comment by uwap** [comment]
Wir haben sowohl 0,3l als auch 0,5l Flora. Das müsste man mal™ alles ordentlich dokumentieren.

**Comment by tabascoeye** [comment]
Öh. Watt? Ich sehe keinen Grund für 0,33, wenn wir 0,5 bekommen können.
Imho war der Grund, dass Rolling Store keine 0,5er hatte.

**Comment by uwap** [comment]
Derzeit haben wir beide und da war jetzt eig die Überlegung erst die 0,33l einzuräumen, damit die wegkommen und dann die 0,5l einzuräumen. Ich bin auch dafür wieder 0,5l zu bestellen.

**Comment by Don42** [comment]
Das Problem war das der Rolling Store zu dem Zeitpunkt keine 0.5l Flora da hatte. Zum annehmen war ich nicht da, ich habe es erst später gesehen und ihn drauf angesprochen. Er weiß jetzt das wir Flora und Premium nur 0.5L und nichts anderes annehmen.

**Comment by uwap** [comment]
Ich habe mal provisorisch™ ein paar Beschriftungen auf die Innenseite der Kühlschranktür gemacht. In Zukunft müssen wir uns da mal was besseres ausdenken.

**Comment by Bfritz0815** [comment]
ich schau mal, ob ich morgen da was improvisieren kann...

Langfristig wären 3d-gedruckte Clipse geil, wo man Label vom Labeldrucker vorne drauf machen kann (aber das is mir zu hoch)...

**Comment by Ranlvor** [comment]
Die Idee mit den 3D gedruckten Clipsen finde ich geil. Ich guck mal, ob ich ein Modell finde / ob ich OpenSCAD beibringen kann, was ich gerne hätte.

**Comment by steeph-k** [comment]
On 05.08.2017 23:00, Ranlvor wrote:
>
> Die Idee mit den 3D gedruckten Clipsen finde ich geil. Ich guck mal, 
> ob ich ein Modell finde / ob ich OpenSCAD beibringen kann, was ich 
> gerne hätte.
>
Zur Inspiration: http://www.ebay.de/itm/332193862374

**Comment by Bfritz0815** [comment]
Alternativ könnte man label-clips als be-labelbare "meterware" drucken. (Ich hab da mal meine 50 cent skizziert)

![label-clip](https://user-images.githubusercontent.com/776715/28998898-a1f41808-7a36-11e7-83b0-157543fc848d.png)

**Comment by Ranlvor** [comment]
Ich hab mal Version alpha meiner Idee gedruckt und montiert… Weiß jetzt, was ich anders designen muss…

![2017-08-06 01 04 52](https://user-images.githubusercontent.com/230440/28999361-2ef8ff4a-7a44-11e7-9acc-2a694adb92f2.jpg)

Idee: Mit dem Labeldrucker des RaumZeitLabors 24mm-Labels drucken, die mit diesem Halter im Kühlschrank befestigt werden können.

**Comment by steeph-k** [comment]
Sieht nice aus! Aber kleben müssen die Labels damit ja nicht, oder? Dann 
wäre das dicke Papier aus Annettes Fach 3 wahrscheinlich billiger.

**Comment by Ranlvor** [comment]
Kleben ist nicht notwendig, der Halter sollte auch für nichtklebende Labels (24mm x 67mm, 3mm oben und unten werden vom Schild verdeckt) funktionieren. Also wenn du da was mit Annette drucken willst: gerne, für den Prototypen habe ich den Labeldrucker verwendet, weil das schneller ging.

**Comment by uwap** [comment]
Wir haben jetzt die Halter für die Preisschilder. Afaik wollte @slowpoketail eine Vorlage für Anette machen. Wenn die fertig ist close ich das.

**Comment by uwap** [comment]
Ich hätte gern eine kleine Box oder Schale auf dem Kühlschrank stehen, in dem diverse vorgedruckte Labels sind, damit man die beim Einsortieren des Kühlschranks schnell ändern kann. Ich denk mir da mal was aus.

**Comment by Bfritz0815** [comment]
@uwap Ohne Vorlage geht auch. Einen Kostenvorteil sehe ich da im Endeffekt nicht:
Wenn man mal bedenkt, dass man dann ne A4 Karton und ein A4 Laminier-Folie und ne Tonne Zeit verbrauchen würde um ein oder zwei einzelne Labels nachzudrucken, dann relativiert sich jedes pro-Papier/contra-label Argument. 

Bezüglich Box: ich hab da mal ne Label-Box unter die Kronkorken-Box am Kühlschrank gepackt.

**Comment by uwap** [comment]
Wir haben jetzt einfach Labels. Als Box kann man ja einfach Tupperzeug dahin packen. Close
