### ISSUE TITLE
Rolling Store Bestellung

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#133]
Im Rolling Store müsste mal wieder bestellt werden:

- Braumeister Limo
- Flora
- Premium Cola
- (Soli Mate)
- Wasser (viva-con-aqua)
- Limo Zeug (Nicht fritz)

Bestellen wir Club Mate auch da oder machen wir das normalerweise mit Loscher zusammen? Wer kann mir vormittags beim Be- und Entladen helfen? Wer kann Dienstag mit mir schauen wie viel von was wir bestellen wollen?

#### Todo
- [ ] Ermitteln was wo bestellt werden muss
- [ ] Bestellen
- [ ] Alles unter https://wiki.raumzeitlabor.de/wiki/Getr%C3%A4nke dokumentieren

**Comment by uwap** [comment]
cc @slowpoketail

**Comment by tabascoeye** [comment]
* Wir haben bisher immer direkt bei Loscher bestellt, weil meistens gleich 2-3 Paletten == Staffelpreise
* Wir haben eine eigene Ameise (sollte mal beschriftet werden!)
* Das Leergut sollte ganz gut sortiert sein (bei Loscher anmelden, dass wir 3 Paletten Leergut haben!)

Würde eine Mische aus CMC, Mate, ICE-T und evtl eine Mische an deren Softgetränken (Apfel-kirsch, ACE,...)  vorschlagen.

**Comment by uwap** [comment]
@tabascoeye Kümmerst du dich um die Bestellung bei Loscher und ich mich um die beim Rolling Store? Wollen wir uns Dienstag mal zusammensetzen und schauen was bestellt werden muss?

**Comment by Don42** [comment]
Braumeister kam ziemlich sicher auch nicht vom Rolling Store. Dort haben wir nur Premium (Cola/und anderes) und Flora Mate bestellt.

**Comment by tabascoeye** [comment]
Braumeister und Oettinger Glorietta haben @flederrattie und ich besorgt in letzter Zeit. 8-10 Kisten bekomme ich in mein Auto, ist halt nur ein Tropfen auf den heißen Stein.

**Comment by uwap** [comment]
Hier kam die Idee auf beim Rolling Store mal ein paar Kästen an gemischten Soft Drinks zu bestellen, um eventuell mal neue Alternativen zu finden. Aktuell haben wir leider meist nur Koffein- und Alkoholhaltige Getränke.

**Comment by tabascoeye** [comment]
Wir bringen morgen wieder 8 Kisten Verschiedenes mit.
Ich würde bei der loscher Bestellung zb Wasser und apfel-Kirsch mitbestellen.

**Comment by Bfritz0815** [comment]
Bin sehr für Loscher Apfel-Kirsch zu haben. Bei Wasser wär ich dafür welches der Marke "Viva-con-aqua" zu bestellen (etwas teurer, aber wir können den Preis ja ganz normal weiterrechnen (x2 und aufrunden auf nächste ganze Kreuz) und die Marke hat ne wohltätige Komponente. Wer Wasser günstig will, kann auch den Wasserhahn nutzen...).

**Comment by uwap** [comment]
Das mit dem Wasserhahn kann ich so nicht unterschreiben. Das Wasser hier ist sehr verkalkt. Aber ich habe tatsächlich auch nichts dagegen nur Viva Con Aqua zu holen. Ich habe heute ein Sixpack Orangensaft geholt, damit es mal ein wenig abwechslung gibt.

**Comment by uwap** [comment]
Mag sich Jemand um die Rollingstore bestellung kümmern? Eig wollte ich das morgen tun, aber aufgrund der Diskussionskultur im RZL (Scheinbar ist alles was man tut immer falsch!) habe ich gerade wenig lust. Irgendwer anderes?

**Comment by Ranlvor** [comment]
Habe gerade mit dem Rolling Store telefoniert. Sie liefern nächsten Dienstag, 15 Uhr. Werde mich darum kümmern.

    2x Soli Mate 0.5l (Zum mal probieren. EK: ~1,10€ -> VK: 2€)
    4x viva-con-aqua leise 0.75l
    4x viva-con-aqua laut 0.75l
    3x Braumeisters Limonade Zitrone 0.5l
    3x Braumeisters Limonade Orange 0.5l
    3x Braumeisters Limonade Holunder 0.5l
    3x Braumeisters Limonade Grapefruit 0.5l
    22x Premiumcola 0.5l
    10x Flora Power 0.5l

Was ich sonst noch so an Infos erhalten habe:
* Kapazität im Lieferfahrzeug ist wohl 100 Kisten/Bestellung. Die nächste Bestellung könnte man also auch etwas größer planen. (Hatte ursprünglich auf 40 Kisten geplant)
* In Sachen Limo können sie uns Libella anbieten in verschiedensten Sorten zu einem Preis um 0,50 €/Flasche (=> Verkauf um 1€/Flasche)
* Sie freuen sich sehr mal wieder von uns zu hören

**Comment by Ranlvor** [comment]
(vergessen zu schreiben)
@slowpoketail das RZL hat nächsten Dienstag Soli Mate, solange Vorrat (2 Kisten) reicht.

**Comment by Kunsi** [comment]
Y U NO Club-Mate?

**Comment by Ranlvor** [comment]
Weil ich gehört habe, dass demnächst eine Lieferung von Loscher kommen könnte und der Mate günstiger hat.

**Comment by uwap** [comment]
@ranlvor Großartig! Vielen Dank fürs Kümmern. Sofern die Baustele noch länger anhält, wäre ich stark dafür libella zu bestellen. Wenn die Baustelle nicht mehr da ist, können wir vielleicht ja bei Loscher bestellen. Ich würde mich da auch bereit erklären vormittags vorbei zu kommen, sofern ich nicht als einziger die Bestellung entgegen nehmen muss.

**Comment by abrock** [comment]
Was hat das eigentlich mit der Baustelle zu tun? Die Loscher-Fahrer können einfach über die Turbinenstraße zum Rolltor fahren.

**Comment by uwap** [comment]
@abrock Kriegen die das denn bei all der Loscher Verpeiltheit auch ordentlich hin?

**Comment by Ranlvor** [comment]
Rollingstore war da. Braumeisters hat er leider keine so schnell gekriegt, dafür waren aber 2 Kisten Wintermate dabei.

Und ich muss sagen: Wow ist der flott. Musste einmal um's Gebäude laufen weil ein Tor zu ging und in der Zeit hatte der die komplette Palette ausgeladen. Und dann hat er sie uns noch bis ins Getränkelager gefahren.

An Pfand würde er uns gefühlt auch alles außer Bitburger abnehmen, auch leere Ramen und Paletten. Oh und wir haben 1 Palette mehr Pfand im Lager als ich dachte.
