### ISSUE TITLE
Sperrmüll

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#134]
- [x] Den alten schwarzen Tisch entsorgen (Der ist müll!)
- [x] Alte Holzplatten vom Regal im Eingangsbereich und der Snackbar entsorgen
- [x] Das kleine alte Snackbarregal entsorgen
- [ ] Schauen was es sonst noch so für Dinge gibt, die entsorgt werden müssen
- [ ] (Task für mich): Vermieter fragen, ob wir den Holzcontainer mitnutzen dürfen.

**Comment by Bfritz0815** [comment]
Stand aktuell:

- Das kleine Regal mit den Glasböden ist im Lager Ebene 2.
- Der schwarze Tisch ist weg.
- Die anderen Regalteile sind erstmal im Lager bei den großen Holzteilen auf der rechten Seite. Die können wir ggf nuch für anstehende Sachen brauchen. Not urgent. Lager aufräumen ist ja sowieso interessant.

**Comment by uwap** [comment]
Aktueller Stand:

Wir dürfen den Holzcontainer nur für unbehandeltes Holz nutzen. Das Textilienlager wird zum Sperrmülllager umgebaut und wir werden uns um die Entsorgung von Sperrmüll nach dem Küchenumbau kümmern.
