### ISSUE TITLE
neue Garderobe

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#135]
Vorschäge:

1. https://www.ebay-kleinanzeigen.de/s-anzeige/garderobe-fuer-die-wand/695549412-87-3547
2. https://www.ebay-kleinanzeigen.de/s-anzeige/garderobe-glas-metall/695590601-87-703
3. https://www.ebay-kleinanzeigen.de/s-anzeige/ausgefallene-garderobe/695578354-87-1423

Meinungen? Alternativen?

**Comment by Bfritz0815** [comment]
Hier die Ikea-Variante:
http://www.ikea.com/de/de/catalog/products/20152634/
2 Stück davon, 
Dazu könnte man noch je 1 Dutzend S-förmige Haken nehmen um die Stangen der Ablage als weitere Aufhänger in 2. Reihe nutzen zu können. 

Was mein ich mit S-Haken? Die z.B. (natürlich sollte man auf die Größe der Stangen achten wg Durchmesser) https://www.amazon.de/gp/product/B01D300CK6/ref=s9_acsd_zwish_hd_bw_b2GX3QN_c_x_w?pf_rd_m=A3JWKAKR8XB7XF&pf_rd_s=merchandised-search-5&pf_rd_r=K4J7B9E57NDC19Q9DRA0&pf_rd_t=101&pf_rd_p=38bbed1e-fed5-57d4-ab8e-e4288cae3e55&pf_rd_i=2076565031

Einziger wunder Punkt: Gewicht. Sowas würde ich nicht an die aktuelle Garderobenwand hängen, sondern über Verstärkungen nachdenken.

**Comment by Don42** [comment]
Wenn ich wieder da bin schaue ich mal wo wir nach dem umräumen noch Platz haben. Vllt. können wir da ja was cooles selbst bauen.

**Comment by uwap** [comment]
Ich finde die fertigen Lösungen sehen alle sehr nett aus. Eine eigene Lösung fände ich eher nicht so geil.

**Comment by Don42** [comment]
Ok, schaut mal was ihr findet. Wenn das wieder an die Rückwand von Tardis 1 soll, noch mal schauen was das Brett aushält

**Comment by steeph-k** [comment]
Ich war seit dem Umbau noch nicht da, weiß also nicht wie da was so rein 
passen würde. Mehr Haken als bisher wären aber sicherlich sinnvoll. Ich 
müsste irgendwo noch eine Garderobenleiste aus einer Schule oder so 
haben. Die ist ca. 4 m lang und hat auch einige Haken. Mit Stangen und 
S-Haken wäre man aber flexibler und platzsparender.


On 06.08.2017 20:55, Bfritz0815 wrote:
> https://www.ebay-kleinanzeigen.de/s-anzeige/ausgefallene-garderobe/695578354-87-1423 
>
>
> Meinungen? Alternativen?
>
Das wäre mein Stil. Aber ich glaube, dass wir da etwas ansprechenderes 
selbt bauen könnten.

**Comment by uwap** [comment]
@Bfritz0815 Bist du Dienstag da? Falls ja, wollen wir da mal gemeinsam überlegen was das beste wäre und das zeitnah angehen?

**Comment by Bfritz0815** [comment]
@uwap Dienstage kann ich aktuell nicht versprechen. Meine Meinung zum Besten wäre: 

1. über Verstärkung der Wand nachdenken
2. Die Garderobe, die ich rausgesucht hatte dran hängen

Wenn Jemand ne Idee hat, das zu nem ähnlichen Kostenpunkt selbst bauen zu wollen, wäre ich natürlich nicht dagegen.

**Comment by Bfritz0815** [comment]
@uwap  Vorschlag zur Verbesserung:
Wir haben ne super Weltkarte der Unterseekabel (siehe #139 ) die gehört dem RZL und liegt aktuell nur so rum. 
Größenmäßig würde die an die Garderobe unterhalb der Aufhängungen passen. Man sollte aber nen Wasserschutz anbringen (Ne Acrylplatte davor?). 

Wenn wir die Garderobe etwas ausmisten, könnte man das Ding sogar sehen...

**Comment by uwap** [comment]
Wie groß ist die denn? Und wäre wirklich der Plan die ganzen Jacken vor diese schöne Weltkarte zu hängen?

**Comment by Bfritz0815** [comment]
Poster ist:
hoch ca. 108
breit ca. 147

Ich fänds auch schön, für die Karte nen besseren Platz zu finden, aber die Frage wäre: Wo ist der?
- Die Wand an der Werkstatt hat Platz, aber da wird was wahrscheinlich leicht dreckig
- Die Wand neben dem Hochregal oberhalb der Tardis (nur da siehts keiner)
- Hinter die Tafel unterhalb vom Panel
- An die Stahlträger an der Decke mittles Pony-Magie anheften (my Favorite)
- Evtl mal nach nem Umbau des Olymp an die Außenseite der Wand, die zum Raum hin zeigt?

**Comment by Don42** [comment]
![img_20170730_093504](https://user-images.githubusercontent.com/141622/29752852-e01f2150-8b65-11e7-9c24-9d5c3661b966.jpg)
Sowas wäre cool und würde weniger Platz wegnehmen.
cc @uwap

**Comment by steeph-k** [comment]
On 27.08.2017 20:25, Marco Kaulea wrote:
>
> Sowas wäre cool und würde weniger Platz wegnehmen.
>
Hmm, Schienen, wie zuvor hier vorgeschlagen nehmen aber auch wenig Platz 
weg, da man die Sachen zusammenschieben kann. Vielleicht auch beides 
kombiniert, also höhenversetzte Schienen.

**Comment by Bfritz0815** [comment]
Ich glaub die Lösung von Don würde stabiler an der Wand hängen. (Die oberen und unteren Schraubpunkte liegen weiter vertikal ausseinander)

Is ja jetzt nur mein Laien-Verständnis dazu. Hat da jemand solidere Einblicke?

Die Traglast wäre ja eine der Sachen, die verhinderthaben, dfass wir da einfach die IKJEA-Lösung angedübelt haben. 

Noch ein Vorteil: Die Stangen-Lösung bietet eine Art "Hutablage", diese Lösung bietet die Möglichkeit, sie ohne Ablage zu bauen. Vorteil: Wir brauhcen keine Hutablage und eine Hutablage würden die leute eh nur als Lagerraum für Kisten nutzen: Bis die das Ganze von der Wand reissen. 
Ohne Hutablage wäre das Ganze IMHO langlebiger.

**Comment by tabascoeye** [comment]
Ich frage mich ja weshalb wir eine Garderbe brauchen.
Die einzige Jacke, die ich da hängen sehe und nicht "Altkleidersammlung" ist, wäre echox' Motorradjacke.
Dafür reicht dann wohl 1 Haken.

**Comment by steeph-k** [comment]
Neulich hing auch ein Gürtel da.
Aber im Winter wird die Garderobe mehr genutzt. Auch ich hänge meine Jacke fast immer dort hin. Bei Veranstaltungen zu kälterer Zeit war schon manchmal jeder Haken mindestens doppelt benutzt. Auch an volleren Dienstagen waren es schon zu wenige.

**Comment by uwap** [comment]
Also die Garderobe wird auf jeden Fall genutzt. Insbesondere an Dienstagen.

**Comment by uwap** [comment]
Bezüglich Garderobenredesign bringe ich heute 5 Klemmbretter mit ins RZL. Dort werden dann die Fahrpläne eingehangen. Darüber kommen so Galerielampen. Was Kleiderhaken angeht finde ich den Voschlag von @Don42 noch am schönsten.

**Comment by uwap** [comment]
Ich würde vorschlagen dort wo vorher die Garderobe und ddas Snackregal waren stellen wir 3 IVAR Regale hin, zwei in 89cm Länge und eines in 48cm Länge. Das kleine wird das neue Propagandaregal. Die beiden großen werden zum Snackregal.

Als Garderobe nehmen wir einen einfachen Garderobenständer. Die einfachste Art um unter wenig Platz viele Jacken etc. unter zu bekommen.

**Comment by Bfritz0815** [comment]
Nette idee, haette da nur ein paar fragen:

Wohin mit den Schuhen, sodass man nicht im ganzen raum drueberfliegt?

Warum das Propaganda Regal (selten genuutzt) so prominent aufstellen?

Warum die snackbar weiter richtung muellabstellplatz expandieren?

**Comment by Bfritz0815** [comment]
Oh und:

Wohin mit den einzelnen Garderobenstaendern sodass sie nicht im weg
rumstehen? Die Stehlampen laufen ja auch nich so toll.

**Comment by Bfritz0815** [comment]
Hab gerade mit @uwap gesprochen. 
Die Idee wäre:
- Snackbar und propagandaregal neben Eingang (wie schon von Uwap vorgeschlagen)
- die neue Garderobe kommt unter die Treppen-Nische der Olymp-treppe

Entwurf:
An den Stützbalken unter der Olymptreppe könnten wir an den 3 Seiten, die nicht zum Durchgang zeigen, die alten Garderobenhaken anschrauben. 

Wir schrauben dann Kleiderhaken oder Kleiderhaken-Leisten an Holzleisten. Diese Holzleisten können wir horizontal an die Treppen-Unterseite schrauben. 

Damit hätten wir eine Anzahl von Haken, wie vorher. Gleichzeitig hätten wir eine mehrschichtige Garderobe wie für den anderen Standort angedacht war.

**Comment by Bfritz0815** [comment]
btw: Die schuhe können wir dann im niedrigsten Teil unter der Treppe parken

**Comment by uwap** [comment]
Wir haben ein Teil des neuen Regales aufgebaut. Wir brauchen noch 4 IVAR Bretter in der Größe 42cm x 30cm um das Propagandaregal noch etwas nach Links zu erweitern.

**Comment by uwap** [comment]
Wir haben eine Garderobe und sie wird genutzt.
