### ISSUE TITLE
Kasse für die neue Snackbar

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#136]
Vielleicht sowas: https://www.amazon.de/My-Charity-Boxes-klassische-Spendenbox-Beschriften/dp/B00LW4GW9Q/ref=sr_1_54?ie=UTF8&qid=1502045511&sr=8-54&keywords=spendenbox

Vorteile:
- Kann man direkt an Tardis montieren, dann wird's schwieriger, das abzunehmen. 
- Der Verschluss ist per  Vorhängeschloss, nicht per eingebautem Schloss (Wenn ein Vorhängeschloss zu leicht pickbar ist, kann man das einfach gegen ein komplizierteres austauschen)
- Wenn wir das hier besorgen, können wir die bisherige Kasse dort lassen, wo sie ist (dann haben wir ämlich auch eine für allgemeine Spenden, Veranstaltungen etc.)

Meinungen? Alternativen?

**Comment by uwap** [comment]
Also @tabascoeye würde es wohl erst ein mal reichen, die Kasse an ein Ivar Brett zu schrauben. Eine bessere Lösung sollten wir uns vielleicht aber langfristig suchen.

**Comment by tabascoeye** [comment]
Ich mag die Spendenbox, die @Bfritz0815 da vorgeschlagen hat schon sehr. Finde sie nur ziemlich überteuert für ein bisschen gebogenes Blech.
Wenns sowas in günstiger irgendwo gibt, wäre ich dafür.
Solange kann die alte Kasse gemoved werden. Immernoch besser, als ein komplett offener Behälter wie jetzt.

**Comment by Bfritz0815** [comment]
Hmm. Vielleicht ist das jetzt nur meine eigene Perspektive, aber irgendwie scheint das mit der Kasse eher ein Nicht-Problem zu sein. So weite weg ist die Kasse auf der Theke nicht und irgendwie hab ich noch keine konkreten Beschwerden über den 1,50 m Fußweg gehört. 

Evtl. könnten wir also auch ohne... Meinungen?

**Comment by tabascoeye** [comment]
eine neue Kasse mit Vorhängeschloß fände ich aus Gründen trotzdem sehr gut...

**Comment by Bfritz0815** [comment]
@tabascoeye  Kassenbrett ist jetzt einzeln vor der Theke. Ich hab vor, Di Abend da zu sein. Wollen wir da die Um-Monatge machen?

**Comment by tabascoeye** [comment]
ich hab nicht ganz verstanden, weshalb die snackbar jetzt wieder weiter weg vom kühlschrank steht.
Solange das alles nicht erstmal "eine Weile so bleibt", wüsste ich nicht, wo die Kasse final hin soll.

**Comment by Bfritz0815** [comment]
Ok. Das Rumrücken von snackbar und bald auch Kühlschrank neben die neue
Position der snackbar ist ne Aktion um ggf besseren durchgang zum nebenraum
zu bekommen.

Briefkasten etc könnten links vom snackregal an die tardis Rückseite.

Bis Morgen.

Am 16.10.2017 10:01 schrieb "TabascoEye" <notifications@github.com>:

**Comment by uwap** [comment]
@Bfritz0815 Ähhm. Meintest du nicht eher den Briefkasten als die Kasse? cc @tabascoeye

**Comment by Bfritz0815** [comment]
Ich hab die mail morgens geschrieben. Da bin ich froh wenn ich gweade aus
laufen kann.

Am 16.10.2017 10:16 schrieb "uwap" <notifications@github.com>:

**Comment by Bfritz0815** [comment]
Die lösung mit der kleinen, unabgeschlossenen Kasse im Snackregal und der Hauptkasse auf der Theke läuft aktuell schon seit Monaten prima. 
Die offene Kasse im Snackregal erlaubt sogar kleinere Beträge zu wechseln. 
Ich glaub, da haben wir ein gutes Mittelding zwischen "Kasse des Vertrauens" und Sicherheit. 

Closing.
