### ISSUE TITLE
Rednerpult und Aufzeichnungs Hardware: Storage

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#137]
Idee zur Diskussion:

Den Teil des Rednerpults, der aktuell aus Kisten besteht könnte man durch ein geschlossenes Regal ersetzen. 
Dort könnte man dann Kamera und Anderes zum Vorträge-Aufzeichnen unterbringen. 
Da wo diese Dinge bisher standen, können wir dann Tastatur und Mäuse etc. parken. 

Maße des bisherigen Setups zwischen Rollen und Pult-Aufsatz:
hoch: 80
breit: 60
tief: 45

**Comment by Bfritz0815** [comment]
Besta von Ikea könnte da gehen: http://www.ikea.com/de/de/catalog/products/30245850/
Türen dazu wären natürlich auch schön...

**Comment by Bfritz0815** [comment]
Preislage: 
25 € für den Schrank selbst: http://www.ikea.com/de/de/catalog/products/30245850/
10 € für die Tür: http://www.ikea.com/de/de/catalog/products/40364060/#/50291676

**Total: 35 €**
Die Rollen der aktuellen Konstruktion können wir unten dranschrauben. 
Das Oberteil vom Rednerpult  lässt sich erstmal einfach draufsetzen. 

Das Thema kann ich auch aum Plenum vertreten.

**Comment by steeph-k** [comment]
Finde ich gut. Die Kisten aus dem ehemaligen Eingangsbereichsregal, die 
jetzt am Fenster auf dem Boden stehen würden sich über den frei 
gewordenen Regalplatz freuen.

Wenn das von den Mapen her passt wäre ich dafür, das zu tun. Ein Brett 
dazu wäre auch nicht schlecht.

**Comment by Bfritz0815** [comment]
@steeph-k Danke fürs dran denken. Brett ist jetzt dazugekommen. Maße passen.

**Comment by uwap** [comment]
Das Plenum hat 60€ Budget für einen Schrank am Rednerpult gewährt. Ich würde vorschlagen, dass wir das zusammen mit der Küche bei Ikea kaufen. cc @Bfritz0815

**Comment by Bfritz0815** [comment]
Danke fürs Kümmern.

 Ich war am Wochenende zu broken um vorbeizukommen.

Am 13.11.2017 10:29 schrieb "uwap" <notifications@github.com>:

**Comment by uwap** [comment]
Um auf die 80cm Höhe zu kommen müssen wir alternativ 2 von diesen Korpen (Korpusse? Korpuus?) nehmen: https://www.ikea.com/de/de/catalog/products/70245848/

**Comment by tabascoeye** [comment]
ist inzwischen verbaut worden
