### ISSUE TITLE
Owner der Karte der Unterseekabel?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#139]
Auf Tardis 1 liegt hinten, nahe der Leiter-Abstell-Position eine großformatige Weltkarte mit allen Unterseekabeln. Die ist schön gemacht. 
Owner steht keiner dran und da oben hat niemand was davon. Ich könnte mir vorstellen, dass wir die an die Platte der Garderobe am Eingang hängen. 

Wäre dann nach dem Verstärken der Platte für Garderobenumbau sinnvoll. So voll wie die Haken aktuell sind, macht das wenig Sinn, da jetzt was hinzuhängen. 

Frage is nun: Wem gehört das Teil? (Und: Hat er/sie was dagegen, dass wir das Aufhängen?)

**Comment by silsha** [comment]
Die hat @else mitgebracht und gehört dem RZL. Kann aufgehängt werden.

**Comment by Bfritz0815** [comment]
Thanks. Closing
