### ISSUE TITLE
Neuen Beamer im Workshopraum anbringen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#14]
Wir haben einen neuen Beamer im Workshopraum. Er steht (vermutlich) im Workshopraum und müsste an die Decke desselbigen. :cat:

**Comment by yocky96** [comment]
Da der Beamer eine Spezialaufhängung hat, habe ich einen Adapter bestehend aus einer Holzplatte und Kabelbinder gebaut.
![beamer](https://cloud.githubusercontent.com/assets/1353163/11068055/e3cc069c-87cf-11e5-8ee3-69534c05020f.png)
Der Beamer hängt nun, aber ich konnte das ganze noch nicht Testen, da der Strom im Nebenraum zur Zeit nicht funktioniert (wahrscheinlich ist das lange VGA Kabel zur Decke noch kaputt).

**Comment by else** [comment]
+1 für Hackvalue

**Comment by silsha** [comment]
:+1:

**Comment by yocky96** [comment]
-> es liegt am VGA Kabel, ein neues wurde bestellt
