### ISSUE TITLE
Metro-Einkauf August 2017

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#140]
Bedarfsliste mit aktuellem Inventar-Stand ist hier verlinkt:
https://wiki.raumzeitlabor.de/wiki/Einkaufsliste_Snackbar

Legende:
grün = geht gut = lohnt sich immer (außer es ist viel vorrätig)
türkis = neu oder unsicher = falls letzter Stand bei 0 einkaufen
rot/orange = geht nicht gut, nicht mehr einkaufen

**Comment by Bfritz0815** [comment]
BTW: wir ham grad 3 Kisten mit Mars wegen (teils extrem) überschrittenem MHD weggegeben. Bitte kein Mars mehr kaufen. (Ist in der Tabelle auch rot markiert)

**Comment by uwap** [comment]
Danke für die Doku!

**Comment by uwap** [comment]
Es wurde eingekauft.
