### ISSUE TITLE
Bild-Upload ins Wiki funktioniert nicht

### ISSUE THREAD

**Issue by abrock** [raumzeitlabor/rzl-tuwat#141]
Bilder ins Wiki zu laden funktioniert weder direkt beim Bearbeiten einer Seite noch über Werkzeuge->Datei hochladen.
Bei letzterem gibt es folgende Fehlermeldung:

> Das Verzeichnis „mwstore://local-backend/local-public/6/68“ konnte nicht angelegt werden.

**Comment by lutoma** [comment]
Thumbnails scheinen auch nicht mehr generiert zu werden. Existierende funktionieren zwar weiter, wenn sich aber die Größe geändert hat kommt auch nur ein Fehler:

![2017-12-21-08 41 18](https://user-images.githubusercontent.com/179393/34245571-bcf95cac-e62a-11e7-9495-20762f1cad19.png)
