### ISSUE TITLE
Moemoe hat eine Kiste im Getränkelager - anschreiben

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#142]
- Jemand müsste ihn anschreiben was mit der Kiste passieren soll
- Is er nochmitglied?

**Comment by tabascoeye** [comment]
moemoe war noch nie RZL Mitglied

**Comment by s1lvester** [comment]
Mail auf die Liste am 21.08.

Frist für Lost&Found für 09.09.17.

**Comment by s1lvester** [comment]
Pending. Kontakt zu moemoe hergestellt.

Need: Photo der Kiste.

**Comment by Bfritz0815** [comment]
Hab ihm ne Mail geschrieben, wo sie steht (Getränkelager 2.Ebene, Blechregal). Photo kann ich erst nächsten Sonntag machen, diesen bin ich nicht im RZL.

**Comment by Ranlvor** [comment]
![2017-08-26 19 25 33](https://user-images.githubusercontent.com/230440/29743762-3bedaeee-8a98-11e7-8f42-d99f28d9a440.jpg)
![2017-08-26 19 25 45](https://user-images.githubusercontent.com/230440/29743764-3bf5c3ae-8a98-11e7-84bb-1bf6ec52cf98.jpg)
![2017-08-26 19 26 19](https://user-images.githubusercontent.com/230440/29743763-3bf35600-8a98-11e7-9020-2d7580c0ffc5.jpg)

Photo: Done.

**Comment by s1lvester** [comment]
Mail mit Photo an moemoe ist raus.

**Comment by maugsburger** [comment]
Interessant. Die Kiste gibt es auch schon in #43 

Wie @tabascoeye richtig bemerkt hat war ich nie Mitglied, an die Handschuhe kann ich mich auch nicht erinnern (was ja nichts heißen muss, am Ende hat die jemand da aus Gründen reingelegt). 

Handschrift könnte meine sein, sicher bin ich mir aber nicht.

Daher die Frage, wie am besten verfahren. Ich werde vermutlich den nächsten Monat nicht nach Mannheim kommen können. Da ich aber auch nichts vermisse, gehe ich davon aus dass der Inhalt problemlos auf Müll/Laboranten/Labor je nach Interesse verteilt werden kann.

**Comment by uwap** [comment]
Steht im Hauptraum. Ist jetzt Give Away.
