### ISSUE TITLE
Probot hat eine Kiste im Getränkelager

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#143]
Eine Kiste im Getränkelager 2.Ebene im Metallregal und einen Pappkoffer vor dem Hochregal

- Ist er noch Mitglied?
- Bitte anschreiben, was mit der Kiste und dem Koffer passieren soll

**Comment by tabascoeye** [comment]
Probot ist noch Mitglied

**Comment by Bfritz0815** [comment]
Ok. Closing this as resolved. Kann sein, dass der Koffer zur Kiste wandert wenn ich Zeit hab.
