### ISSUE TITLE
Getränkelager entrümpeln

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#145]
Getränkelager entrümpeln bevor in Hauptraum weiter gebaut werden kann.

- [ ] Regalteile weg
- [ ] Metall-Regale in 2. Ebene sichern
- [ ] alte Farben und Maler Equipment. Entsorgen? Brauchbares UND nötiges auf 2. Ebene
- [ ] Kacheln vom Laborbereich. Frage: entsorgen?
- [ ] Säcke mit Gips und Zement. Mal ehrlich Leute: wer braucht die noch irgendwann die nächsten 24 Monate?
- [ ] Alte Poliermaschine: Gibts dafür überhaupt noch Ersatzteile für die Bürsten? Hat noch jemand vor, die zu nutzen? Wer macht die nutzbar oder kauft Ersatz falls das nicht geht? (Owner: @Inte siehe unten) Frage: Brauchen wir die noch?
- [x] Große Kiste Ikea mit Reserve Gläsern. Frage: brauchen wir so viele?
  - [x] Deckel der Kiste finden
  - [x] RZL Zeug stapeln
- [x] Alter Zigarettenautomat. Frage: verkaufen / entsorgen? (startet aktuell ein Projekt zu #149  )

**Comment by Bfritz0815** [comment]
Anmeerkungen von Steeph aus dem alten Ticket: #51 


Zu "Alte regalplatten auf der 2. Ebene wegschmeissen? Warum sollten wir die noch behalten?":
An der hinteren Wand im Getränkelager könnten wir ein Regal aufbauen und dort viele der Sachen unterbringen, die jetzt im Weg rumliegen. Wie Platten sehen ja noch gut aus und ziemlich stabil.
 @steeph-k
     Owner
steeph-k commented on May 25, 2016
Zu "Große Kiste Ikea mit Reserve Gläsern. Frage: brauchen wir so viele?":
Wenn ich das richtig gesehen habe, dann sind auch bei Veranstaltungen im RZL die Gläser im Schrank mehr als genug. Übrige könnten wir also verkaufen oder spenden.

**Comment by steeph-k** [comment]
Eine Regalwand wurde seit dem auf der oberen Ebene aufgebaut. Die Querstreben liegen aber woanders im Lager und müssten noch befestigt werden.

Den Zigarettenautomat möchte ich nicht entsorgt sehen. Klar, er steht seit Jahren rum ohne dass jemand weiter etwas dran gemacht hat. Aber irgendwann wollte ich das eigentlich schon mal noch angehen. Schließlich ist er ja eigentlich in Ordnung und funktioniert nur mit den Spielkartenboxen nicht so wie gewünscht, wenn ich das richtig mitbekommen habe. Evtl. würde es schon reichen, einfache Pappschachteln im richtigen Format für die Bausätze zu falten, um ihn in Betrieb nehmen zu können.

**Comment by Bfritz0815** [comment]
@steeph-k  sorry, ich hatte deine Comments re-posted ohne sie zu checken. Die Regalwand hat sich schon gerergelt. 

Zum Zigarettenautomat hab ich jetzt ein Ticket erstellt: #149

**Comment by tabascoeye** [comment]
Die Poliermaschine gehört iirc @Inte

**Comment by uwap** [comment]
Die Kiste mit den ganzen Ikea Gläsern müsste alles MRMCD Zeug sein. Bitte auf keinen Fall wegräumen. Wir brauchen die unbedingt und haben da eher zu wenige als zu viele.

**Comment by Bfritz0815** [comment]
@uwap OK. Dies steht da schon seit Ewigkeiten ganz hinten unter allem Möglichem Zeug. Wollt ihr da nicht wenigstens nen Deckel drauf haben damit das nicht so versifft? Ausserdem wärs evtl ganz praktisch mal für das ganze MRMCD-Equipment gescheite Boxen zu haben, in denen die Dinge sicher gelagert sind und sich stapeln lassen. 
Aktuell steht das Zeug eben gefühlt-überall rum und wird daher auch ständig irgendwo umgestellt usw. Das ist sicher auch für die Sachen selbst nicht gut

**Comment by Bfritz0815** [comment]
@uwap Ist die Kiste eigentlich gelabelt?
Afaik wusste bisher kaum jemand, dass die Gläser MRMCD-Stuff sind: 
Ich hab noch im Kopf, dass es schon vor ein paar Monaten ne Initiative gab, die Gläser zu verschenken.

**Comment by uwap** [comment]
@Bfritz0815 Ich bin dieses Jahr auch erst neu bei der MRMCD. Ich finde die Lagersituation aber auch suboptimal, auch aus MRMCD Sicht. Ich würde es für eine gute Lösung halten ein Regal im Getränkelager für die MRMCD zu reservieren. Aber hab bitte verständnis, dass wir gerade jetzt, so kurz vor der MRMCD, andere Dinge im Kopf haben als die Lagerung im RZL zu überdenken. Wir können das aber gerne nach der MRMCD angehen, bzw bin ich auch stark dafür.

Wir haben trotzdem mal altes MRMCD Zeug entrümpelt und weggeworfen.

Was würdest du davon halten, wenn wir das Regal im Getränkelager direkt vorne am Eingang für MRMCD Zeug reservieren?

**Comment by Don42** [comment]
Direkt vorne macht für Dinge die man 1-2 mal im Jahr braucht vermutlich eher weniger Sinn. Was genau der Plan für das Getränkelager ist habe ich nicht mitbekommen, aber da findet man weiter hin doch sicher eine Stelle.

**Comment by Bfritz0815** [comment]
Heute haben wir den gesamten 3. Bereich der 2. Ebene zum MRMCD-Bereich umgebaut: Alles rechts vom Absperrband ist MRMCD. Dort kann MRMCD tun und lassen was sie wollen. Wenn ich woanders MRMCD-Zeug rumkugelnd finde, pack ich das kommentarlos in diesen MRMCD-Bereich. 

Auch so hat sich viel bewegt:

- Event- und Installationmaterial ist teils auf die 2.Ebene gewandert. 
- Jede Menge Dinge wurden Lost-And-Found
- Eine Menge sinnloserweise langzeitgelagerter Dinge wurden in den Hauptraum geschafft und werden den Ownern per Mail mitgeteilt

Noch offen:
- [ ] Ausmisten des antiken Baumaterials auf der unteren Ebene
- [ ] Zigaretten-Automat

**Comment by uwap** [comment]
Die Frage ist, ob wir das Baumaterial noch für irgendwelche Umbau Aktionen brauchen? Den Zigarettenautomat wird über ein anderes Issue verwaltet. Close?

**Comment by Bfritz0815** [comment]
Close sounds good

Am 16.11.2017 15:49 schrieb "uwap" <notifications@github.com>:
