### ISSUE TITLE
Textillager entrümpeln

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#146]
Langfristiges Ziel: Komplettauflösung vorbereiten. 

In der Zwischenzeit:

- [X] mv textilienlager/textilien getränkelager
- [x]  Leerräumen (Schrott weg, alles Andere ins Getränkelager nachedem da Platz geschaffen wurde #145  )
- [x] Regale abbauen
- [x] Sperrmüll aus anderen Arbeiten einlagern

**Comment by s1lvester** [comment]
@slowpoketail: Es liegen ca. 200 Einmach/Einweck-Gläser im Getränkelager. Matelade. What to do?

**Comment by Kunsi** [comment]
Einweckgläser keinesfalls wegwerfen. Wenn nicht benötigt, an Interessierte (z. B. mich) abgeben oder irgendwie zu Geld machen.

**Comment by tabascoeye** [comment]
@slowpoketail: sind ide von eurer Biowaffengruppe? Könnt ihr die bitte abholen und/oder an Leute verteilen, damit wir das Lager leer bekommen?

**Comment by uwap** [comment]
@slowpoketail Das Zeug liegt immer noch dort. Bitte kümmer dich drum.

**Comment by uwap** [comment]
Wir haben die Textilien aus dem Textilienlager ins Getränkelager umgeräumt.

**Comment by slowpoketail** [comment]
Ich kümmer mich da die Woche drum.

**Comment by uwap** [comment]
Moved to Getränkelager. Close
