### ISSUE TITLE
tardis umsetzen

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#147]

**Comment by uwap** [comment]
Ich bin dafür das Hochregallager komplett abzubauen und ein komplett neues, kleineres, dafür tieferes zu bauen.

**Comment by Don42** [comment]
Warum sollten wir den Raum in der Höhe aufgeben und ein kleineres bauen?
Und für was brauchen wir ein tieferes Regal? Was haben wir den was in das aktuell nicht passt?

**Comment by Ranlvor** [comment]
Wenn ich das richtig verstanden habe war die Idee:
- Hochregallager weg
- Tardis an die Wand
- Kleines Hochregallager auf die Tardis

**Comment by steeph-k** [comment]
Es gibt ja auch die Idee, den Olymp bis zur TARDIS zu erweitern. Wenn das Hochregal, so wie es jetzt ist, nicht fortbesteht, könnte der Olymp auch bis zur Wand erweitert werden. Das Regal wäre dann vom Olymp aus erreichbar. Hätte Vor- und Nachteile für das Regal + mehr Bodenfläche.

**Comment by uwap** [comment]
Idee war gerade, dass wir den Anbau wegnehmen und halb an die Seite klatschen, den Kühlschrank dann zum Eingang hin gedreht neben die Tardis packen und da wo jetzt das Propaganda Regal ist die Snackbar hin. Das Propagandaregal dann in die Ecke von der Olymptreppe. Hat halt den Nachteil, dass man den Weg vom Eingang deutlich blockiert. Hat den Vorteil, dass die Kasse da bleiben kann, wo sie gerade ist und wir Buffet(/theke) und Snacks/Getränke zusammen haben.

Meinungen? (cc @Bfritz0815)

**Comment by Don42** [comment]
Würde nicht sagen das es deutlich blockiert. Bei geschlossener Tür steht der Kühlschrank dann nicht weiter im Eingangsbereich als das Propaganda Regal jetzt.

**Comment by Bfritz0815** [comment]
Naja, dann wäre der kiosk-stau im Eingang. So wies is, ist er an der
breitesten Stelle und daher am wenigsten hinderlich.  Ausserdem sammeln wir
müll am Eingangsbereich. Willst du die snacks neben dem Müll haben?

Der Vorteil der Kasse relativiert sich schnell wieder: Da im Küchenbereich
nur noch zu events gezahlt wird wäre es da sogar vorteilhaft, eine
temporäre mobile spendenbox hinzustellen.
Eine weitere Kasse in Armreichweite zum Tablet wäre eh nötig. Da könnte
dann die geste Kasse sein.

Vielleicht ist der Winkel unter der olympischen treppe eh der sinnvollste
ort fürs Propaganda Regal. (Oder irgendwo anders. So wichtig is das
Propaganda Regal auch nicht, dass es nen Premium Standort braucht)

Frage:
Worin besteht der Vorteil wenn snackbar (zu bezahlende snacks für member u
gäste) nahe an einem büffet (kostenlos/gg-freiwillige-spende) Essen steht?
Die 2 verschiedenen preismodelle können aif events mit vielen Gästen zu
Missverständnissen führen.

Am buffet wird:
- Sachen zubereitet
- buffet angeboten

Keins von beiden hat Bezug zur snackbar.



Am 27.08.2017 18:40 schrieb "uwap" <notifications@github.com>:

Idee war gerade, dass wir den Anbau wegnehmen und halb an die Seite
klatschen, den Kühlschrank dann zum Eingang hin gedreht neben die Tardis
packen und da wo jetzt das Propaganda Regal ist die Snackbar hin. Das
Propagandaregal dann in die Ecke von der Olymptreppe. Hat halt den
Nachteil, dass man den Weg vom Eingang deutlich blockiert. Hat den Vorteil,
dass die Kasse da bleiben kann, wo sie gerade ist und wir Buffet(/theke)
und Snacks/Getränke zusammen haben.

Meinungen? (cc @Bfritz0815 <https://github.com/bfritz0815>)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/raumzeitlabor/rzl-tuwat/issues/147#issuecomment-325209648>,
or mute the thread

**Comment by Don42** [comment]
Die "breiteste" Stelle ist nur so breit weil da auch der meiste Verkehr und Vorträge sind.
Wie viel Verkehr ist wirklich im Eingangsbereich? Und wie lange sollte die Kühlschranktür aufstehen?

Der Vorteil die Snackbar um die Ecke zu legen ist, das sie weniger mit dem Vortrags/Projektionsbereich kollidiert und die Beleuchtung nicht auf in den ganzen Raum bzw die Projektionsfläche strahlt.

Wie oft haben wir wirklich ein Büffet? Sonderlich oft kommt das ja auch nicht vor und bisher gab es in der Küche auch nicht wirklich Probleme. Eine explizite Spendenkasse dazuzustellen ist ja kein Problem.

**Comment by Bfritz0815** [comment]
Die Breiten-thematik beizieht sich nicht auf ne Tür, die ab und zu kurz mal
offen steht, sondern auf platz um an Leuten vorbeizukommen wenn diese sich
an der snackbar begegnen und unterhalten.
 Das Problem hatten wir früher neben dem Konferrenztisch.
Heute ist es Geschichte. Bin eher dagegen, das nochmal an anderer Stelle
anfallen zu lassen.

Meine Ansicht in Kurzform:
Es gibt bereiche, die sind Plätze und welche, die sind Durchgänge.
Durchgänge müssen frei bleiben, Plätze können als Treffpunkt dienen
Sinnvoll wäre also, Gegenstände welche zu Treffpunkten werden an Plätze und
nicht an Durchgänge zu stellen.

Alles Andere sind Auslegungen und persönliche Ansichten, die man besser vor
ort besprechen als texten kann. (Bei dem Bezug zur Beamerwand hab u.a. ich
nämlich noch andere Ansichten)

Am 27.08.2017 22:03 schrieb "Marco Kaulea" <notifications@github.com>:

**Comment by Don42** [comment]
Ok, dann machen wir das in zwei Wochen.

**Comment by uwap** [comment]
Ich kann @Bfritz0815 argumentation auch nur Unterstützen.

**Comment by abrock** [comment]
Die Tardis ist nicht als Unterbau für ein Regal geeignet, darauf sollten höchstens leichte sperrige Dinge gelagert werden.

**Comment by uwap** [comment]
Zwischenfrage: Können wir uns auf ein "not gonna happen" einigen?

**Comment by Don42** [comment]
Klingt gut.
