### ISSUE TITLE
Küche entrümpeln

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#148]
Infolge #118 gabs heute (20. 8.2017) ein Meeting, in dem wir einige Aktionen vorgesehen haben. 
U.A. auch wie die Küche umgebaut wird. 

- Neuer Kühlschrank und Gefrierschrank
- neue Abzugshaube und deren Schrank
- Herdplatte als einzelne Einheit ohne Ofen
- Oberschränke statt dem Gewürzbrett
- Bestehende Theke durch Neue ersetzen (mit Füßen für leichteres Fegen)

Konkrete TODOs:

- [x] Im Ikea-Simulator schauen Leute (Brainfreeze und DaFo) nach, wieviel es kostet
- [ ] Drucker und Blechschrank kommen woanders hin
- [x] Tardis-Umbau

**Comment by uwap** [comment]
Wir hatten heute das zweite Küchenplanungsmeeting. Wir haben darauf geachtet, keine unputzbaren Ecken zu haben. Es wird zwei Kühlschränke geben, davon ein reiner Gefrierschrank. Das ganze kostet ~3.000€ ohne Elektrogeräte. Wir haben dafür mehr Schubladen, statt Schränke und viele Hängeschränke.

**Comment by tabascoeye** [comment]
gibts screenshots aus dem Küchenplaner?

**Comment by uwap** [comment]
![kuche](https://user-images.githubusercontent.com/2212422/30520342-12b39ee2-9bac-11e7-98df-1e49d54269ee.png)

**Comment by uwap** [comment]
![kuche2](https://user-images.githubusercontent.com/2212422/30520467-e53e8d84-9bae-11e7-9e92-ddcf989edb74.jpg)
![kuche3](https://user-images.githubusercontent.com/2212422/30520468-e53ebac0-9bae-11e7-8e9a-3cb0cf56e32d.jpg)

**Comment by uwap** [comment]
@tabascoeye Bitteschön.

Erklärung: Die Arbeitsplatte über der Waschmaschine und der Spülmaschine kann der Küchenplaner leider nicht darstellen. Das, zwischen Herd und Ofen ist ein Gefrierschrank. Über der Spüle hängt so ein Schrank mit Abtropffläche.

**Comment by tabascoeye** [comment]
Das heißt, die "theke" vorne entfällt komplett? Ich dachte wir wollten eher noch die Theke zum "L" vervollständigen und nur noch einen "Eingang" in die Küche machen?

**Comment by Don42** [comment]
Nur ein Eingang ist eher unpraktisch. Entweder bei Vorratskäufen oder beim Anrichten am Tisch müsste man sonst ständig Umwege laufen. Außerdem war die Theke an der Snackbar bisher nicht wirklich als Theke benutzbar.

**Comment by tabascoeye** [comment]
Das heißt neben der Herdplatte hat man nur eine Schrankbreite an Küchenplatte als Arbeitsfläche?
Oder macht die Platte wieder ein L wie bisher? Dann wäre der Zugang zur Waschmaschine erschwert...

Was soll der ganze Spaß denn kosten?

**Comment by uwap** [comment]
@tabascoeye 

> Das ganze kostet ~3.000€ ohne Elektrogeräte

Neben dem Herd haben wir jetzt auch nicht wirklich Arbeitsfläche und sie wird imho da auch nicht gebraucht. Die Lücke ist bewusst gewollt, weil es dadurch leichter zu reinigen ist.

**Comment by Kunsi** [comment]
Du willst neben dem Herd eigentlich eine Arbeitsfläche haben, einfach um mal nen Kochlöffel oder sowas abzulegen. Warum nicht die Waschmaschine neben den Herd stellen, und dann da in der Ecke ein totes Eck haben?

**Comment by uwap** [comment]
@Kunsi Für solche kleinen Dinge ist da ja genügend Arbeitsfläche. Außerdem ist direkt unter dem Herd auch die entsprechende Schublade dafür. Ein totes Eck wollen wir explizit vermeiden, weil ugh bah widerlich.

**Comment by steeph-k** [comment]
On 03.10.2017 21:37, uwap wrote:
>
> Ein totes Eck wollen wir explizit vermeiden, weil ugh bah widerlich.
>
Ich hab' bei meiner Küche zwar auch darauf geachtet, dass die Ecken 
nicht ungenutzt bleiben. Aber wenn man stattdessen genau so viel Platz 
neben dem Eck frei lässt, bringt das ja auch nichts. Ich bezweifle, dass 
rechts neben dem Herd genug Plat ist, um was abzulegen oder gar 
abzustellen. Wenn man die Waschmaschine neben den Herd stellt und das 
Eck abschließt, dann fällt auch der Grund für die jetzige Lücke weg. Wo 
kein Dreck rein kommt muss auch nicht einfach zu reinigen sein. Der 
aktuelle Plan sieht für mich an der Stelle nach Platzverschwendung aus. 
Die Arbeitsfläche könnte man gut brauchen, gerade an der Stelle.

**Comment by uwap** [comment]
@steeph-k @Kunsi Auf dem Küchenplanungsmeeting wurden viele Gründe für das jetzige Design vorgetragen. Auch eine Ecke oberhalb der Arbeitsfläche lässt sich schlechter putzen und führt dazu, dass es leichter zugemüllt wird.

**Comment by steeph-k** [comment]
Soll mich auch nicht stören. Ich nutze die Küche eh kaum. Kommt mit nur 
unpraktisch vor. Aber wenn die an der Planung Interessierten das so 
besser finden: gut.

**Comment by uwap** [comment]
Wollen wir den Vorstandsschrank eventuell unter die Treppe *hinter* das neue propagandaregal setzen? Oder gibt es andere ideen? @tabascoeye @Don42 

Kann der Drucker dann eigentlich weg?

**Comment by Bfritz0815** [comment]
Die alte Theke ist nun im Sperrmüll-Lager. 
Der alte Tisch wurde gegen modularere Tische aus dem Getränkelager ausgetauscht. 
Die Leergutkisten stehen nun neben dem Getränke-Kühlschrank.

**Comment by uwap** [comment]
Um noch mal auf die Kritik von @steeph-k und @Kunsi zurück zu kommen:

Wir könnten auch den Herd und alles Links davon weiter nach links wandern lassen, dann rechts neben dem Herd eine Arbeitsplatte hin. Der Kühlschrank könnte neben den Vorratsschrank wandern.

Kritik, Anregungen, Gegenvorschläge?

**Comment by uwap** [comment]
Sorry. Mir ist gerade aufgefallen, dass es ja in dem Sinne den Vorratsschrank gar nicht mehr gibt. An der Stelle wo jetzt der Voratsschrank steht, würde ich ungerne den Kühlschrank hinsetzen, weil das dann ständig den Gang blockiert. Hat Jemand andere Ideen?

**Comment by uwap** [comment]
Wenn ihr an der Küchenplanung weiter interessiert seid, tragt euch bitte in das Dudle für das nächste Küchenplanungsmeeting ein. Ziel ist es, noch mal die offenen Baustellen zusammen zu fassen, einen Zeitplan zu errichten und den Transport von der neuen Küche sowie dem Sperrmüll zu organisieren und alle weiteren Fragen zu klären. https://dudle.inf.tu-dresden.de/rzl-kitchen-02-2018/

cc @Bfritz0815

**Comment by uwap** [comment]
Leider funktioniert der Küchenplanungslink nicht ordentlich bei uns. Daher müssen wir noch die folgenden Möbel raussuchen und bei IKEA bestellen:

7x Hängeschrank
1x Hängeschrank mit Abtropfding
3x 3-Schubladenunterschrank
1x 4-Schubladenunterschrank
3x 2-Schubladenunterschrank
1x Unterschrank mit Tür
1x Großer Ofen-Mikrowellenschrank

**Comment by tabascoeye** [comment]
Ich habe das nochmal komplett neu in diesem kack IKEA Planer gebaut.
Inklusive korrekten Maßen und einer Dastellung von Balken, Treppe und Tür:

<img width="1078" alt="screen shot 2018-03-24 at 18 01 51" src="https://user-images.githubusercontent.com/111893/37866632-ad91f86c-2f8d-11e8-8556-9559fdc62815.png">
<img width="1073" alt="screen shot 2018-03-24 at 18 02 34" src="https://user-images.githubusercontent.com/111893/37866633-adad0f6c-2f8d-11e8-84f5-f5146d68acd3.png">
<img width="1072" alt="screen shot 2018-03-24 at 18 02 48" src="https://user-images.githubusercontent.com/111893/37866635-adc8d652-2f8d-11e8-967a-3b2de1632290.png">

Da sind jetzt keine Arbeitsplatten drauf, weil wir die nicht bei IKEA sondern bei Hornbach kaufen wollen.
Mehr dazu in einer Mail an die ML

**Comment by Kunsi** [comment]
Wenn es keine Einwände gibt, würde ich mich um die … äh … Entsorgung von Mikrowelle und Herd/Ofen kümmern.

**Comment by tabascoeye** [comment]
Sowas bitte wie immer auf dem Hauptkommunikationsmedium (ML) klären.
Da stellen sich zB die Fragen: Wer ist Eigentümer?
Die Mikrowelle zB gehört glaube ich DaFo…

==> Mail auf die Liste bevor Sachen aus dem RZL rausgetragen werden!

**Comment by Bfritz0815** [comment]
ich würd gerne für die Dauer der Umbauten eine kleine improv-Küche unter der Tafel haben wollen:

- 2 Tische
- 1 Mikrowelle
- wasserdichte Kunststoff-Box f schmutziges Geschirr/Besteck
- Boxen mit sauberem Geschirr/Besteck

Daher bitte hold-off bezüglich Mikrowelle entsorgen, solange noch keine neue da ist. Thanks

**Comment by Kunsi** [comment]
re Eigentümer: Klar, der Eigentümer hat natürlich das Vorrecht. Ich weiss nur, dass die Geräte ausgetauscht werden sollen - und bevor sie entsorgt werden, würde ich sie gerne einer Zweitverwendung zuführen.

**Comment by n1trux** [comment]
Pyrolyse-Backofen heißt, dass gut belüftet werden muss (Kohlenmonoxid!!!).

Wie soll denn die Belüftung generell gelöst werden? Die Dämpfe vom Kochen gelangen derzeit ja noch in jede Ecke des RZL…

Plädiere daher für eine gute Belüftung und einen CO-Melder. Wird der Umbau nur heute stattfinden? Bin leider krank, würde aber gerne wann anders helfen…

**Comment by heylix** [comment]
Pyrolysebackofen heißt, es entsteht giftiges Kohlenmonoxid. Ich plädiere für einen CO-Melder.

Soll an der Belüftung zukünftig etwas geändert werden? Der ganze Raum riecht nach Essen, wenn gekocht wird.

**Comment by Wifi-cable** [comment]
Sieht gut aus :) ich komm gleich zum helfen.

**Comment by uwap** [comment]
Die neue Küche steht. Der Tardisumbau scheint nicht wirklich weiter relevant. Ich mache mal ein neues Issue auf, bezüglich des Vorstandsdruckers. Ansonsten ist alles erledigt.
