### ISSUE TITLE
Zigarettenautomat aufpimpen

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#149]
Auf Wunsch  von @uwap und @steeph-k gibts nun dieses Ticket. https://github.com/raumzeitlabor/rzl-tuwat/issues/145#issuecomment-323597876

**Comment by steeph-k** [comment]
Todo:
- [ ] Funktion prüfen
- [ ] ggf. reparieren
- [ ] Zuverlässigkeit mit Spielkartenboxen testen (evtl. mit Papier zw. Boxen)
- [ ] ggf. neue Boxen entwickeln und herstellen, mit denen es ordentlich funktioniert
- [ ] Standort überlegen und besprechen
- [ ] Befüllen, verschönern, Schild anbringen, Inbetriebnahme ankündigen

**Comment by uwap** [comment]
@steeph-k Passiert da noch was? Ich wäre inzwischen eher dafür den Zigarettenautomaten zu entsorgen.

**Comment by Kunsi** [comment]
Nicht wegwerfen. Lieber an interessierte Menschies (z. B. Mich) abgeben.

**Comment by uwap** [comment]
@Kunsi @steeph-k Dann klärt das unter euch. Ich wäre allerdings für eine Zeitnahe Lösung (Also so bis Ende des Jahres)

**Comment by tabascoeye** [comment]
“unter euch“ ist nicht bei rzl Eigentum.
Mailingliste ist unser Medium für sowas.
Github bekommen nicht alle mit.
Also Dinge an einzelne auf github veräußern geht nicht.

Wenn er wirklich weg soll, dann Mail an die Liste mit “wenn kein Veto kommt er in 4 Wochen weg“ analog zur Lost&Found

**Comment by steeph-k** [comment]
On 03.10.2017 16:25, uwap wrote:
>
> Richtig. Also zu klären ist:
>
>   * Kann sich @steeph-k <https://github.com/steeph-k> zeitnah um die
>     Reperatur kümmern?
>
Damit ist eher nicht zu rechnen. Ich wusste nicht mal, dass er defekt ist.

**Comment by tabascoeye** [comment]
imho sind die Spielkartenhüllen unserer Bausätze steckengeblieben und sowas (zu rutschig?). Und außer mit dem komischen Handgerät wurde er iirc auch nie Betrieben.
Müsste also erstmal auf eine uC Steuerung umgebaut werden und sowas.

**Comment by Bfritz0815** [comment]
Aktueller Stand:
Ich hab die Dinger in Absprache mit @steeph-k mit nem neuen Label beklebt: Owner/public mit Steeph und @Kunsi als owner. 

@uwap  Da die Beiden ja jeweils interessiert scheinen, was damit zu machen, können wir das ja auch als Projekt auffassen und dort lassen. 

Zur Erinnerung: Es stand dort mit Label "Owner RZL" rum, niemand hat was damit gemacht, letzte Info unter der Allgemeinheit war, es sei kaputt. Jetzt ist das imho hinreichend geklärt, dass wir das als projekt dort lassen können.

**Comment by abrock** [comment]
Ist der Automat noch im RZL? Wenn nicht würde ich das Issue schließen.

**Comment by Kunsi** [comment]
Soweit mir bekannt, steht der noch rum. Wenn er stört, kann ich ihn gerne abholen, ansonsten würd ich das eher aufs Spätjahr verschieben.

**Comment by tabascoeye** [comment]
steht noch im Getränkelager

**Comment by steeph-k** [comment]
Vor ein paar Wochen wollte ich mich endlich mal daran machen, konnte den Schlüssel aber nicht mehr finden. Da ich mit dem Abarbeiten meiner Punkte von oben bisher nicht wirklich begonnen habe kann ich wohl nicht mehr Einspruch erheben, wenn ihn jemand entsorgen möchte.

Trotzdem: Schönes Teil eigentlich.

**Comment by steeph-k** [comment]
Da sich spontan eine Gelegenheit ergab und die wenigen, die gegen eine Entsorgung des Gerätes waren in zwei Jahren nichts damit getan haben, ist es jetzt entsorgt.
