### ISSUE TITLE
Mailvorlagen

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#156]
Da es in letzter Zeit häufiger Ärger aufgrund von doof formulierten Mails oder falsch verstandenen Mails gab, würde ich vorschlagen neutral formulierte Mailvorlagen zu entwerfen und ins Wiki zu packen. Vorallem für so sachen wie "Du hast Zeug rumstehen. Brauchst du das noch?", "Du hast Zeug im Weg stehen, kannst du das wegstellen?", "Wir haben hier ungelabelte Dinge. Gehören die wem?", etc.

Meinungen?

**Comment by tabascoeye** [comment]
technische Lösung für Soziales Problem. wird nicht funktionieren imho

**Comment by uwap** [comment]
Es gibt jetzt https://wiki.raumzeitlabor.de/wiki/Mailvorlagen. Es sollte mal Jemand drüber schauen und ergänzen / korrigieren.

**Comment by uwap** [comment]
Wir können ja auch einfach miteinander reden und dadurch Konflikte lösen. Wäre eigentlich viel schlauer. Oder halt die ML nicht mehr nutzen, wie es hier genügend Leute tun. Close
