### ISSUE TITLE
Baustelle an der Boveristr auf die Anfahrtsbeschreibung der Webseite packen

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#157]

**Comment by tabascoeye** [comment]
Hmm die Wegbeschreibung bezieht sich ja sehr auf die ÖPNV Anfahrt und geht von der Haltestelle aus.
Vielleicht nur ein Hinweis auf die Baustelle?

**Comment by tabascoeye** [comment]
Handled in https://github.com/raumzeitlabor/rzl-homepage/pull/310
