### ISSUE TITLE
Dinge die nun in Lost gekommen sind

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#158]
Hier is doku dafür um Mail-größen nciht auszudehnen. 

Läuft anfang dezember in giveaway. 

Vieles davon is in der Lot and FoundKiste. Manches ist aus Platzmangel im Workshopraum abgestellt.

**Comment by Bfritz0815** [comment]
![img_20171017_191009](https://user-images.githubusercontent.com/776715/31679309-f66f8746-b370-11e7-820d-26fad11dfd7b.jpg)

Diverse Klamotten und Schlafsäcke.

**Comment by Bfritz0815** [comment]
Lego-zeug in einer Tasche

![img_20171017_190501](https://user-images.githubusercontent.com/776715/31679367-2b7689f8-b371-11e7-9f78-d0e5b8b297c9.jpg)

**Comment by Bfritz0815** [comment]
ungelabelte pelzige DInge: 

![img_20171017_190846](https://user-images.githubusercontent.com/776715/31679619-f4a58b12-b371-11e7-8d81-515bd7e8777f.jpg)

**Comment by Bfritz0815** [comment]
Kisten mit Lego-Artigem. @slowpoketail ist das was von dir oder hattest du deins schon mitgenommen?
Liegt im Workshopraum.

![img_20171017_190229](https://user-images.githubusercontent.com/776715/31679717-45a7578e-b372-11e7-970e-a6bf883938de.jpg)

**Comment by Bfritz0815** [comment]
![img_20171017_190434](https://user-images.githubusercontent.com/776715/31684791-2ee70ec2-b381-11e7-9579-120201525215.jpg)

"Automat" und 1-Dosen Kühlschrank
im Lost and found

**Comment by uwap** [comment]
Mag Jemand™ mails schreiben? (Ich habe ausgründen keine lust)

**Comment by tabascoeye** [comment]
Der "Automat" ist soweit ich weiß von "Kisl"

**Comment by Bfritz0815** [comment]
@tabascoeye magst du kisl anschreiben?

**Comment by Bfritz0815** [comment]
Die Inhalte sind nun ins Found gewandert. Nächsten Monat sind die Giveaway.

**Comment by uwap** [comment]
Hatte @steeph-k nicht auch noch Kontakt zu Kisl?

**Comment by steeph-k** [comment]
On 07.01.2018 17:18, uwap wrote:
>
> Hatte @steeph-k <https://github.com/steeph-k> nicht auch noch Kontakt 
> zu Kisl?
>
Mehr als ihm E-Mail schicken könnte ich jetzt auch nicht.

**Comment by Bfritz0815** [comment]
@steeph-k wäre nett, wenn du das tätest. (Am Besten mit link zu dieser issue)
Bitte scheib hier rein, wenn die Mail raus ist, damit nicht evtl noch x Andere rum-Mailen. 
Danke

**Comment by steeph-k** [comment]
On 07.01.2018 18:34, Bfritz0815 wrote:
>
> @steeph-k <https://github.com/steeph-k> wäre nett, wenn du das tätest. 
> (Am Besten mit link zu dieser issue)
>
Done.

> Bitte scheib hier rein, wenn die Mail raus ist, damit nicht evtl noch 
> x Andere rum-Mailen.
>
Done.

**Comment by steeph-k** [comment]
https://wiki.raumzeitlabor.de/wiki/Dudelkran

**Comment by Bfritz0815** [comment]
Danke @steeph-k 🙂

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by abrock** [comment]
Zu Dingen die vor >1y im Lost waren brauchen wir denke ich kein Issue mehr.
