### ISSUE TITLE
Baustrahler

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#160]
Seriosly: Was wollen wir noch damit? 

Bitte lasse sich jemand was einfallen, den loszuwerden.

Derweil steht der im Workshopraum. 

![img_20171017_190724](https://user-images.githubusercontent.com/776715/31679753-6df0ffa6-b372-11e7-95c3-f78770eb28fe.jpg)

**Comment by abrock** [comment]
Gehört soweit ich weiß @Inte

**Comment by uwap** [comment]
Ich habe Inte per Mail angeschrieben.

**Comment by tabascoeye** [comment]
"seriously", seid ihr vielleicht etwas zu sehr im Wahn Dinge zu entsorgen?!
Das ist ein Werkzeug und Werkzeuge sollten wir nie wegschmeissen, wenn sie noch funktionieren.

Beispiel: Wenn wir im Raum was an der Verkabelung ändern wollen und deshalb kein Licht schalten können, aber noch einen Stromkreis haben, der nicht betroffen ist, kann man das Ding wunderbar als Arbeitslicht nutzen und nicht mit Taschenlampen o.ä. Mist arbeiten.

==> Wenn der euch im Weg ist braucht er einen sinnvollen, bekannten Lagerplatz

(WTF)

**Comment by uwap** [comment]
@tabascoeye Ja, wir sind so wahnsinnig die Lagerfläche im Getränkelager endlich wieder für Getränke nutzen zu wollen und außerdem Platz schaffen zu wollen, für die ganzen Sachen aus der Küche, die während des Küchenumbaus auch irgendwo hin müssen. Der Baustrahler wurde ewig nicht verwendet und eigentlich jeder hat schneller ein Handy zum Lichtmachen in der Hand.

**Comment by tabascoeye** [comment]
Ein Handy zum lichtmachen. Ernsthaft?

**Comment by uwap** [comment]
@tabascoeye Ich habe echt kein Bock so zu diskutieren. Wir wollen Platz im Lager schaffen für andere Umbauaktionen die schon längerfristig geplant werden. Und dann kommen wir mit so einem Baustrahler und werden von der einen Ecke angemault: "Wieso habt ihr den noch nicht weggeschmissen? Weg mit dem Müll" und von der anderen Ecke mit: "Seriously? Wieso wollt ihr das Entsorgen? Geht's noch?!"

Ich hab echt keinen bock mehr -.-

**Comment by tabascoeye** [comment]
Es funktioniert halt nicht mit der Brechstange. Und "Diskussion" funktioniert wohl nicht indem man etwas, mit dem man selbst nichts anzufangen weiß direkt mit "seriously?" und ähnlich sinnlosen Kommentaren zu entsorgen versucht.

Der Baustrahler gehört nicht dem RZL, er ist bei jeder größeren Umbauaktion im RZL im Einsatz gewesen und eine Handy LED ist kein Ersatz für 1000W Licht.

**Comment by uwap** [comment]
@tabascoeye Also ernsthaft:

1. Wir verbringen ein Wochenende im Getränkelager um Dinge umzuräumen, damit wir da Platz für den Küchenumbau schaffen
2. Die MRMCD kommt mit vieeel Kram wieder und der Platz ist weg
3. Leute vergreifen sich im ton, weil sie (zu recht) sauer sind
4. Wir verbringen abermals ein Wochenende im Getränkelager um Platz für Dinge zu schaffen
5. Leute (du) vergreifen sich im Ton.

Wir drehen uns hier im Kreis. Wenn der Baustrahler dir so wichtig ist, dann mach das RZL doch mit Baustrahler, ohne Küchenumbau und ohne neue Getränke. Zumindest habe ich keinen bock mehr auf die beiden Sachen. Ihr müsst euch alle mal an die eigene Nase fassen und nicht nur meckern, dass andere die falsche Wortwahl wählen oder sonst was.

**Comment by uwap** [comment]
@tabascoeye Danke für die zwei verschwendeten Wochenenden. Macht euren scheiß doch alleine. Ich hab keinen Bock mehr.

**Comment by tabascoeye** [comment]
Strohmann-Argument, Falsches Dilemma und Emotionale Erpressung.

Ich kann sehr gut unterscheiden zwischen der ganzen Arbeit, die ihr euch macht, die ich extrem gut finde und dem emotionalen Ballast, den ihr hier und auf der ML entladet. Das eine bringt uns weiter, das andere nicht.
Wenn ihr auf das eine ohne das andere keinen Bock habt, muss das RZL damit leben.

Der Trick ist: Ihr müsst es **nicht** jedem Recht machen. Ich kann noch so oft sagen, dass ich den Baustrahler sinnvoll finde. Wenn ihr @Inte Bescheid sagt, dass er den abholen soll, dann ist er halt weg.

**Comment by uwap** [comment]
@tabascoeye Ich kann durchaus unterscheiden zwischen den Sinnvollen Argumenten die wir hier kriegen und persönlichen angriffen, mit denen Argumente untermauert werden ("Seid ihr zu sehr im Wahn...?!", "$deinArgument, ernsthaft?!", ...). Natürlich müssen wir es nicht jedem Recht machen, ich muss mir aber auch nicht alles wortlos gefallen lassen.

Nach solchen Aktionen wie die im Getränkelager schreiben wir die Mails an die ML nur noch gemeinsam, damit sich niemand auf den Fuß getreten fühlt und kaum schaue ich heute morgen in meine Mails, beschwert sich ein @tabascoeye über unsere Aktion. Ja, weil du hast dich nämlich nicht über den Ton von @Bfritz0815 beschwert sondern uns allen an den Kopf geworfen, was uns denn einfallen würde zu hinterfragen ob wir das Teil noch brauchen oder nicht.

Und gerade das zu hinterfragen, dafür ist doch diese Plattform da. Nicht um Menschen anzumachen, was ihnen denn einfiele. Ich für meinen Teil sehe da keinen Fehler drin das hier offen zu diskutieren.

Und da sind wir eben bei dem was ich sagte. Das sollte hier keine emotionale Erpressung oder sonst was sein, aber ich bin es einfach Leid dauernd von allen Seiten angemacht zu werden ich würde Dinge falsch tun. Wenn es doch so falsch ist was ich tu, dann macht es doch besser. Ach, habt ihr keinen Bock drauf? Ich langsam nämlich auch nicht. Und das ist genau der Punkt der mich so ärgert.

Wenn wir das mit dem Baustrahler gar nicht erst zur Diskussion gestellt hätten, sondern direkt ihn entsorgt hätten, dann hätte es einen riesen Aufschrei gegeben (oder keiner hätte es bemerkt und es wäre ruhig geblieben). Stattdessen machen wir es auf den richtigen Weg und stellen es zur Diskussion, schreiben Besitzer an, blahblahblah... Nur, damit **ich** am Ende angemacht werde:
1. "Wieso habt ihr das Ding noch nicht weg geschmissen?! Das gehört dem RZL. Schmeißt den Scheiß endlich Weg"
2. "Was fällt euch eigentlich ein zu hinterfragen, ob wir das Teil behalten wollen? Seriously? Geht's noch?!"

Ich muss mich also dafür von mehreren Seiten anmachen lassen, dass wir den korrekten Weg wählen. Nächste mal also gleich ohne zu fragen entsorgen oder die ganze umräum Aktion komplett sein lassen?

**Comment by uwap** [comment]
@tabascoeye Also bitte, wenn du dich von dem Ton von Jemanden angekotzt fühlst, lass das nicht an anderen raus, die nichts dafür können.

Zurück zur sachlichen Ebene:

Wurde der Baustrahler in letzter Zeit benutzt? Hast du oder Jemand anderes etwas in nächster Zeit vor bei dem der Baustrahler benutzt wird?

**Comment by tabascoeye** [comment]
> Wenn wir das mit dem Baustrahler gar nicht erst zur Diskussion gestellt hätten, sondern direkt ihn entsorgt hätten, dann hätte es einen riesen Aufschrei gegeben

Natürlich werden sich Leute aufregen, wenn ihr deren Eigentum ungefragt wegwerft. Das liegt in der Natur der Sache.
Nebenbei: Wenn im e.V. Schäden entstehen, wie das Zerstören oder Verlust von persönlichem Eigentum, dann ist jemand "persönlich voll Haftbar". Und zwar der Vorstand.

> "Was fällt euch eigentlich ein zu hinterfragen, ob wir das Teil behalten wollen? Seriously? Geht's noch?!"

Mein "seriously" (mit den Anführungszeichen!) bezog sich auf den Eröffnungskommentar von @Bfritz0815. Ein "bitte lasse sich wer was einfallen, den loszuwerden" ist auch kein Nachfragen, ob wir das Ding noch brauchen oder nicht.

> Wurde der Baustrahler in letzter Zeit benutzt? 

Soweit ich weiß beim Ausbau des Getränkelagers zuletzt (zweite Ebene).

> Hast du oder Jemand anderes etwas in nächster Zeit vor bei dem der Baustrahler benutzt wird?

Ich nicht. Wenn aber zB auf dem olymp eine neue Phase verlegt werden soll, wäre es zB sinnvoll einiges an Phase abzuschalten und dann trotzdem Arbeitslicht zu haben.
Wir können aber auch akut einen neuen kaufen, wenn er gebraucht wird. Nur widerspricht das meinem Verständnis des Zwecks eines Hackerspaces: Infrastruktur vorhalten, um Dinge zu tun.

**Comment by uwap** [comment]
@tabascoeye Dann lass dir einen guten Platz dafür einfallen und hör auf Leute mit deinem "seriously" (mit ausrufezeichen!1!!!!) anzupissen oder überleg dir ob du jetzt @Bfritz0815 damit ansprechen wolltest oder mich. Ich jedenfalls habe keine Lust mehr auf die Diskussion hier und mir ist es egal ob der bleibt oder nicht, aber einigt euch.

**Comment by tabascoeye** [comment]
finale klarstellung: **ich** war von dem Satz
> Seriosly: Was wollen wir noch damit?

angepisst. Deshalb **zitierte** ich das. Ein einfaches "brauchen wir den noch?" hätte ich mit "ja" beantwortet.
Ein guter Platz wäre imho die Werkstatt.

**Comment by uwap** [comment]
@tabascoeye Und deshalb spiegelst du deine Aggressionen auf mich wieder und lässt sie auf mich aus oder was?

Der Baustrahler steht jetzt in der Werkstatt.

**Comment by tabascoeye** [comment]
Ich bitte um Entschulding, dass ich "Ihr" statt @Bfritz0815 in meinem ersten comment benutzt habe.
