### ISSUE TITLE
Drahtis Tassen

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#161]
Hi,
im Workshopraum ist jetzt eine Kiste abgestellt mit Tassen und Beschriftung Drahti. (tels durchgestrichen, teils nicht). Kann jemand Drahti dazu kontaktieren?

![img_20171017_190314](https://user-images.githubusercontent.com/776715/31679846-ab200822-b372-11e7-989f-2dff1245d978.jpg)

**Comment by uwap** [comment]
Die kamen auch schon auf die ML. Drahti schrieb mir dazu am 30.08.: "Am Samstag habe ich Zeit die Abzuholen"

**Comment by uwap** [comment]
Ich habe mit Drahti geredet. Seine Aussage war: "Entsorgt den Scheiß". Die Kiste wurde mit einem Giveaway label versehen.
