### ISSUE TITLE
Weltdameschaft

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#165]
Pläne laufen.

**Comment by Ranlvor** [comment]
Pssssst, doch nicht im öffentlivchen Tracker!

**Comment by uwap** [comment]
Todo:

- [ ] Plenum beschließt Weltherrschaft
- [ ] ???
- [ ] Profit

**Comment by Bfritz0815** [comment]
Einige Lichtwerfer wurden auf neue Versionen mit besserem Effizienz-rating ge-updated.

**Comment by uwap** [comment]
Es gibt jetzt Pläne von der neuen Bestuhlung

**Comment by uwap** [comment]
Wir sollten den Himmelsschnodder endlich mal an uns ran saugen.

**Comment by s1lvester** [comment]
Da im Titel des Issue keine gender-neutrale Sprache verwendet wurde, CLOSED.

**Comment by uwap** [comment]
Titel geändert zu Weltdameschafft.

**Comment by abrock** [comment]
Titel immer noch nicht gender-neutrel => CLOSED
