### ISSUE TITLE
Backup NAS sanieren

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#166]
Das NAS braucht ein Netzteil

**Comment by Bfritz0815** [comment]
@Ranlvor danke!

**Comment by Ranlvor** [comment]
Dinge, die gebackupt werden möchten
- [ ] lutoma.vm.rzl
- [ ] rami.vm.rzl
- [ ] datengrab.rzl
- [ ] partkeepr.rzl
- [ ] qrgo.vm.rzl
- [ ] db.rzl
- [ ] abrock.vm.rzl
- [ ] s1lvester.vm.rzl
- [ ] cashdesk.rzl
- [ ] unifi.vm.rzl
- [ ] kunterbunt.vm.rzl
- [ ] freeswitch.vm.rzl
- [ ] ranlvor.vm.rzl
- [ ] infra.rzl
- [ ] mate.rzl
- [ ] premium.rzl
- [ ] citizenfour.rzl
- [ ] git.raumzeitlabor.org
- [ ] chat.raumzeitlabor.org

Abhaken, wenn Backup abgeschlossen und Status OK.

**Comment by Ranlvor** [comment]
Alle Backups sind durch und werden automatisch täglich ausgeführt.
