### ISSUE TITLE
Ethikkommission

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#168]
Discussion thread for the implementation of an ethics comission for the raumzeitlabor

**Comment by uwap** [comment]
Ich fände ein CARE-Team wie es das Entropia hat voll sinnvoll

**Comment by Kunsi** [comment]
Unser CARE-Team ist unverkäuflich!

**Comment by uwap** [comment]
Close weil keine sinnvolle diskussion
