### ISSUE TITLE
Mehr Sonoffs

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#171]
Die Funksteckdosen schalten sehr unzuverlässig. Teilweise bleibt dadurch das Licht auch mal mehrere Tage an. Jemand der Ahnung hat sollte mal mehr Sonoffs besorgen und flashen.

**Comment by Ranlvor** [comment]
Für uns interessant wären:
- Sonoff Basic: 90~250V AC auf Schraubklemmen, für Geräte die permanent auf MQTT umgerüstet werden sollen
- Sonoff SV: 5~24V DC AC auf Schraubklemmen, für Geräte die permanent auf MQTT umgerüstet werden sollen
- Sonoff S20 Smart Socket: Schuko-Zwischenstecker

Jemand müsste mal™ entscheiden, wie viele wir von welcher Sorte wollen und einen Plenumsantrag machen.

**Comment by uwap** [comment]
Ich würde es sinnvoll finden wenn wir alle alten Funksteckdosen austauschen. Außerdem würde ich Anette von den Arbeitsplätze auf dem Olymp trennen wollen. Da wäre die Frage ob für die Arbeitsplätze nicht sowieso Dauerstrom sinnvoller wäre?

**Comment by tabascoeye** [comment]
Watt kosten die denn?
Ich würde mal mindestens 10 von den S20 nehmen, oder?
(ich dachte die alten schalten inzwischen zuverlässiger?)

**Comment by uwap** [comment]
@tabascoeye Ja, die alten Funksteckdosen schalten inzwischen zuverlässiger, hängen sich aber häufig auf. Dann lassen sie sich gar nicht mehr über MQTT steuern, bis man sie manuell schaltet.

**Comment by Ranlvor** [comment]
Günstigster S20 bei Amazon ist bei 11,09 € (+Versand?). Als ich 08.2017 welche gekauft habe war das noch bei 16,99 € (kostenloser Versand).

Und die alten Funkdosen schalten inzwischen, wenn sie sich nicht aufgehangen haben, zu >90% Zuverlässigkeit. Meine Stimme dazu: „ist mir egal, ob wir die tauschen oder behalten“.

**Comment by Nurtic-Vibe** [comment]
> Günstigster S20 bei Amazon ist bei 11,09 € (+Versand?).
Die werden leider auch aus China versandt, also selbes Problem wie bei Aliexpress

Aus EU versandt gibt es die S20 auf Amazon für 18,89€/Stück

**Comment by uwap** [comment]
@Ranlvor Würdest du welche aufs Plenum setzen?

**Comment by Ranlvor** [comment]
Erledigt. Siehe https://wiki.raumzeitlabor.de/wiki/Plenum#Sonoff_S20_Dosen

**Comment by uwap** [comment]
Wäre ja eigentlich cool, wenn die ganzen Sonoffs im IOT WLAN wären. Seid ihr da schon weiter gekommen? @Nurtic-Vibe

**Comment by Nurtic-Vibe** [comment]
* IOT WLAN müsste sich Leah mal anschauen, habe die Zugangsdaten nicht.
* Falls noch mehr WLAN Steckdosen gebraucht werden: https://www.obi.de/hausfunksteuerung/wifi-stecker-schuko/p/2291706 sind auch ESPs und laut https://github.com/arendst/Sonoff-Tasmota/issues/1988 auch von Tasmota unterstützt.

**Comment by Ranlvor** [comment]
Habe mich man an die Serielle des Cisco-Stacks gehangen, mich mit den RZL-Default-Zugangsdaten eingeloggt und meinen SSH-Key eingeworfen. Habe die VLAN-Konfiguration der APs gerade gezogen und mate mit in's VLAN gepackt und für infra eine statische IOT-IP konfiguriert. Der erste Sonoff ist auch schon mit Tasmota geflasht, auf das IOT-WLAN konfiguriert und in Betrieb.

**Comment by Ranlvor** [comment]
Habe jetzt alle Sonoffs, die wir noch gelagert waren, mit Tasmota geflasht, in's RZL-IOT eingebunden und in's OpenHab. Haben damit aktuell 7 unbelegte Sonoffs.
