### ISSUE TITLE
Familienduellgerät entfernen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#18]
Im Raum steht ein großes Gerät von jiska und muzy. Weiteres Vorgehen klären. 

![](http://i.imgur.com/u2fvWE4.jpg)

**Comment by else** [comment]
Wurde ins Lager zum restlichen Eventzeugs verfrachtet.

**Comment by silsha** [comment]
Mail von Jiska dazu:

> Das ist das Display für Gameshows. Es gehört dem shackspace und war bei
uns wegen den vorletzten MRMCDs und weil ein Transport zum 31C3 mal
angedacht war.
>
>Nicht wegwerfen sondern Transport Richtung shackspace!

**Comment by else** [comment]
Wer übernimmt den Transport?

**Comment by jiska2342** [comment]
12:02 #shackspace: < muzy> jiska: hm, ich will nur die grobhandtaster, die könnte man mir zusenden - was mit den bildschirmen passieren soll - keinen plan
12:03 #shackspace: < muzy> jiska: abholen kann ich das nicht, man könnte die übergabe am congress machen

**Comment by else** [comment]
Danke, vielleicht können das ja die MRMCD Leute regeln.

**Comment by Bfritz0815** [comment]
@jiska2342 also ich hab heute das Gerät im Getränkelager gesehen und da sah es so aus, als ob der taster noch dran wäre. (siehe https://github.com/raumzeitlabor/rzl-tuwat/issues/51 )

Habt ihr schon weitere Pläne mit dem Duellgerät(ohne Taster)?

**Comment by uwap** [comment]
Wurde das Gerät mittlerweile entsorgt? ich habe da jedenfalls im hinterkopf dass es entsorgt wurde. Kann das jemand bestätigen damit ich das hier schließen kann? @jiska2342

**Comment by Bfritz0815** [comment]
@uwap Das Gerät (mit beiden Tastern) steht im Getränkelager links hinten. Ticket muss wohl erstmal offen bleiben. 
Fragen: 
1. Taster hab ich abmontieren wollen, war mir dann aber zu nervig. Der Oberteil eines Tasters plus einige Schrauben dazu liegt nun in deiner obersten Schublade vorne drin @jiska2342 . Evtl. finden sich ja mal Leute, die das Geräte oder Teile davon nach Stuttgart schaffen. 
2. @jiska2342Hat sich der Shackspace schon mal zum Rest des Geräts geäußert?

@abrock was meinen denn die MRMCD-Leute zu Elses Vorschlag?

**Comment by uwap** [comment]
@jiska2342 Kann der Rest nun weg?

@muzy Brauchst du immer noch die Grobhandtaster? Soll ich die in 2 Woche richtung Chaosdorf tragen? Was ist mit dem Rest?

**Comment by uwap** [comment]
Ist weg. Die Grobhandtaster liegen in der Kiste von @jiska2342.

**Comment by uwap** [comment]
Die Grobhandtaster sind jetzt auf den Weg ins Chaosdorf zu Muzy, just for the record.
