### ISSUE TITLE
Raum Telefon kaputt

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#181]
Wenn man im Raum anruft geht der Anruf häufig gar nicht durch. Müsste mal Jemand™ schauen warum und fixen.

**Comment by Kunsi** [comment]
Das Tor funktionierte beim letzten mal über ISDN auch nicht, vielleicht ist das ISDN generell kaputt?

**Comment by uwap** [comment]
Nein, manchmal geht es, aber nicht immer.

**Comment by uwap** [comment]
Also ja, natürlich irgendwas am ISDN. ^.^

**Comment by Ranlvor** [comment]
*Kommentar einschieb, dass auch das „ISDN“ mittlerweile leider per VoIP rein kommt*

**Comment by uwap** [comment]
Tritt das Problem noch auf?

**Comment by Ranlvor** [comment]
War gerade wieder kaputt

**Comment by Ranlvor** [comment]
Sieht aktuell stabil aus.
