### ISSUE TITLE
TRÅDFRI-Infrastruktur

### ISSUE THREAD

**Issue by Ranlvor** [raumzeitlabor/rzl-tuwat#189]
- [x] OpenHAB updaten (notwendig für TRÅDFRI-Modul)
- [x] TRÅDFRI-Gateway besorgen
- [x] TRÅDFRI-Gateway in OpenHAB einbinden
- [x] FLOALTs anlernen (an's Gateway)
- [x] FLOALTs anlernen (an's OpenHAB)
- [x] in Sitemap einfügen
- [x] MQTT
- [x] Map
- [ ] ???
- [ ] Profit

**Comment by Kunsi** [comment]
Ich glaube, das TRAFRI-Gateway will man nicht verwenden, weil das eben *nur* TRAFRI kann. Fragt mal @Drachenkaetzchen nach Details, die hat da auch solche Lampen zuhause.

**Comment by uwap** [comment]
Wir haben halt nur TRÅDFRI Lampen. Es gibt afaik noch ein Gateway von Phillips für die Phillips Hue lampen. Das ist auch TRÅDFRI kompatibel aber deutlich teurer als das TRÅDFRI Gateway und ich sehe auch sonst keinen Vorteil.

**Comment by Ranlvor** [comment]
FLOALTs sind am OpenHAB 2 und an der Map angebunden.

**Comment by Ranlvor** [comment]
@Kunsi @Drachenkaetzchen Mittlerweile scheint das TRÅDFRI-GW auch Fremdkrams zu können. Konnte erfolgreich einen China-RGB-Controller [1] anlernen und mit Fernbedinung/App/OpenHab steuern.

Contra: Die IKEA-Fernbedinung kann nur An/Aus/Helligkeit und keine Farben und das Statusfeedback von Fernbedinungs-Aktionen an's Gateway tut nicht.

Pro: Der App/OpenHab-Krams funktioniert vollständig.

[1] https://de.aliexpress.com/item/GLEDOPTO-ZIGBEE-Led-Controller-RGB-CCT-WW-CW-zigbee-controller-LED-DC12-24V-LED-strip-controller/32858603964.html?spm=a2g0s.9042311.0.0.76534c4d2SVVWL

**Comment by tabascoeye** [comment]
IKEA hat auch rgb LEDs mit einer anderen Fernbedienung. Vll müssten wir uns die mal anschauen
