### ISSUE TITLE
MRMCD Stuff

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#19]
Der Raum steht voll mit Kisten der MRMCD (Shirts, Tassen, ...). Hier muss das weitere Vorgehen geklärt werden.

**Comment by abrock** [comment]
Shirts gehören Besuchern, die sie nicht abgeholt haben.
Tassen habe ich drei gesehen, die habe ich in die MRMCD-Schublade.
Es gibt zwei große Ikea-Kisten mit Dingen, da kläre ich die Weiterverwendung auf dem nächsten Orgatreffen.
War das alles? Ich bin nächstes WE nicht da.

**Comment by silsha** [comment]
Es standen noch diverse Kisten mit Baustellenmaterialien rum. Was passiert mit den T-Shirts? Können die mitgenommen werden? Stehen die zur freien Verfügung? Wie werden wir sie los? (Und den Rest auch.)

**Comment by else** [comment]
Es gab auch noch eine Kiste mit Tassen, glaube vom letzten Event.

**Comment by abrock** [comment]
Die Textilien sind Eigentum der Leute, die sie vorbestellt und bezahlt haben. Wie gesagt, ich kläre das auf dem nächsten Orgatreffen.

**Comment by s1lvester** [comment]
Is glaub ich bis auf eine kiste erledigt. close?

**Comment by steeph-k** [comment]
Das Baustellenschild habe ich im Getränkelager gesichtet, glaube ich. Im Hauptraum stehen noch Tischplatten, von denen ich gehört habe, dass sie von einer MRMCD waren und in der Werkstatt stehen die dazugehörigen Tischbeine. Sonst ist mir zumindest nichts aufgefallen. Also im Weg steht nichts.

**Comment by Bfritz0815** [comment]
Im Getränkelager ist noch ne Box mit MRMCD 2015 Postern.

**Comment by Bfritz0815** [comment]
@abrock Stand: im Hauptraum stehen hinter der Tür 2 MRMCD-Tische (auseinandergenommen). Im Lager stehen glaubich noch MRMCD-Poster von 2015 (please trash or giveaway). Wenn die weg sind, können wir das Ticket schliessen. Thx.

**Comment by uwap** [comment]
@abrock @Bfritz0815 Wie ist der aktuelle Stand? Sind die Sachen schon weg? Falls die Poster nicht weg sind, können die weggeschmissen werden?

**Comment by uwap** [comment]
Ist entsorgt.
