### ISSUE TITLE
Rednerpult weiß anstreichen

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#191]

**Comment by Bfritz0815** [comment]
anthrazit (für weniger Helligkeit des Pultes bei Video-Aufzeichnungen von Vorträgen)

**Comment by heylix** [comment]
Hab mich jetzt für eine Zwischenlösung zwischen weiß und anthrazit entschieden: das random hellgrau, was entsteht, wenn man schwarz und weiß in einem undefinierten Verhälttnis mischt.

Befindet sich derzeit in einer Haribo-Dose in der neuen Werkstatt und in Teilen auch bereits auf dem oberen Teil des Rednerpults. Den unteren Teil wollte ich erst mal nicht bearbeiten, da das so komisches Ikea-Pressspan ist und ich es nicht durchscheuern wollte.

Dieses Tuwat wird also quasi bearbeitet :)

**Comment by Ranlvor** [comment]
Unterer Teil ist weiß (weil weiße IKEA-Korpen), oberer Teil ist gestrichen -> Close
