### ISSUE TITLE
Alert mit text und Leuchte um an müll zu erinnern

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#193]
Es ist wieder Sommer:
Die Blumen dörren, die Vögel hecheln. 
Und im RZL hat sich die Mitgliederzahl seit Dienstag vervierfacht:

Mal wieder durfte ich einen Mülleimer im RZL nicht nur leeren, sondern auswaschen, da er vor Fliegen ud Maden nur so wimmelte. 

Da man am Dienstag wohl übersieht, den Müll rauszubringen, möchte ich folgendes haben:
Einen Task, der zwiscehn März und August jeden Dienstag um 21:30 zündet, 
das Küchenlicht anschaltet auf max, auf dem Panel im Hauptraum einen text anzeigt "Küchenmüll bitte rausbringen", die Alarmleuchte anschaltet, die Klingel 3 Sekunden laufen lässt und für 5 minuten den Onkyo ausschaltet (mit wiederholten checks, damit wieder Einschalten ncihts bringt).

**Comment by Ranlvor** [comment]
Ich bin da pessimistisch, ob das was hilft.

Wenn wir einfach nur die Leute ärgern (viel zu laute Klingel viel zu lang laufen lassen, plötzlich viel zu viel Licht, Musikanlage sabotieren, etc…) sogt das nur dafür, dass Leute (zurecht) angepisst sind und den Job wieder abschalten.

Vorschlag für die „mildere“ Version der Idee:
- 10 s Rundumleuchte (doppelt so lange wie bei IRC)
- 100 ms Klingel (doppelt so lange wie bei IRC) (das müsste ich mir aber erst noch anhören, wenn ich im RZL bin, um zu prüfen, ob das nicht zu viel ist)
- Text: „Gegen Fliegen & Maden: Bitte Küchenmüll runterbringen“

**Comment by Bfritz0815** [comment]
Die Dauern kann man ja noch ausprobieren. 
Bei dem Vorschlag mit dem Onkyo geht es darum, dass keiner sich angesprochen fühlt, wenns gleich nach dem kurzen Klingeln wieder saugemütlich ist. 
Wenn alle wissen, dass der "Betrieb" eh für 5 Minuten unterbrochen ist, dann findet sich eher jemand um den Müll rauszubringen. 
(Oder die Küche zu entrümpeln oder die Spülmaschine ein/auszuräumen und andere Dinge, die im Sommer regelmäßig laufen sollten)
Nach einem Abend, in dem der ganze Raum voll ist, gibts auf jeden Fall genug zu tun. 

Das können wir ja auch für jeden Tag nutzen, für den es üblicherweise Folgeprobleme gibt. 
(Was ja jetzt den Sonntag zum Glück nicht mehr involviert)

**Comment by uwap** [comment]
Ich bin sehr dafür so einen Alarm zu machen. Ich finde Onkyo ausschalten auch sinnvoll. Die Klingel würde ich jedoch nicht länger leuten lassen wollen, als beim Ping. Die ist an sich schon nervig genug.

Eventuell könnten wir auch sowas überlegen, wie die Augsburger im OpenLab haben. Die haben dort das Stackenblocken. Das ist 1 mal täglich gegen 20 Uhr, auch am offenen Abend. Dabei geht die Rundumleuchte dauerhaft an und über die Medienanlage läuft der Sound vom Stackenblockenvideo für 3 Minuten in Dauerschleife. Jeder der in der Zeit nicht aufräumt, wird von den anderen dazu gebracht mitzumachen. Das funktioniert da ziemlich gut, für generelles ordnung schaffen.

**Comment by tabascoeye** [comment]
Auch im MetaLab gibt es sowas. Dort pulsiert die Beleuchtung rot und steht für "Aufräumen". Es gibt eine TODO Liste, was dann alles getan werden muss.
Das habe ich vor Ewigkeiten schonmal erzählt und wir wollten es mit dem NodeRed umsetzen, wurde dann aber nie gemacht...

**Comment by Ranlvor** [comment]
Hab mal die milde Version implementiert. Für Mai - September und nur, wenn der Raum offen ist.

**Comment by abrock** [comment]
Wir haben inzwischen Stackenblocken.
