### ISSUE TITLE
Sonntag...

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#195]
Das Wipe and Defrag und das Plenum fällt immer auf den Sonntag. Ich habe das Gefühl, dass die Leute, die ausschließlich Sonntags da sind, inzwischen keine Lust mehr haben, den Müll von den Dienstagsleuten wegzuräumen, zumal sie meist die einzigen sind, die irgendwie sozial gezwungen werden was zu tun.

Das ist meiner Meinung nach ein Problem. Es gibt zwar immer genug motivierte Leute, um den meisten Müll wegzuräumen, es ist aber dennoch etwas unfair und macht wipe and defrags und plenen unangenehmer.

Lösungsvorschläge?

**Comment by silsha** [comment]
Ein tägliches Mini-W&D, wie im Metalab? Dort blinken täglich um 22 Uhr oder so alle Lichter für 5 Minuten, in denen alle Anwesenden gedrängt werden irgendwas sinnvolles zu machen (Müll wegwerfen, Geschirr in die Maschine, Kühlschrank auffüllen, etc.)

**Comment by silsha** [comment]
nvm, ich sehe gerade, dass genau der Vorschlag schon in https://github.com/raumzeitlabor/rzl-tuwat/issues/193 besprochen wird.

**Comment by Bfritz0815** [comment]
Trotzdem guter input. Vielleicht können wir von deren Erfahrungen
profitieren.
Kennt sich jemand da gut genug aus um dazu konkretere Angaben zu machen.


silsha fux <notifications@github.com> schrieb am Mo., 30. Juli 2018, 17:53:

**Comment by schinken** [comment]
Wir hatten das bei uns mal, dass Dienstag Abend um 20 Uhr ein Alarm kommt, dass Menschen die Küche kontrollieren sollen (abgelaufenes Wegwerfen, Müll raus, ...) - nichtmal im gesamten Space.

Hat leider, trotz recht guter Moral bei uns, nie geklappt. Menschen haben ans LED Board geschaut - den Text gesehen - und weitergemacht

**Comment by silsha** [comment]
@schinken Das klingt nach etwas, was 2-3 Menschen tun können - daher können das ja auch „andere“ machen.
Wenn täglich alle anwesenden motiviert werden was zu tun ist es leichter die Faulenzer konkret anzusprechen.

**Comment by Bfritz0815** [comment]
Genau mit dem Verhalten rechne ich auch wenn nur eine Nachricht erscheint
und das wars.
Deswegen muss die Atmosphäre der Gemütlichkeit aufgehoben werden: alle
lichter auf max, alarm an und den onkyo fuer 3 Minuten auf was antreibendes
stellen.


Christopher Schirner <notifications@github.com> schrieb am Di., 31. Juli
2018, 13:27:

**Comment by Bfritz0815** [comment]
Stackenblocken läuft nun täglich. Looks good so far. Closing

**Comment by Bfritz0815** [comment]
BTW: Dank an @Ranlvor für die Arbeit mit der Umsetzung
