### ISSUE TITLE
Funksteckdose Ventilator zickt

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-tuwat#196]
Als ich gestern ins RZL kam, lief der Deckenventilator schon.
Ich hab gedacht, dass er vielleicht nicht mit in der Abschalteroutine im NodeRed drin ist, aber als ich ihn per map abschalten wollte, ging das nicht.
Im alten openhab Interface wurde die Dose als ausgeschaltet gezeigt und schalten brachte auch keinen Effekt.
Da wir gehen wollten habe ich die Dose dann manuell über den taster abgestellt.

Müsste mal gecheckt werden, ob da was nicht stimmt.

**Comment by uwap** [comment]
Ich finde wir sollten mal alle alten Funksteckdosen durch Sonoffs ersetzen, da das schon ab und an mal mit den alten Funksteckdosen vorkommt.

**Comment by s1lvester** [comment]
I agree with uwap

**Comment by Ranlvor** [comment]
Habe die Dose vom Strom getrennt, 10 Sekunden gewartet, wieder eingesteckt, jetzt funktioniert sie wieder.

Ansonsten: was @uwap und @s1lvester sagen klingt irgendwie mit jedem Reset einer Dose, den ich mache, ein bisschen mehr verlockend.
