### ISSUE TITLE
Tupperware™ ausmisten

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#2]
Slowpoke will nur noch die Tupperware mit den blauen Deckeln, und die Neuen. Damit wir alles stapeln können.

**Comment by Bfritz0815** [comment]
close, weil done?

**Comment by Don42** [comment]
Es müssen noch die alten entsorgt werden. Kann man glaube ich zu #23 hinzufügen und das hier schließen.
