### ISSUE TITLE
Pizza-Tiefkühler

### ISSUE THREAD

**Issue by Ranlvor** [raumzeitlabor/rzl-tuwat#200]
Ohai,

eigentlich wollen wir doch wieder einen Tiefkühlschrank für Pizza, Lasagne, etc. In der E-Ecke steht noch der alte, der würde grob gemessen unter die Treppe passen.

Wollen wir das mal umstellen?

Gruß
Rnalvor

**Comment by uwap** [comment]
Unter der Treppe sind zur Zeit leider die Schuhe. Wo sollen die dann hin?

**Comment by s1lvester** [comment]
Unter die Tische an der Beamerwand. Wäre eine gute Möglichkeit da mal aufzuräumen 😉

**Comment by Bfritz0815** [comment]
*TLDR: *
*Nein*: Da zu viele Seiteneffekte:

   1. der Alte Schrank gehört weg
   2. Ich habe bisher keinen brauchbaren Vorschlag fürs Platzieren der
   Garderobe gehört
   3. Wozu überhaupt einen Mitglieder-*Gefrierschrank*? (Ist dann nur
   Müll-Lager und einer alleine wird dafür nicht reichen)
   4. Aufräumen vor der Beamerwand bitte erst nach dem NebenNeban raum: Zu
   viele Dependencies für einen korrekten Defrag


*Gegenvorschlag:*
A:
Keinen Mitglieder-Gefrierschrank: (0€ Kosten, 0 Müll-Endlager, 0
Platzvergeudung, 0 Bäh-Faktor)

B:
Wenn unter der Beamerwand nach dem Nebenebenraum-Bau Platz ist, kommen da
die Kästen Leergut hin.
Bei der vielen Breite ist da Platz genug ohne in die Höhe zu gehen.
Hinter dem Getränkekühlschrank könnten wir dann einen richtigen,
geräumigeren Gefrierschrank stellen. (oder 2 kleinere? => weniger Risiko
wenn einer offen stehen bleibt...)
Der wäre bei der Kasse und mehr Platz als die Kästen würde er auch nicht
einnehmen.



*Langfassung*:

Bin da nicht so der Freund von:
1.
der Kühlschrank ist ein *Siffmonster*. Warum wir den noch nicht weg haben,
ist mir rätselhaft

2.
ich mag die Nische als *Garderobe + Schuhabstell-Fläche +
Rucksäcke-Abstellfläch*e schon sehr gern.
Besonders im Winter (der ja bald kommt) werden wir viel Platz für Jacken
und Stiefel brauchen.
Da wir ja den Kiosk so weit Richtung Eingang gezogen haben, muss da
woanders Platz her. Vorschläge herzlich willkommen.

Vorne *beim Beamer können wir keine Jacken aufhängen* und ich halte nichts
davon, Jacken und Schuhe getrennt aufzustellen.
Das beachtet dann eh keiner und wir stolpern wieder dauernd im ganzen Raum
über Stiefel.

Der Tisch unter der Treppe gibt der Küche mehr Freiraum für
Veranstaltungs-Arbeiten und ansonsten ist das eine exzellenter Ort um
Rucksäcke abzustellen, wenn die Besitzer keinen Platz am Tisch brauchen.
Das aktuelle Pattern, sein Scheiss auf einen/zwei/drei Plätze zu werfen und
sich dann  woanders hin zu verziehen geht mir nämlich dezent aufn Sack.
Ohne den Tisch können wir da nicht viel ändern.

Auch offen bei dem Entwurf: *Wohin mit dem runden Mülleimer*?
Bisher hat der eine sehr gute Nische, sodass er *nicht im Weg* steht.

3.
Ich möchte auch daran erinnern, dass der etwas geringere Platz an
Gefrierschränken im RZL schon im Küchenmeeting berücksichtigt und in Kauf
genommen wurde:
Einen weiteren für direkt daneben hat man ja absichtlich nicht gekauft.

*Wozu braucht man eigentlich einen Mitglieder-Gefrierschrank?*
Gefrierschränke diene zur langfristigen Lagerung sehr leicht verderblicher
Lebensmittel.
Kurz mal was einstellen, wie beim Kühlschrank, ist ja OK, aber:
Seit wann ist es Vereinszweck, Lebensmittelreste monatelang zu lagern?

Wenn wir das wollen, sollten wir das Textillager zum Kühllager umrüsten,
denn dann wird auch ein einziger weiterer Gefrierschrank nicht reichen...

4.
Was das Aufräumen betrifft:
Den Laser wegschaffen geht erst wenn der NebenNebenraum da ist. Vorher wäre
es ein halbgares Rumräumen statt einem Aufräumen.
Auch: Wohin mit den Kisten Lost, Found und Giveaway?

Für unter der Beamerwand denk ich mir eh 2 Modelle:
A: Frei lassen
B: geschlossene Schränke für Bedarfsmaterialien wie z.B. die Kabel, die im
MOment im ganzen Raum rumfliegen.
Wenn die AV-Kabel im Rednerpult sind und alle Anderen in mehreren GUT
SORTIERTEN Kisten in den Schränken,dann wäre das eine Verbesserung

**Comment by uwap** [comment]
Um hier nicht tausende Themen durcheinander zu bringen, sag ich mal nur was zur Gefriersituation. Also in alle den ganzen Küchenmeetings in denen ich war, kann ich mich nicht an ein Argument gegen eine zweite Tiefkühltruhe erinnern.

Aktuell sieht es eher so aus, dass die Tiefkühltruher fast nur für Mitgliederkrams genutzt wird und kaum Platz für Pizzen da ist. Und wenn Pizzen da sind, landen sie ganz hinten, vor dem Mitgliederkram.

Entgegen deinen Behauptungen sehe ich auch nichts länger als 3 Wochen dadrin, von dem ganzen Mitgliederkrams.

Ich würde eine Kühltrühe in der Nähe der Snackbar für den Verkauf bevorzugen.

**Comment by Bfritz0815** [comment]
@uwap 
Kann sein, dass mich da mein Gedächtnis täuscht und ich war auch nicht auf allen Meetings dazu. Aber ich erinnere mich, dass zur Sprache gebracht wurde, ob man wirklich aus den beiden Gefrierschränken, die vorher da waren, einen machen will. 
Der Konsens war: Ja. 
Dann hab ich da nicht weiter gedrängt. 

Ich erinnere mich auch an das Argument, dass man sowieso nicht tonnenweise Zeug im RZL in Gefrierung lagern soll und daher ein zweiter Schrank überflüssig sei.

**Comment by tabascoeye** [comment]
Ich habe bewusst die kühl-gefrier-Kombi genommen. Beim umräumen habe ich den alten gefrierschrank mit Pizza etc da komplett reinbekommen.
Sehe keinen Bedarf für mehr.
Die kakigori-förmchen raus, dann ist da wieder Platz für TK-Fraß.

**Comment by Bfritz0815** [comment]
@uwap 
**wg "Entgegen deinen Behauptungen sehe ich auch nichts länger als 3 Wochen dadrin, von dem ganzen Mitgliederkrams.":**

Ein 1 kilo Beutel Shrimps abgefüllt Anno 2016, hab ich weggeworfen. 
Herzliche Grüße an wer auch immer "Roulette" ist für Müll in der Küche und die Art, wie meine Finger nun nach altem, ranzigen Fisch stinken. Frisch war da trotz Gefrierung nichts mehr. 

An dieser Stelle bitte an meinen Punkt zum Thema "Müllager" erinnern. Danke. 


Auch aktuell im Gefrierschrank:
1. Bohnen
2. diverse Beutel mit Kräutern (WTF?)

Das zusammen mit den shrimps verbraucht schon 1 Drittel des Platzes. 

Die Leitlinie war mal: 
**Mitbringen, essen, wieder nach Hause mitnehmen.** 

Für **Gemüse und Co** kann man argumentieren:
Entweder direkt wieder mitnehmen oder in den Kühlschrank und innerhalb von 3 Wochen verzehren. 
Im (geräumigen) Kühlschrank gibt es extra dafür unten das Gemüsefach. 
Für Kräuter gilt das Selbe. 

Für **Fleisch, Fisch und Co** kann man argumentieren:
Der Gefrierschrank in einem Verein kann jederzeit aus Unachtsamkeit abtauen. 
Das merkt man dem Fleisch äusserlich nachher u.U. nicht so an. 
Ergebnis: Salmonellen + Lebensmittelvergiftung. 
Als Verein sollten wir uns das Haftungs- und Gesundheitsrisiko dazu nicht gönnen. 

Für **Eis** kann man argumentieren:
Bitte keine Vorräte für mehrere Wochen hamstern. Danke. 
Mit der Regel "Mitbringen, essen, wieder nach Hause mitnehmen" löst sich das Platzproblem automatisch. 
Hier wirkt sich die Hamster-Mentalität am krassesten aus. 


Was meint Ihr zu meinen Überlegungen?

**Comment by Bfritz0815** [comment]
Ich hab jetzt mal ein Paar Dinge umgeräumt, damit wieder Platz im Gefrierschrank ist:

1. **Privatkrams** ist unten im Schubfach drin
2. Die **Formen für Shaved-Ice**: 4 davon hab ich im oberen Fach hinten in die Schräge gepackt damit sie nicht im Weg rumstehen. Der laufende Bedarf ist ja nicht hoch
3. Alle restlichen 6 Formen für Shaved-ice hab ich ins Gemüsefach im Kühlschrank gepackt (so können wir die ins Kühlen investierte Energie wieder teilweise reinholen) Wenn sie abgetaut sind, kann man das Wasser wegkippen und die Formen zur Maschine stellen
4. Die (public) **Bohnen** sind jetzt im Gemüsefach vom Kühlschrank wo sie hingehören. Wer langfristige Vorräte anlegen will, kann das zu Hause tun
5. Die unverpackten (public) **Schnitzelreste** sind im Müll
6. Die (public) **antiken, halb zertauten Vanilleeis-Reste** im 1 Kilo Container sind im Müll
7. Das **letzte Sandwich-eis mit Beeren-Geschmack**, für das eine ganz Kiste im Gefrierschrank sein musste, hab ich mir gerade gegönnt. Danke an die noble Spende, wer auch immer das public-Eis spendiert hat

Ergebnis:
- Oberes Fach: Kein Mitglieder-Krams
- Mittleres Fach: kein Mitglieder-Krams
- Schubfach unten: Trotz gehamstertem Eis, antiken Eisresten in großen Containern und Beutel-Eis (Warum? Wir haben immer Eis in den Shaved-Ice-Formen) ist wieder Platz 

Das sollte fürs Erste schon mal helfen. 

Auch ein Ergebnis:
Meine Hände sind rauh vom vielen Händewaschen um das "eau de ranzige-Garnelen" loszuwerden. 
Wer die experience teilen mag: Einfach das untere Schubfach öffnen und voila: Der Perfekte Abend-Duft für den Mann von der Müllhalde. 
Danke an dieser Stelle an alle, die mit ihrem alten, abgelaufenen, 3x durchgetauten Shit im Gefrierschrank zu dieser umwerfenden Mischung beigetragen haben. 

 @uwap Meine kleine Aufräumaktion hat also alle meine Annahmen im längeren Post in krasseste Weise bestätigt. Ich bin also mehr als je zuvor gegen einen Mitglieder-Gefrierschrank. 
Wir sollten stattdessen die Regeln für die Gefrierschranknutzung enger fassen und durchsetzen. 

Ich werde in Zukunft in random spotchecks den Gefrierschrank entrümpeln

**Comment by Bfritz0815** [comment]
@tabascoeye way ahead of you :)

**Comment by Bfritz0815** [comment]
@Ranlvor @uwap schaut mal bitte beim nächsten Besuch, ob ein weiterer Schrank dann noch nötig ist. 

Ich finde, ein größeres Schrankvolumen hat zwar den Vorteil, dass man **seltener einkaufen** muss, aber die **Vorteile** daraus sind schon nicht so groß:

1. Der Aldi is direkt um die Ecke: Es ist kein Problem, Nachschub zu besorgen
2. Mehr als jetzt in den Gefrierschrank geht kann ich auch nicht auf einmal vom Aldi in Taschen mitbringen

Dazu kommt der **Nachteil**:
Wenns abtaut, ist **mehr** auf einmal **wegzuwerfen**: In unserem Verein taut es schon etwa alle 3 Monate mal ab, weil jemand die Tür nicht richtig schließt. 
Deshalb hab ich oben auch angerissen, statt einem Größen Snackbar-Kühlschrank lieber 2 kleinere anzuschaffen (falls wir überhaupt einen anschaffen wollten)

**Comment by Ranlvor** [comment]
Na gut. Dann haben wir ja jetzt ein Pizzagefrierfach.

Eventuell sollte man noch die Bereiche entsprechend labeln, damit im Mitgliedsbereich auf Grund der Größenbeschränkung öfter die Garbage Collection läuft.

**Comment by Bfritz0815** [comment]
@Ranlvor Ich fand die Backofen-Anleitung ganz gut. Vielleicht würde ein solcher Zettel am Gefrierschrank helfen?

**Comment by Ranlvor** [comment]
Ich wäre für etwas laminiertes IM Gefrierschrank, vielleicht in bunt links und rechts neben den Fächern / an der Schublade (?) oder so. Einfach nur die Hinweise „Public Zone“ (grün) und „Kommerz Zone“ (rot) oder sowas.
