### ISSUE TITLE
Verkaufs-Gefrierschrank

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#203]
@uwap  Ich weiss, ich hatte mich mal dagegen ausgesprochen, einen Gefrierschrank für den Verkauf anzuschaffen. 

Aber:
Jetzt hat Ozi erwähnt dass er beim Langnese Werksverkauf gut vorbeikommt, sodass er dort im Sommer extrem günstig an verschiedene Eissorten kommt. 

Dafür reicht dann das bestehende Schrankvolumen nicht mehr so gut. 

Wir haben da jetzt mal den Platz neben dem Kühlschrank ausgemessen und eine Option ausgesucht:

https://shop.rauschenbach.de/Kuehlmoebel/Eureka/Tiefkuehlschraenke-mit-geschaeumten-Tueren-Eureka/Tiefkuehlschrank-SD-72-Esta.html?gclid=CjwKCAiA4OvhBRAjEiwAU2FoJdn1Jz1F08vR3oI3aUnUG4FAk2M8P3vDrXXuVZeFaP4IJzqXn9zW5hoCrc4QAvD_BwE

Der Preis ist bei 590 € aber dafür hat er auch etliche Vorzüge, die die billigeren nicht haben:

1. 90 Liter Fassungsvermögen
2. **Glastür**, sodass Leute nicht unbedingt endlos die Tür aufreißen müssen um zu sehen, was drin ist
3. **Automatische Türschließung** (nie wieder 10 Kilo versumpfte, abgetaute Ware wegwerfen)

Lieferung frei Bordsteinkante

Meinungen?

**Comment by Ranlvor** [comment]
Nice. Wenn der Dienstag, 15.01.2019 gegen 15:30 an 49.508475, 8.500508 steht nehm' ich den mit hoch :-)

**Comment by uwap** [comment]
Mit der Glastür ist das natürlich sehr geil.

Es ging ja schon immer darum, dass in unserem Eisfach nicht genug Platz ist. Neben Eis wollen wir ja auch noch Pizza, Lasagne und Kratz- und Wassereis verkaufen.

Und gerade mit Glastür ist recht offensichtlich, dass es ein verkaufsschrank ist. Wir können die Preise offensichtlicher platzieren, sodass Leute daran denken zu bezahlen. Neben welchen Kühlschrank willst du den stellen? Ich denke mal du meinst unter die Treppe, oder?

**Comment by Bfritz0815** [comment]
Ja, unter die Treppe

Am Mo., 14. Jan. 2019, 01:05 hat uwap <notifications@github.com>
geschrieben:

**Comment by heylix** [comment]
Also _676,88 € inkl. 19 % MwSt. frei Bordsteinkante_ finde ich schon krass.

Wollen wir nicht vielleicht eine gebrauchte "klassische" Truhe ähnlich dieser? https://www.ebay.de/itm/Eistruhe-AHT/163276115653?hash=item260403cec5:g:OZUAAOSwuehbMzAN

**Comment by Bfritz0815** [comment]
Klar is das nicht billig.
Aber:

   1. Die Truhe ist "gebraucht": Bei manchen Gebrauchten kriegt man
den *Gestank
   *nicht mehr raus. Vorsicht.
   2. Auch weisst du nciht, was da an *Schimmel und Keimen *in einem alten
   Kühlsystem steckt. Wir haben hier niemand, der so ein versifftes Kühlsystem
   korrekt reinigen könnte.
   3. Bei Truhen schliessen die Leute den Deckel kaum je richtig. Die Folge:*
   Mehr Stromverbrauch und weniger Haltbarkeit*
      1. Daher sollten sich der Schrank gegenüber der Truhe allein durch
      geringere Stromkosten und weniger *Weggeworfenes *früher oder Später
      amortisieren
   4. Auf einem Schrank kann man oben dinge ablegen, auf einer Truhe nicht.
   Das hindert aber niemand daran,  Dinge abzulegen. Daher ist das dann
   äusserst* lästig und ggf unhygienisch*, je nachdem was da abgestellt
   wird.
   5. Dafür dass man nur den halben Preis "sparen" würde, ist mir das
   hygienische Risiko bei einer gebrauchten Truhe zu hoch


TLDR:
Eine Truhe will ich kategorisch nicht wegen Stromverbrauch und Hygiene und
Komfort.
Gebrauchte Kühlgeräte will ich nicht wegen Hygiene und Geruch.
FYI: *Ich persönlich werde nichts aus einem gebrauchten Kühlgerät kaufen*
(sollte eines angeschafft werden).

**Comment by tabascoeye** [comment]
Früher war mehr Vereinszweck ("Förderung der Erziehung, Volks- und Berufsbildung einschließlich der Studentenhilfe") und weniger "ich will X, sonst Y"

Ich bin jedenfalls dagegen 600€ Mitgliedsbeiträge auszugeben, damit ihr im Sommer mal ein Eis schlecken könnt.

**Comment by uwap** [comment]
Das heißt du bist dann auch dafür, die Snackbar nicht mehr aufzufüllen, @tabascoeye? Das erfüllt ja auch keinen Vereinszweck sondern dient nur dazu, dass wir was zu knabbern haben und wir geben da auch gut 600€ aus, wenn wir Snacks kaufen.

Ich finde 600€ auch viel und wäre auch dafür zu schauen ob es was um die 300€ gibt. Es gibt hier aber keinen Grund uns gleich wieder anzupampen deswegen. Wenn wir nur noch nach Vereinszweck gehen würden, würden wir vieles nicht mehr machen können. Wozu brauchen wir dann eigentlich noch eine Küche? Wofür brauchen wir das Getränkelager? Oder generell Getränke? Wofür brauchen wir den Olymp überhaupt noch?

Ich fände es schon wichtig, wenn der Vorstand nicht mehr alle aktiven Mitglieder vergraulen würde, sonst gäbe es bald niemanden mehr, der noch lust hat was im Sinne des Vereinszwecks zu organisieren.

**Comment by flederrattie** [comment]
(Ach, @uwap komm mal langsam wieder runter... das ist kein Grund schon wieder auf Krawall gebürstet zu sein.)

Zum Gefrierschrank:
Ihr wollt einen zweiten Gefrierschrank für etwas mehr Pizza im Winter und mehr Eis im Sommer.
Soweit, so gut. 
Ich verstehe allerdings auch nicht ganz, warum wir dafür so viel Geld ausgeben müssen.
Bitte haltet euch vor Augen, dass das knapp 24 "normale" Mitgliedsbeiträge sind.

Das Ding hat noch nicht mal eine klare Energieverbrauchskennzeichnung (ist wohl auch besser so... eine Glasscheibenheizung im Innenraum muss auch erstmal wieder weggekühlt werden.)
Wozu brauchen wir überhaupt einen Gefrierschrank mit einer Glasscheibe? Es weiß doch jeder was drin lagert. Beim normalen Kühlschrank und dem Getränkekühlschrank funktioniert das auch ganz prima ohne Scheibe. Argument: Damit nicht jeder immer die Tür aufreißt... Wenn da stapelweise Pizza übereinander liegt, muss ich trotzdem die Tür aufmachen um zu schauen, ob meine Lieblingsspinatpizza unter der mit Salami liegt. 

Auch die automatische Türschließung ist in meinen Augen nichts weiter als mal wieder der Versuch ein soziales Problem technisch zu lösen. Man kann auch einfach die vorderen Füße ein wenig höher schrauben als die hinteren, damit die Tür von selbst nach hinten kippt. Gerne kann zusätzlich ein Zettel mit der Bitte um Rücksicht beim Schließen aufgehängt werden.

Kurzum: Ich würde mich freuen, wenn sich nach einem oder am besten mehreren energiesparenden, günstigeren Modellen umgeschaut werden würde und diese auf das Plenum zur Abstimmung wandern würden. Des Weiteren fände ich es schön, wenn solche Diskussionen auch mal wieder auf die Mailingliste wandern würden, da es viele Mitglieder gibt, die nicht auf Github sind.

**Comment by tabascoeye** [comment]
Strohmannargument, what-aboutism und emotionale Erpressung.

Als Antwort auf ne Meinungsäußerung.
Mir fehlt die Lust auf dem Niveau zu reden.

**Comment by abrock** [comment]
> Das heißt du bist dann auch dafür, die Snackbar nicht mehr aufzufüllen, @tabascoeye? Das erfüllt ja auch keinen Vereinszweck sondern dient nur dazu, dass wir was zu knabbern haben und wir geben da auch gut 600€ aus, wenn wir Snacks kaufen.

Der Vergleich ergibt keinen Sinn, es geht ja nicht darum Eis zu kaufen was dann wieder verkauft wird sondern einen Schrank anzuschaffen um große Mengen Eis zu lagern.

> Es gibt hier aber keinen Grund uns gleich wieder anzupampen deswegen.

Nicht jede Gegenmeinung zur eigenen Meinung ist "anpampen".

> Wozu brauchen wir dann eigentlich noch eine Küche?

Zur Förderung der Erziehung, Volks- und Berufsbildung einschließlich der Studentenhilfe, konkrekt geht es darum die Zubereitung von nahrhaften Speisen zu lernen.

> Wofür brauchen wir das Getränkelager? Oder generell Getränke?

Wenn man nichts trinkt muss man sterben.

> Ich fände es schon wichtig, wenn der Vorstand nicht mehr alle aktiven Mitglieder vergraulen würde, sonst gäbe es bald niemanden mehr, der noch lust hat was im Sinne des Vereinszwecks zu organisieren.

Es würde mir enorm helfen wenn du nicht bei dem geringsten Widerstand sofort so eine schlechte Stimmung verbreiten würdest sondern darüber nachdenken ob Gegenargumente u.U. berechtigt sind und diese ggf. in die Planung mit einbeziehen.

**Comment by uwap** [comment]
@abrock Wäre cool, wenn du auch noch mal schreiben könntest, was deiner Meinung nach dagegen spricht, doch nach gebrauchten Eisschränken zu schauen, statt nur einen Daumen runter zu geben.

**Comment by abrock** [comment]
> Schön wie wir uns jetzt wieder anpampen. Und wie oft hatten wir das Argument, dass 600€ zu viel ist jetzt schon? 5 mal?

Dreimal. Findest du die Validität des Arguments ändert sich mit der Anzahl der Wiederholungen? Wenn ja, in welche Richtung? Warum fragst du? Warum redest du schon wieder von "anpampen" anstatt dich auf Sachargumente zu beschränken?

> @abrock Wäre cool, wenn du auch noch mal schreiben könntest, was deiner Meinung nach dagegen spricht, doch nach gebrauchten Eisschränken zu schauen, statt nur einen Daumen runter zu geben.

Ob das RZL eine neue, gebrauchte oder garkeine Tiefkühltruhe anschafft ist für mich weniger relevant als dein ständiges Abwerten von anderen Meinungen als "angepampe".

> Gegen eine Truhe bin ich aber auch. Vielleicht gibt es ja auch gebrauchte Gefriertruhen mit Glastür?

Hatte heylix schon verlinkt:
https://www.ebay.de/itm/163276115653

**Comment by abrock** [comment]
> Des Weiteren fände ich es schön, wenn solche Diskussionen auch mal wieder auf die Mailingliste wandern würden, da es viele Mitglieder gibt, die nicht auf Github sind.

Ich bin dafür, dass tuwat-Diskussionen automatisch auf der ML landen. Das war ganz am Anfang vielleicht problematisch weil tuwat ein tolles neues Spielzeug war und innerhalb kürzester Zeit hunderte Kommentare und Issues der Form "Jemand müsste den Müll rausbringen --- Habe ich erledigt --- super, danke" auf der ML landeten, inzwischen ist das Kommentaraufkommen so niedrig dass es m.E. kein Problem mehr darstellt.

Andererseits könnten Threads wie dieser, die keinen Zusatznutzen aus Github-Features ziehen auch einfach direkt auf der ML gepostet werden.

**Comment by uwap** [comment]
@abrock Das wird schon im Issue #138 diskutiert.
