### ISSUE TITLE
Olymp aufräumen

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#205]
@heylix und ich wollen demnächst mal irgendwann den Olymp aufräumen. Die Idee ist, dass wir zwei Stapel machen "Wollen wir noch" und "Wollen wir nicht mehr". Über den "Wollen wir nicht mehr"-Stapel lassen wir Team Retro drüber schauen und gegebenfalls noch mal Sachen auf den anderen Stapel packen lassen. Als Möglichkeit das Übergangsweise zu lagern, bis der Olymp umgebaut ist, haben wir uns den alten MRMCD Bereich im Getränkelager vorgestellt. Nach dem Olymp Umbau würde dann alles zurück auf den Olymp bzw in den Free for all oder Müll kommen.

Das ganze hängt mit #167 und #164 zusammen.

**Comment by s1lvester** [comment]
Will wirklich nicht rumflamen aber gibts dieses Team Retro eigentlich noch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by steeph-k** [comment]
Falls nicht, würde ich mich als Ersatz anbieten, um sicher zu stellen, dass nicht alle Computergeschichte weggeworfen wird. Dass wir z.b alle zwölfzehn Amigas aufheben sollten, glaube ich allerdings auch nicht.

**Comment by uwap** [comment]
@steeph-k Keine Angst, das Team Retro existiert noch. Don't feed the trolls und so ;)

**Comment by steeph-k** [comment]
Klar existieren einzelne Personen noch. Aber die obensetehende Frage kam 
mir auch schon in den Sinn.

**Comment by uwap** [comment]
Olymp wurde mit der Hilfe von Team Retro aufgeräumt. Das Team Retro räumt den Olymp nach dem Umbau nach der Marie Kondo Methode wieder ein.
