### ISSUE TITLE
Küche entrümpeln

### ISSUE THREAD

**Issue by slowpoketail** [raumzeitlabor/rzl-tuwat#23]
- [x] Tupper™®© (aus)sortieren (siehe auch #2)
- [x] Schüsseln & sonstiges (aus)sortieren (zB gesprungenes)
- [x] Entsorgung von Schüsseln und Tupper™®©
- [ ] Elektrogeräte (aus)sortierien bzw einlagern (Eventzeug)
- [ ] Schränke putzen
- [x] Gläser & Tassen (aus)sortieren
- [x] Kühlschränke putzen
- [ ] Waschmaschine reinigen
- [ ] Spülmaschine ersetzen (ist undicht und auch sonst kaputt-ish)
- [ ] Mikrowelle putzen
- [x] Ofen putzen
- [ ] Töpfe aussortieren
- [ ] Topfrondell ersetzen

**Comment by slowpoketail** [comment]
Die Schränke links neben dem Kühlschrank, ausser dem Gläser/Tassenschrank sind geputzt. Der Gläserschrank wird nächstes Wochenende sortiert und geputzt.

Zur Spülmaschine: Nachfolgemodell würde 120€ kosten (laut DaFo).

**Comment by Don42** [comment]
Nur als Erinnerung für nächstes Wochenende. Die Gläser mit der Öffnung nach unten Stapeln. Da splittern öfters mal die Kanten der Böden, und wenn sie mit der Öffnung nach oben gestapelt sind hat man Glassplitter im Getränk. Das ist eher nicht so toll.

**Comment by Don42** [comment]
Gläser sind aufgeräumt. Ein Teil steht noch gespült auf der Arbeitsfläche. Diese können eingeräumt werden.
Es fehlen zu Nudelmaschine und Fleischwolf ein Schneckenwelle und eine Kurbel.

**Comment by abrock** [comment]
Die Schneckenwelle liegt zwecks Reparatur seit einiger Zeit[tm] bei mir zu Hause. Sobald die Drehbank läuft kümmere ich mich darum. Kurbel für Nudelmaschine kann ich auch herstellen.

**Comment by Bfritz0815** [comment]
wg "Schränke putzen": 
- Vorratsschränke (Mehl etc, Backzutaten, Kartoffeln) geputzt: Cheatha hat das vor ca 2W gemacht
- Tupper-Regal hat cheatha schon gemacht
- Schubladen sind von diversen Leuten sukzessive geputzt worden
- Gläser-Regal ist geputzt worden
- letztes WE hat jemand die Elektro-Regale geputzt

@slowpoketail  Damit sollte "Schränke putzen" erledigt sein, oder?

**Comment by steeph-k** [comment]
Der Ofen ist innen gereinigt. Nicht 100%ig, aber größtenteils glänzt er sogar wieder.

An der Waschmaschine wollte ich den Filter reinigen. Dabei ist mir aufgefallen, dass der Filter fehlt. Außerdem lag ein abgeschnittenes Stück Gummischlauch lose in der Filterkammer und beim Aufschrauben ist (sauberes) Wasser ausgelaufen. Ich kenne mich nicht aus, habe aber den Eindruck, dass da etwas nicht stimmt.
