### ISSUE TITLE
Treppenteppiche waschen/ersetzen

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#24]

**Comment by slowpoketail** [comment]
Wir sollten eher neue besorgen, da der Verdreckungszustand für waschen eigentlich schon viel zu hoch ist. Wir haben noch ein paar Ersatzteppiche, die sind aber nicht genug, es müssten dann neue bestellt werden.

**Comment by slowpoketail** [comment]
Teppiche wurden von von evilsadnes abmontiert. Neue müssten bestellt werden, 15 kosten laut Dafo ~30€.

- [ ] Teppiche abmontieren
- [ ] Neue Teppiche bestellen
- [ ] Neue Teppiche montieren

**Comment by abrock** [comment]
Erledigt.
