### ISSUE TITLE
32c3 Planung

### ISSUE THREAD

**Issue by slowpoketail** [raumzeitlabor/rzl-tuwat#26]
Das Congress-Wiki ist jetzt komplett funktional, und ich habe das RZL schonmal provisorisch als Assembly eingetragen. Weitere Infos (Platz, Projekte, Wünsche, etc) müssen noch nachgetragen werden. Mail auf die Liste ist ebenfalls unterwegs.

**Comment by jiska2342** [comment]
Danke soweit, TODO wäre noch das in eine große Assembly zu mergen (-> Diskussion ML).

**Comment by jiska2342** [comment]
https://events.ccc.de/congress/2015/wiki/Assembly:Singularity_City ist angelebt, RaumZeitLabor ist Child Assembly davon. Koordination von Strom&Platz über die große Assembly "Singularity City", ich bin etwa ab dem 20. Dezember in Hamburg und kümmere mich um alles vor Ort.

**Comment by abrock** [comment]
Sprinter ist reserviert.
