### ISSUE TITLE
Sicherungen im Nebenraumsicherungskasten dokumentieren

### ISSUE THREAD

**Issue by ghost** [raumzeitlabor/rzl-tuwat#27]
Wie das Topic schon sagt:
zur Zeit sind keine der Sicherungen (abgesehen von dem Kreppband) dokumentiert.

**Comment by maikf** [comment]
Die Liste der Sicherungen waren wohl mal als Zettel im Kasten vorhanden.
Habe gestern die Werkstatt durchsucht und nichts gefunden.
Zu zweit müsste man mal sämtliche Sicherungen mappen, welche Steckdosen sie schalten.

**Comment by uwap** [comment]
Wenn ich mich recht erinnere sind wir das an einem Wipe and Defrag letztes Jahr angegangen, so weit ich weiß mit @Bfritz0815 oder @steeph-k. Kann das Jemand von euch bestätigen? Ansonsten schaue ich die Tage im RZL noch mal ob das erledigt ist.

**Comment by steeph-k** [comment]
Ich kann das bestätigen. Soll ich mal?
Angegangen ist sehr passend. Es wurden dabei nicht alle Sicherungen beschriftet, wenn ich mich richtig erinnere.

**Comment by uwap** [comment]
Wenn ich mich recht erinnere, waren die anderen Sicherungen nicht zuordbar. Ich schließe das hier mal.

**Comment by steeph-k** [comment]
Unsere Erinnerungen zu hochprozentig deckend.

Als ich neulich einen Automaten schalten musste habe ich ihn jedenfalls sehr schnell gefunden, ohne jetzt sagen zu können, wie. Scheint also gut beschriftet zu sein, oder so.
