### ISSUE TITLE
Gitlab aufsetzen

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#28]
https://github.com/sameersbn/docker-gitlab

**Comment by else** [comment]
Bisher noch keine Lust gehabt, das einzurichten.

**Comment by lutoma** [comment]
Brauchen wir das wirklich? Sehe aktuell keinen Use-Case, GitHub funktioniert doch ganz gut für unsere öffentlichen Repos, und für die zwei privaten haben wir auch ein halbwegs okayes setup
