### ISSUE TITLE
Mailingliste umziehen

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#29]
als VM auf citizenfour

**Comment by hax404** [comment]
KVM-basiert oder lxc?

**Comment by else** [comment]
Mir egal. Vermutlich ist kvm einfacher wegen Umzug etc.

**Comment by hax404** [comment]
Ich kann den Umzug machen. Starten werde ich erst ~20.07.2016 wegen Klausuren.

# Vorbereitungen
Ich sehe auf premium aktuell die Listen
* Agenda (übernehmen)
* Anmeldung
* Announce - Veranstaltungshinweise vom RaumZeitLabor
* Camp2015 - Organisationsliste für das CCCamp2015 (nicht übernehmen?)
* Info - Mitteilungen und Pressekontakte (übernehmen/neu anlegen; falls Archiv existiert, dieses nicht übernehmen, weil Spam)
* Kinder - Announce ML für Veranstaltungen
* Mailman (wird automatisch neu angelegt; ignorieren)
* Maschinenraum (auch bekannt als netzwerk@; übernehmen; falls Archiv nicht existiert, Archiv nicht übernehmen)
* Orga - Liste zur Orgakommunikation für die Trollcon
* RaumZeitLabor (übernehmen inkl. Archiv)
* RZL - RZL Admin Liste
* Tor (nicht übernehmen)
* Vorstand (übernehmen inkl. Archiv)

Welche Listen, die nicht in Klammern „übernehmen“ haben, müssen noch übernommen werden?

# Schutzmaßnahmen gegen Spam (betrifft hauptsächlich info@)
* Greylisting
* SPF (?)
* DKIM (?)
* Spamassassin, der Emails ab 10 (?) Punkten verwirft. Könnte Emails von chinesischen Händlern betreffen

## Alternative Idee für info@
info@ wird ein IMAP-Postfach, dessen Zugangsdaten alle kennen, die diese Emails lesen wollen. Es wird einen eigenen Spamordner enthalten, wo per Sieve-Script alle möglichen Spam-Mails einsortiert werden. Weiterhin einen Ordner für nichterkannte Spam-Mails, mit denen der bayesische Filter trainiert wird.

## Alternative Idee2 für info@
Ihr kennt bestimmt, dass man mit einem + Emailadressen personalisieren kann. Ohne Mehraufwand könnte man also Emailadressen nach dem Schema info+$shopname@ verteilen, die alle im selben Postfach landen. Viele Webformulare erlauben ein + nicht in der Emailadresse. Postfix kann reguläre Ausdrücke in Aliasen. Der Aufbau einer solchen ist also beliebig. „verlohrengegangene“ Emailadressen, die nun zugespammt werden, können in einer einfachen Blackliste eingangsseitig abgewiesen werden.
Vorteil1: Es gehen keine Emails verlohren, da ein fälschlich abgewiesener Absender eine Fehlermeldung von seinem (!) Mailserver bekommt.
Vorteil2: Wir wissen, wer seine Datenbank an Spammer verliert/verkauft.
Nachteil1: Alle Kontakte, Shops, etc. müssen auf neue individuelle Adressen umgestellt werden. Das bedarf eines Parallelbetriebs über einen gewissen Zeitraum.
Nachteil2: Die Emailadresse im Impressum kann durchrotiert werden. Bei (bestehenden) Visitenkarten wird das schwieriger. 

Ich konnte bei meinem heimischen Setup durch die Mischung von Alternative Idee 1 und 2 mein Spamaufkommen gut minimieren. Gegen einen Catch-All spricht, dass bei mir eine menge Spammer versuchen, Emails an $beliebigerVorame.$beliebigerNachname@Domain abzuladen.

Meinungen?

**Comment by docsteel** [comment]
Aus welchem Grund genau die ML umziehen? Was spricht dagegen die auf premium laufen zu lassen?

**Comment by else** [comment]
Naja, Grund wäre, dass Premium weg kann. Es gibt momentan drölfzehn Server, davon läuft nur die Homepage und Wiki auf dem Root.

**Comment by docsteel** [comment]
Auf premium laufen nebenbei noch ein Haufen interner Dienste wenn ich das richtig sehe:
- BenutzerDB
- Partkeepr
- Status
- Ticketsystem
- Paste-Service
- ....

**Comment by hax404** [comment]
> * Paste-Service

von [dessen Existenz](https://paste.raumzeitlabor.de/) wusste ich überhaupt nichts.
Ich stimme @else zu, dass wir aktuell etwas viele Server haben. Meines Wissens wurde citizenfour gerade dafür angeschafft, um zu zentralisieren.
Den Rest von premium umzuziehen wäre dann was für einen anderen Thread.

**Comment by tabascoeye** [comment]
Jap. Wir zahlen immer noch alle diese Kisten. Und die Wiki seite von citizenfour sagt ja auch, dass er die anderen alle ersetzen soll.

zu den MLs:
* Orga@ - kann weg. Gibt keine Trollcon mehr
* Kinder@ -- watt?? an Ferrero verkaufen...
* Camp2015@ - kann weg
* announce@ -- funktioniert die automatisiert mit dem Kalender? Passiert da überhaupt was drauf? Im zweifel - kann weg

**Comment by uwap** [comment]
Gibt es da news zu?

**Comment by Ranlvor** [comment]
Die Mailingliste ist immernoch auf premium installiert, dieses Ticket schreibt von einem Umzug in eine KVM-VM auf citizenfour.

Dies ist bisher nicht geschehen und es ist mir unklar, ob wir das wollen. Aktuell haben wir durch premium/citizenfour eine Trennung in interne/externe Dienste, es ist mir nicht klar, ob wir diese Trennung beibehalten oder auflösen möchten.

Ich persönlich stehe neutral zu der Sache.

**Comment by docsteel** [comment]
Ich würde die Trennung in intern/extern gerne bestehen lassen und den issue hier schliessen da er inzwischen überholt ist.
