### ISSUE TITLE
Schubladen durchgehen und ggf. freigeben

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#3]
Schubladen von Ex-Mitgliedern, die schon länger nicht mehr da waren, könnten wieder freigegeben werden.

**Comment by Bfritz0815** [comment]
gerade mit (Unknown user) in Tardis2 Schubladen-Inventur gemacht. 
Liste:
0x70	komplett leer
0x71	unbeschriftet, Elektroteile
0x72	"Hugo"
0x73	Beschriftung "Netzteil"
0x74	Keine Beschriftung, Textilsachen
0x75	Beschriftung "Bauteile"
0x76	Beschriftung "Settop-Box" Stempel			Anm.: Schubladenhöhe justieren
0x77	Beschriftung "Magnetkarten"
0x78	Benutzer "Zero_dtime"
0x79	Beschriftung "Elektroinstallation"
0x7A	Beschriftung "Kaltgeräteverlängerung KVM PS/2
0x7B	Beschriftung "Adapter"
0x7C	Beschriftung "Türschließer"					Anm.: Schublade schwergängig
0x7D	Beschriftung/Benutzer "Plankins"
0x7E	Benutzer "Naddie"							Anm.: Schublade schwergängig
0x7F	Beschriftung "Textilmaterial
0x7G	Beschriftung "Textilmaterial"				Anm.: Schublade schwergängig
0x80	leer
0x81	Beschriftung/Benutzer "Sylvester
0x82	Benutzer "JensWilmer"
0x83	Beschriftung "Holzlager						Anm.: Frage, Auslagerung in Werkstatt
0x84	Beschriftung "RainbowDash", Inhalt Mobilé-Teile		Anm.: public
0x85	Beschriftung "Bausatz-Storage BS0001 Partkeepr benutzen!"
0x86	Beschriftung "Bausatz-Storage BS0002 Partkeepr benutzen!"		Anm. Front nachjustieren
0x87	Beschriftung "Bausatz-Storage BS0003 Partkeepr benutzen!"
0x88	Beschriftung "Bausatz-Storage BS0004 Partkeepr benutzen!"
0x89	Beschriftung "Kartendrucker"				Anm. Front justieren, Frage zusammenlegen mit 0x77
0x8A	Eigentümer "SDR HackRF", Frage Besitzer/Mitglied? Frage, Schublade fast leer, umschichten?
0x8B	Eigentümer "Fnordcordia"
0x8C	Keine Beschriftun, Inhalt: Bauteile, Kunststoffplatten		Frage: Bauteile im Partkeepr? Beschriftung dazu? Kunststoff in die Werkstatt oder wegschmeißen?		Anm.: Schublade federt komisch
0x8D	Beschriftung "Agenda Diplom"
0x8E	Beschriftung "Stickrahmen"
0x8F	Beschriftung "Stickrahmen"
0x8G	Beschriftung "Felty", Inhalt: Filz (Textilverarbeitung), Frage? Public? Kosten?
0x90	Beschriftung/Benutzer "Alexander"
0x91	Beschriftung "Glasfasermatten
0x92	keine Beschriftung, Inhalt: Trollcon-Reste, Blechschneide-Ausrüstung, Frage: Blechschneide -> DaFo
0x93	Beschriftung "Holz-Reste", Aufgabe: Ausmisten?
0x94	Beschriftung "RainbowDash", Inhalt: Holzteile Maustüröffner-Tage, Frage: Zusammenlegen mit 0x84?
0x95	Beschriftung "Bausatz-Storage Partkeepr BS0005 benutzen!"
0x96	Beschriftung "Bausatz-Storage Partkeepr BS0006 benutzen!"
0x97	Beschriftung "Bausatz-Storage Partkeepr BS0007 benutzen!"
0x98	Beschriftung "Bausatz-Storage Partkeepr BS0008 benutzen!"
0x99	Beschrfitung "19 Zoll Hardware DaFo/Felicitus"
0x9A	Beschriftung "Mechanische Bauteile", Inhalt: Verschiedene Schaniere und Schrauben
0x9B	Beschriftung "Bohrer", Inhalt: Wenige Zentrierbohrer, Frage: Umräumen?
0x9C	Beschriftung "MRMCD", Frage: Ausmisten?
0x9D	Beschriftung "Sticken"
0x9E	Beschriftung "Stickbeispiele"
0x9F	Beschriftung "Stickvlies"
0x96	Beschriftung "Stoff", Frage: Alte MRMCD-Sachen ausmisten?
0xA0	Benutzer "Deramon"
0xA1	keine Beschriftung, Inhalt: Diverse Farben, Frage: Zweck? Noch nötig?
0xA2	Beschriftung "Kinderfarben"
0xA3	Beschriftung "Pinsel und Farben"
0xA4	Beschriftung "Fräse"
0xA5	Beschriftung "Bausatz-Storage BS0009..."
0xA6	Beschriftung "Bausatz-Storage BS0010..."
0xA7	Beschriftung "Bausatz-Storage BS0011"
0xA8	Beschriftung "Bausatz-Storage BS0012"
0xA9	Beschriftung "Türöffner-Tag"
0xAA	Beschriftung "Schneidplotter"
0xAB	Beschriftung "Ultimaker (PLA)"
0xAC	Beschriftung "Ultimaker"		Anm. Label kaum lesbar
0xAD	Beschriftung "Sticken"
0xAE	Beschriftung "StickProtect, Untergarn, Nadeln (Hucqvarna)
0xAF	Beschriftung "Textil: Sollwied, Thermofix"
0xAG	Beschriftung "Tardis-Zubehör", Aufgabe: Hälfte der Plastikteile wegschmeißen

**Comment by Bfritz0815** [comment]
habe die Reparaturen und einzelnen Arbeiten an tardis 2 in ein Ticket gegeben: https://github.com/raumzeitlabor/rzl-tuwat/issues/37

**Comment by Bfritz0815** [comment]
0x1F ist leer

**Comment by s1lvester** [comment]
Haben einzelne issues von @Bfritz0815 bekommen.
