### ISSUE TITLE
Kasse auf Strichliste.org umstellen 

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#30]
Die jetzige funktioniert zwar und ist von @silsha, aber ist echt anstrengend zu bedienen.

**Comment by steeph-k** [comment]
Die Hauptunterschiede, die ich zum aktuellen System sehe, sind, dass die aktiven Nutzer oben gelistet werden und dass man auch beliebige Beträge eingeben kann. In der Tat eine kleine Verbesserung. Aber mich stört auch das jetzige System nicht.

In dem Zusammenhang gibt es auch ein paar Wiki-Seiten, die mal aktuelisiert werden könnten:
https://wiki.raumzeitlabor.de/wiki/Guthabensystem
https://wiki.raumzeitlabor.de/wiki/Kasse
https://wiki.raumzeitlabor.de/wiki/Kassensystem
https://wiki.raumzeitlabor.de/wiki/Getr%C3%A4nkeautomat

**Comment by uwap** [comment]
Also ich mag das aktuelle System ja und der code sieht sauber genug aus, um relativ schnell sowas wie "Add Custom Amount of Money" einzubauen. Ich sehe auch nicht, wo fnordcredit ansonsten anstrengend zu bedienen sein soll.

**Comment by else** [comment]
@silsha hat es auf cashdesk.rzl installiert.

zu erledigen:
* [ ] Konvertierung
* [ ] Backup

**Comment by else** [comment]
Zwischenstand: jetzt haben wir beides :joy:, @silsha, was ist der Plan?

**Comment by uwap** [comment]
Ich möchte mich noch ein mal gegen das Umstellen auf ein anderes System aussprechen. Strichliste hat z.B. keine Möglichkeit Benutzer alphabetisch zu sortieren und auch sonst sehe ich mit Strichliste eher Nachteile als Vorteile.

**Comment by else** [comment]
Fnordcredit ist nicht mehr maintained: https://github.com/silsha/fnordcredit
strichliste ist maintained, sogar von > 1 Person.

**Comment by uwap** [comment]
Also ich seh da bei fnordcredit zumindest im entropia fork den letzten commit vor 13 tagen...

**Comment by Bfritz0815** [comment]
So wie ich das jetzt verstehe, sind beide derzeit in productive. Oder?
Die derzeitige Strichliste ist also nicht in einem test-run und wer auch immer "herpderp" ist, hat entweder deutlich zuviel Kohle oder isn troll.

**Comment by silsha** [comment]
Die aktuelle Strichlisteninstallation ist im test-run und ich weiß nicht, warum Leute angefangen haben, sie zu benutzen. :cat: 

Jedenfalls gibt es einen Migrator, welcher eine frische Installation voraussetzt: https://github.com/schinken/fnordcredit2strichliste

Die nächsten Schritte wären also:
- [ ] Aktuelle Strichlistennutzer notieren
- [ ] Strichliste nochmal sauber installieren
- [ ] Migration durchführen
- [ ] Early adopters manuell migrieren
- [ ] :euro: Profit :moneybag:

**Comment by silsha** [comment]
@maikf Was ist da der aktuelle Stand? 🐱 Hast du die Migration zum laufen gebracht?

**Comment by silsha** [comment]
Nachdem ein Upgradeversuch gescheitert ist, waren @y0cky und ich gezwungen fnordcredit auf strichliste umzustellen. Alle Account mit Guthaben oder Schulden wurden übernommen. Alle leeren Konten nicht.

Neue IP ist cashdesk.rzl:8081

![image](https://cloud.githubusercontent.com/assets/31850/23967790/935df7c8-09c0-11e7-9652-82f26ae0b200.png)
