### ISSUE TITLE
Batterien abholen lassen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#32]
Altbatterien werden seit neustem erst ab drei Kisten abgeholt. Ich habe noch eine Kiste bestellt und lasse sie abholen, sobald sie voll sind.

**Comment by s1lvester** [comment]
Ist erledigt, oder? zumindest stehen keine batterien mehr am Eingang.

**Comment by silsha** [comment]
Ich weiß es ehrlich gesagt nicht. @maikf meinte letztens, da war jemand da. Hat der auch die Batterien abgeholt?

**Comment by maikf** [comment]
Hat er.
