### ISSUE TITLE
Fernseher im Textillager

### ISSUE THREAD

**Issue by Don42** [raumzeitlabor/rzl-tuwat#33]
Im Textillager steht ein alter Fernseher der laut Aufkleber @felicitus gehört. 
War wohl für das MAME Projekt. Läuft das noch? Wird der abgeholt?

**Comment by felicitus** [comment]
Negativ, keine Zeit dazu. Könnte verschrottet werden, außer jemand anderes findet sich für das MAME-Projekt.

**Comment by slowpoketail** [comment]
Ich wäre für wegtun; 'nen Fernseher lässt sich im Zweifel immer noch wieder auftreiben, wenn das irgendwann mal weitergebaut werden sollte.

**Comment by Bfritz0815** [comment]
ist bei Schrott

**Comment by abrock** [comment]
Ist inzwischen weg.
