### ISSUE TITLE
Kiste Pinpad

### ISSUE THREAD

**Issue by Don42** [raumzeitlabor/rzl-tuwat#34]
Im Textillager befand sich eine Kiste mit dem Label "Pinpad". Diese enthielt Elektronik und einen Maschinentelegraph. Wird diese Kiste und/oder der Inhalt noch benötigt benötigt?
@abrock

**Comment by else** [comment]
Foto?

**Comment by abrock** [comment]
Ich werde die Kiste am Dienstag sichten und den Inhalt entsorgen / wegräumen. Wo steht sie?

**Comment by steeph-k** [comment]
Die Kiste steht vorne auf dem Konferenztisch, ungefähr auf Eingangshöhe.

**Comment by yocky96** [comment]
![1](https://cloud.githubusercontent.com/assets/1353163/11212708/a60aced4-8d37-11e5-8012-7305453c5398.jpg)
![2](https://cloud.githubusercontent.com/assets/1353163/11212707/a6076a32-8d37-11e5-9f3e-2c9bae576ce0.jpg)

**Comment by tabascoeye** [comment]
status?

**Comment by abrock** [comment]
> status?

Keine Ahnung wo die Kiste ist.

**Comment by silsha** [comment]
Ich schätze, damit hat sich das Problem von selbst gelöst. :3
