### ISSUE TITLE
T-Shirt Presse verkaufen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#35]
Auf der gelben T-Shirt-Presse klebt ein Zettel mit „soll verkauft werden“ drauf.

Wenn niemand was dagegen oder andere Pläne hat, würde ich die auf eBay stellen und den Gewinn dem Verein überweisen.

**Comment by abrock** [comment]
Es ist schon mit Entropia vereinbart, dass die die für 150€ kaufen.

**Comment by silsha** [comment]
Ah, okay. Ist da schon der Transport geklärt?

**Comment by abrock** [comment]
Wurde auf dem Kongress an Entropia übergeben und bar bezahlt.
