### ISSUE TITLE
Arbeitsplätze auf dem Olymp

### ISSUE THREAD

**Issue by maikf** [raumzeitlabor/rzl-tuwat#36]
Ingo und ich haben zwei Tische, die übrig waren auf den Olymp gestellt,
anstelle zwei der drei Regale, die als Tische missbraucht wurden.

Es fehlt noch der "Leuchtstoffröhrenreflektor" der selbige beleuchtet.
Dieser befindet sich schon auf dem Olymp, unter dem Chaos, weiter rechts.

**Comment by steeph-k** [comment]
Klingt gut. Vielleicht können die Regalstücke an der freien Stelle im Getränkelager untergebracht werden.

An den Arbeutsplätzen waren eigentlich Schreibtischlampen. Reichen die nicht aus?

**Comment by s1lvester** [comment]
Beide "Arbeitsplätze" funktionieren.
