### ISSUE TITLE
Die Tür im Herren-WC ist extrem schlecht montiert. Vermieter kontaktieren

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#38]
Die Tür im Herren WC ist so schlecht montiert, dass man sie kaum aufbekommt. 
Bitte kontaktiere den Vermieter und bewege ihn dazu, Abhilfe zu schaffen. 

Was ist denn so falsch an einer Tür ohne Klinke? In einem WC sollte man sowieso keine Türklinken anfassen müssen...

**Comment by abrock** [comment]
Tür war abgeschlossen, ist jetzt wieder aufgeschlossen. In solchen Fällen einfach eine E-Mail an Robert schicken mit CC: info@raumzeitlabor.de und Reply-To: info@raumzeitlabor.de
