### ISSUE TITLE
Infoscreen reparieren

### ISSUE THREAD

**Issue by s1lvester** [raumzeitlabor/rzl-tuwat#39]
Beim Mariocartturnier flog durch die Slushmaschienen der FI raus. Seither geht der Infoscreen nicht mehr.

Ausführliche Diagnostik hat ergeben:

1. am RPI ist der HDMI-Port kaputt
2. am Monitor scheint der digitale Eingang (DVI) ebenfalls abgebrannt zu sein. Analog über VGA geht der Monitor noch.

Lösung(-svorschläge):
RPI mit dem am Ultimaker getauscht, da der kein Display benötigt.
Hab dem Pi eine neue SD-Karte spendiert, da die alte wohl auch abgeraucht war.

TODO:

- [ ] MAC-Adressen für ultimaker.rzl mit dem infoscreen.rzl tauschen

- [x] Kiosk mode auf dem infoscreen einrichten

**Comment by s1lvester** [comment]
Infoscreen-raspbian ist neu aufgesetzt.
Beim nächsten mal geht's dann etwas schneller: https://github.com/raumzeitlabor/kiosk-browser

**Comment by tabascoeye** [comment]
mag jemand noch den @Cheatha darüber in Kenntnis setzen? Das ist afaik sein Monitor, der da an der Ebene hängt...

**Comment by Don42** [comment]
Ist weitergeleitet. Unklar wann er das ließt.

**Comment by Cheatha** [comment]
Der Monitor macht irgendwas über Full-HD, was der Pi nur macht, wenn man irgendeinen speziellen Display-mode in der config.txt auf der SD-Karte direkt änderte. Vielleicht liegt es daran?

**Comment by Cheatha** [comment]
Für »Pi über VGA anschließen« braucht man übrigens einen aktiven Konverter, die Bildqualität wird bei 1920x1200 ebenfalls eher mau sein. Also entweder HDMI-auf-display-port oder mal den Monitor aufmachen und schauen, ob man da was fixen kann. Ansonsten kostet ein 27"-monitor mit ner 2560er Auflösung wohl unter 600€. Mehr Platz (in Pixeln) wäre sowieso nicht schlecht. Ob der Pi allerdings so ne Auflösung hinbekommt, weiß ich nicht.

**Comment by s1lvester** [comment]
Also auch mit 

` hdmi_group=2
hdmi_mode=68`

in der config.txt macht der monitor keinen mux über DVI. Hat jemand ein Displayport-Kabel rumliegen und kann mal den Eingang testen?

**Comment by Cheatha** [comment]
Der Monitor lies sich digital auch mit anderen Rechnern und Kabeln nicht wiederbeleben. Ich habe ihn zerlegt, konnte aber optisch keine durchgeschmoren ICs, Leitungen, etc feststellen. Wäre cool, wenn jemand, der was von Elektronik versteht, mal das Gerät anschauen kann. Es liegt in der E-Ecke auf dem linken Rollcontainer.

**Comment by s1lvester** [comment]
#44 

Einiges ist geklärt und der noch größere Infoscreen funktioniert. Fehlt noch das Umbiegen der static dhcp leases.

**Comment by Cheatha** [comment]
Die native Auflösung des Screens ist 2560x1600. Prinzipiell scheint der Raspberry Pi das zu können, wahrscheinlich muss man aber mindestens ein HDMI-Kabel dafür verwenden. Aktuell hängt ein HDMI-DVI-Kabel dran.

**Comment by s1lvester** [comment]
@Cheatha: Ich glaube es macht keinen Unterschied wie hoch die Displayauflösung ist so lange der komplette Inhalt der Website dargestellt wird, oder täusche ich mich da?

**Comment by tabascoeye** [comment]
naja wenn da ruminterpoliert wird, sieht u.a. Schrift halt scheisse bis unlesbar aus.
Und: Mehr Pixel == mehr potenzielleer Inhalt für InfoScreen-ng

**Comment by steeph-k** [comment]
Das ist erledigt, oder?

**Comment by Bfritz0815** [comment]
@steeph-k  sollte so sein. ich schließ das mal

**Comment by abrock** [comment]
@Bfritz0815 
Ich habe dir mal Eigentümer-Rechte für die Organisation RaumZeitLabor gegeben, jetzt solltest du auch fremde Issues schließen können.
