### ISSUE TITLE
Die Lampen vor dem RZL funktionieren nicht

### ISSUE THREAD

**Issue by abrock** [raumzeitlabor/rzl-tuwat#42]
Jemand müsste mal dem Vermieter Bescheid sagen, damit der das repariert.

**Comment by abrock** [comment]
Ich habe da mal eine E-Mail geschrieben.

**Comment by lutoma** [comment]
Die Neonröhren im Gang vor dem RZL wurden gerade von einem Kübler-Mitarbeiter ausgetauscht & das Licht funktioniert wieder.
