### ISSUE TITLE
Privatsachen aus Format-and-reinstall-2015 zum Abholen

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#43]
And er Tafel stehen noch reichlich Sachen. Daher hier mal ne Liste der Sachen, ne Liste der Besitzer  bzw. Checkliste, welche Besitzer schon jemand verständigt hat:

## Owner

- [ ] DaFo
- [x] Don @Don42 
- [x] Echox @echox 
- [ ] Kisl
- [ ] Nicoduck @nicoduck 
- [ ] Moemoe
- [ ] Probot
- [ ] RZL
- [ ] Slowpoke @slowpoketail @proxypoke 
- [ ] Tiefpunkt @tiefpunkt 
- [ ] Zwetschgo

## Sachen

- [x] **DaFo** 1 Pappkiste (40x60 cm), 1 10x10cm Kiste und ein Motor (o.A.)
- [ ] **DaFo** kleine Ikea-Kiste: 'für Dafo' mit u.A. Atari-Anleitung
- [ ] **DaFo** kleine Ikea-Kiste: mit Telefonen
- [ ] **DaFo** kleine Ikea-Kiste: mit switche, patchkabel, Handbuch fuer den Ettikettendrucker
- [ ] **DaFo** Sammlung auf den Arbeitsplätzen in der Ä-Ecke (sind nur nicht physisch unter der Tafel, damit das Sortieren und Verpacken leichter fällt)
- [x] **Don** @Don42  Schlafsack
- [x] **Echox** @echox  Airbrush-Set mit Pistole und Kompressor
- [ ] **Echox** @echox  IKEA Kiste mit Farben
- [x] **Echox** @echox  Stofftasche mit Lego (falls nicht echox's bitte comment unten)
- [ ] **Kisl** "Spieleautomat"
- [ ] **Nicoduck** @nicoduck  1leere Kiste "Astaro Internet security"
- [ ] **Moemoe** 1 Memberkiste mit Beschriftung "Bitte anschreiben"
- [ ] **Probot**: 1 IKEA-Kiste mit Privatzeug
- [ ] **RZL** Laminierfolien, Bondrucker-Papierrollen, Buntstifte, Luftballons. **Vereinszeug?**
- [ ] **RZL** "RZL-Aufkleber, Pron-wall" **Wer weiss, wessen und wohin, bitte aufräumen.**
- [ ] **RZL** Ersatzlampe für den alten Beamer "Davis 450 und 650": Funzt die noch? Kann jemand die für den Verein auf Ebay verticken?
- [ ] **RZL** USB-Dosen Küklschrank: Soll der weg? Herschenken? Ver-ebayen?
- [ ] **RZL** Stofftasche mit Lego (war nicht echox's)
- [x] **Slowpoke** Gitarre
- [ ] **Slowpoke** Kiste mit Knex (gehörend a auch noch die anderen Kisten im Textillager dazu?) @slowpoketail @proxypoke 
- [ ] **Tiefpunkt** @tiefpunkt  Tiefpunkts Kiste
- [ ] **Zwetschgo** Box "Spiele-Kalssiker"

**Comment by echox** [comment]
(falls nicht echox's bitte comment unten)
Keine Ahnung warum mir ne Stofftasche mit Lego gehoeren soll.

**Comment by echox** [comment]
Hi,

ich vermisse die "Ikea Kiste mit Farben".
Wo finde ich die?

Enthalten war unter anderem ein komplettes Grundfarben Set von Schmincke 
in Pipettenflaschen.

Viele Gruesse,
Simon

**Comment by Bfritz0815** [comment]
Ich hab zwar nichtmehr im Kopf wie die genau aussah, aber wenn ich die gelistet habe, dann war sie vor 2 Tagen an der Tafel gestanden. Fakt ist: Jetzt ist sie nicht mehr da. Hat wohl Beine bekommen. 

**Frage: Wer weiss, wo die hin ist?**

wg.:
> ich vermisse die "Ikea Kiste mit Farben".
> Wo finde ich die?
> Enthalten war unter anderem ein komplettes Grundfarben Set von Schmincke in Pipettenflaschen.
> Viele Gruesse, Simon

**Comment by echox** [comment]
Fakt ist, ich will die wieder haben...

**Comment by Bfritz0815** [comment]
@blabber Bitte um fire-support: Einige der Leute in der Liste sind noch nicht kontaktiert. Der Vorstand müsste doch deren Anschriften haben. Frage: Kannste die mit link anmailen, dass sie ihrn Kram bitte abholen? Gerade so Leute wie "Moemoe" oder "Probot" könnte ich jetzt nicht kontakten. Danke.

**Comment by steeph-k** [comment]
Ich weiß nicht, was der oben gelisteten Dinge erledigt wurde. Aber mir ist aufgefallen, dass der Kramshaufen nicht mehr da ist. Kann man das Isse also schließen?

**Comment by Bfritz0815** [comment]
@steeph-k  Sollte jemand sich um den Kram gekümmert haben, würde ich das schließen. 
Allerdings glaube ich das erst, wenn ich's mit eigenen Augen gesehen habe. (Also dass die Sachen weg sind, nicht etwa irgendwo zur Seite geschoben oder so)
Wenn ich wieder drin bin, kann ich ja mal schaun... (Vorraussichtlich am Do wg. Feiertag)

**Comment by steeph-k** [comment]
OK, hab' mich geirrt. Es stehen noch ein paar Sachen da und es ist ist sogar was dazu gekommen. Aber insgesamt ist es deutlich weniger geworden. Ich werde demnächst mal versuchen, die Besitzer der übrigen Sachen zu erreichen. Mengenmäßig dürfte das meiste immer noch @Don42 gehören.

**Comment by Bfritz0815** [comment]
Das Meiste is weg. Ich schliess das jetzt. Bis zur nächsten Instanz in ~ 6 Monaten ;)

**Comment by steeph-k** [comment]
Naja, die Sachen sind beim Aufräumen fürs Agenda-Diplom wohl ins Getränkelager gewandert. Sie stehen. Weniger im Weg, aber immer noch rum.
