### ISSUE TITLE
Auflösungs-Einstellungen am RasPi vom Status-Screen ändern

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#44]
Für den Statusscreen gibts nen neuen, größeren Bildschirm. Die Darstellungsprobleme dort kommen evtl. von den Einstellungen dazu am RasPi. 
Kennt sich da jemand hinreichend aus um das zu fixen?

**Comment by s1lvester** [comment]
done.
