### ISSUE TITLE
Olymp-Labeln

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#45]
Bitte labelt **alle** Dinge auf dem Olymp. Im [(heutigen Plenum)](https://wiki.raumzeitlabor.de/wiki/20160306_-_Plenum) wurde beschlossen im Mai alles wegzuschmeissen, was ungelabelt aufm Olymp rumfliegt. 

For your convenience hab ich Aufkleber, Post-its, Edings und Duct-Tape auf den Arbeitstich am Krchbumm-Labor gestellt. 

@slowpoketail 
@proxypoke 
@maikf 

Bitte informiert auch möglichst viele andere Olymp-Nutzer. Danke.

**Comment by uwap** [comment]
Wie ist der aktuelle Stand? Wir haben Mai. Sollte noch mal eine Erinnerung auf die ML gepostet werden?

**Comment by Bfritz0815** [comment]
Es hat sich inzwischen insofern was getan, als dass das Krachbumm-Labor aufgeräumt wurde und die 2 PC-Plätze frei sind. Auch die Konsolen-Ecke ist besser geworden. 

Es fliegt immer noch ne Menge Sch... rum aber die vorherige Situation, dass der ganze Olymp eine Privat-Schrottsammlung war, ist nun erstmal rum. Alles Weitere sollte sich mit etwas nagging schon selbst regeln.
