### ISSUE TITLE
Olymp F&R

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#46]
Wurde aufm [(heutigen Plenum)](https://wiki.raumzeitlabor.de/wiki/20160306_-_Plenum) nachgefragt. 
- [x] Buchscanner ins HochRegal
- [x] Slowpokes Gitarre zum Abholen bereit stellen
- [ ] Alles Labeln! https://github.com/raumzeitlabor/rzl-tuwat/issues/45
- [ ] Leuchtstoff-Röhre (wird die kommenden 2 Wochen angeschlossen)
- [x] Arbeitstische benutzbar (frei+feste stromversorgung) machen
- [x] einzelne Schreibtisch-Lampen für die Arbeitstische besorgen
- [x] Hängematten wenn überhaupt so aufhängen, dass sie nicht die Arbeitstische behindern
- [x] Wo ist Stauraum für die Hängematten, wenn sie nicht im Gebrauch sind?

@slowpoketail 
@proxypoke 
@maikf

**Comment by lutoma** [comment]
Bezüglich Hängematten scheint aktuell der Modus Operandi zu sein, sie nach der Benutzung abzuhängen. Noch schöner wäre natürlich ein Ort an dem sie dauerhaft hängen könnten, aber dafür müsste man erstmal einen passenden Ort finden und dann Halterungen anbringen.

**Comment by steeph-k** [comment]
Schreibtischlampen hatte ich hingestellt. Wie kann man hier etwas abhaken?

Stauraum für die Hängematten ist im Hochregallager. Wenn sie gar nicht mehr gebraucht würden dann sicherlich auch außerhalb des RZL.

**Comment by Bfritz0815** [comment]
@steeph-k leider kann das jeweils nur der author der issue.

Was die Verstauung der Hängematten im Hochregal betrifft: Dass jemand die Teile regelmäßig vom Slackspace aus sagenhafte 10-20 meter weit durch den Raum trägt um sie ins Hochregallager zu bringen, das glaube ich erst, wenn ich sehe, wie das einer macht. (ohne über fliegende Schweine zu stolpern, versteht sich)

Eine (möglichst luftige) Kiste oder so aufm Olymp wäe da IMHO die realistischere Variante. (Wäschepuff anyone?)

**Comment by Bfritz0815** [comment]
da das mit der Leuchtstoffröhre zwar noch offen aber nicht mehr dringend ist und die Label-Task eh separat ist, schliesse ich das hier jetzt.
