### ISSUE TITLE
Metro-Einkäufe und die Metro-Karte Defrag

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#48]
Hallo,
Sache ist die:
1. Für nen Metro Ek braucht man ne Metro Karte
2. Die hat nicht jeder
3. Auf unseren Verein laufen wohl 5 von 5 möglichen karten
4. Seltsamerweise sind die Kartenhalter selten greifbar, wenn ein Ek ansteht. e.g. seit min. 2 Wochen wäre ein Ek nötig. Er kommt jedoch nicht zustande

Daher hab ich folgende Fragen:
- [ ] Wer hat ne RZL-Metro-Karte auf seinen namen laufen?
- [ ] Wer ist so selten hier, dass es keinen Sinn mehr macht, dass er/sie eine hat? (i.e. wer kann seine abgeben?)
- [x] Wer hat derzeit keine metrokarte, hat aber ein halbwegs geräumiges Auto und Interesse ein RZL-Metro-Engel zu werden?

hat jemand noch Andere Ideen dazu?

**Comment by steeph-k** [comment]
Ich würde Metro-Engel werden. Etwa mit der gleichen Zuverlässigkeit wie mit dem Schrott-Entsorgen. (Es wird also meistens ein paar Tage dauern, bis es bei mir passt. Also frühe Info hilft, wenn mir selbst nicht auffällt, was fehlt.) Das Auto wäre ein Kangoo, was größeres nach Anfrage.

**Comment by s1lvester** [comment]
Als Metro-Engel mit Auto könnte ich mich auch mit entsprechender Vorlaufzeit von einem Tag oder so zur Verfügung stellen.

**Comment by tabascoeye** [comment]
Also so weit ich weiß hat aus dem derzeitigen Vorstand keiner eine Metrokarte die auf RZL läuft...

**Comment by lutoma** [comment]
Ich hätte eine Metro-Karte, die ich gerne zur Verfügung stellen kann. Sollte aber auch problemlos möglich sein, das für das RZL zu machen, ist halt ein bisschen Papierkram bei der ersten Karte, zusätzliche gehen dann schnell. Allerdings fangen sie ab etwa ~7 Karten auf einen Firmen-/Vereinsnamen an etwas rumzumosern.

**Comment by lutoma** [comment]
Man könnte auch einfach eine der Metrokarten im RZL deponieren. Ggf mit entsprechender Vollmacht falls sie tatsächlich mal aufs Bild schauen, aber machen sie eh nie.

**Comment by steeph-k** [comment]
Weiß mittlerweile jemand etwas zum Verbleib der Karten? Wenn nicht sollten wir wohl einfach neue beantragen.

**Comment by s1lvester** [comment]
Ping? Getränke sind leer.

**Comment by s1lvester** [comment]
@98

**Comment by Bfritz0815** [comment]
Aktuell läuft ne Serie von Events und der Kiosk ist seit ner Weile effektiv leer.
Also hier mal ein paar Items um das Thema mal wieder ins Rollen zu bringen: 

1. Laut Metro-Seite kann ein Verein auch Einkaufsberechtigungen per Online-Account managen. Das wäre glaubich auch fürs RZL praktischer als per PDF-Download + Papierkram. https://www.metro.de/meine-branche/vereine/als-verein-kunde-werden  @tabascoeye hat der Vorstand Zugang zu dem Account? (bzw. legt der Vorstand einen Account neu an?)
2. Hat jemand ne Liste, wer ne Metro-Karte auf den Verein hat? (falls nicht: Wie kommen wir an die Info?) Die meisten RZL-Metro-Karten-Inhaber scheinen ja aktuell unterm Radar zu fliegen.
3. Wer hat für die letzten ca. 5-6 Metro-Gänge die Karte beigesteuert? (und war es eine Vereins-Karte oder eine von einer anderen  Organisation? e.g. Firma)
4. @abrock ich glaub mich düster erinnern zu können, dass mir mal gesagt wurde, ein Herr Brock hätte eine Metro-Karte. Frage: Stimmt das? Folgefrage: Falls Ja, kommst du aktuell noch dazu, die zu benutzen?
5. @steeph-k @s1lvester  Frage: involviert deine Freiwillig-Meldung als Engel auch das Vorschießen der Kohle bis zur Rückerstattung? (Kosten liegen i.d.R. im 3-Stelligen Bereich. )

Aktueller Freiwilligen-Stand:
- Steeph: Auto (und Vorschießen?)
- s1lvester: Auto (und Vorschießen?)
- Bfritz0815: Geld Vorschießen (hat **kein** Auto)

@steeph-k Das Problem ist, dass ich mal vor ca 3 Jahren versucht habe, eine für den Verein auf meinen Namen zu bekommen. Ich hatte den nötigen Papierkram dabei. Dort vor Ort sagte man mir, es könnten maximal 5 Personen eine Vereins-Metrokarte haben und unser Verein habe bereits 5 eingetragen. "Einfach mal eine beantragen" geht also in die Kategorie "tried and failed"...

**Comment by s1lvester** [comment]
Ja Engeln kann ich. Auch monetär. Hab gerade auch etwas Zeit. Aber geht nicht auf 5 min Zuruf sondern eher mit Vorlauf von einem Tag.

In dem anderen Issue kam ja nie raus wer genau jetzt ne Karte hat, oder?

**Comment by abrock** [comment]
Ich habe Metrokarte, Auto und Geld aber keine Ahnung was und wie viel davon ich kaufen soll. Wenn jemand mit Ahnung heute mit mir in die Metro fahren will bitte melden.

**Comment by Bfritz0815** [comment]
@abrock Ich melde mich dann grade mal. Ich compile mal eine liste...

**Comment by Bfritz0815** [comment]
alte Liste ist hier:
https://wiki.raumzeitlabor.de/wiki/Einkaufsliste_Snackbar

https://docs.google.com/spreadsheets/d/1hQLwVAsRVv5Udjg-GUTq1-_vNMG17FgwshTNfySFF6w/edit#gid=0

**Comment by steeph-k** [comment]
Ich teile mir mittlerweile ein Auto mit anderen und könnte, wenn ich es habe, fast nur noch an Wochenenden einkaufen fahren. Aber Geld vorschießen wäre kein Problem.

**Comment by uwap** [comment]
@tabascoeye @flederrattie @blabber Wie ist der aktuelle Stand bezüglich Metro Karten die auf das RZL laufen? Ich wäre für den Vorschlag von @lutoma eine oder zwei Metrokarten im RZL zu deponieren

**Comment by tabascoeye** [comment]
Da ich noch nie eine RZL Metro-Karte gesehen habe, weiß ich nicht was ich bei
https://www.metro.de/my-metro/account-registration
eintragen müsste, um überhaupt einen account zu klicken.

==> Wenn nicht langsam mal geklärt wird, ob überhaupt irgendjemand noch eine aktive RZL Metro Karte besitzt, müssen wir da mal hinfahren und denen sagen, sie sollen einen cold reset machen.
Dann hole erstmal nur ich mir eine Karte und klicke mir so einen Zugang.

- [ ] Mindestens ein Mitglied mit RZL karte meldet sich bei mir (PN!) und sagt mir die nummer

**Comment by tabascoeye** [comment]
@flederrattie hat ein Kündigungsschreiben für die Karten. Wir wissen nur nicht, wann wir das nächste mal in der Metro vorbeikommen.
Dann können wir neue Karten beantragen

**Comment by tabascoeye** [comment]
RZL METRO-Karten wurden defragmentiert.
Aktuelle haben nur @flederrattie und ich jeweils eine.
Es gibt keine nicht-personenbezogenen Karten, auch nicht für Vereine. 
Wir können noch weitere beantragen, sinnvollerweise von Leuten, die auch wirklich öfter zur METRO gehen und noch keine eigene Karte haben.

**Comment by abrock** [comment]
Heißt das alle anderen Karten wurden deaktiviert?

**Comment by tabascoeye** [comment]
Ja. Ob das jemanden in der Metro interessiert weiß ich aber nicht ;o)
