### ISSUE TITLE
Antoß Filmabend

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#49]
Hab mal die Satzung geschmökert. Da steht was von "Vorführung von Filmen"...

Wie wärs also mit nem regelmäßigen Filmabend. 

Vorschlag: Donnerstag 19:00 +

Was geschaut wird, kann man ja erstmal kurzfristig provisorisch vor Ort an dem Tag aushandeln. Strukturieren können wir das ja später immer noch, falls es funktioniert. 

Vorläufige Ideen wären:

- C3 Videos
- Making-of-Videos von games, movies etc.
- diverse Konferenz-Videos
- ...

**Comment by Bfritz0815** [comment]
BTW: habe für heute dabei: 
Das Making-of von Civilization3 (EN)
- Iterative development
- lessons-learned
- discarded game concepts

**Comment by Don42** [comment]
FInde ich eine gute Idee. Wollte ich selbst mal wieder anstoßen.
Habe da eine rechte große Playlist an Konferenztalks.

**Comment by JannF** [comment]
Ich kann frisch geschnittene Talks von der Troopers 16 anbieten wenn Interesse besteht.

**Comment by Bfritz0815** [comment]
@Don42 @JannF cool. listet doch mal sowas wie Titel und ggf. link für die interessantesten Movies im Ppad: https://piratenpad.de/p/bUB0TyvT6v6eNKOpq7JW
Dannn können auch andere sehen, was für Möglichkeiten vorliegen. 
Ne Entscheidung, was genau wir schaun, könne wir dann ggf. vor Ort abstimmen aber ich glaub, dass es bessere resonanz gibt, wenn man als Interesent im Vorfeld ungefähr ne Idee kriegt, worauf man sich da einlässt.

**Comment by Don42** [comment]
@JannF An den Troopers Talks hätte ich Interesse.

**Comment by JannF** [comment]
Ich werde die Talks auch Dienstag - Freitag auf den Offiziellen Kanal auf YT hochgeladen haben, die findet man dann hier:
https://www.youtube.com/user/TROOPERScon

**Comment by blabber** [comment]
Den Versuch den donnerstäglichen Videoabend zu reanimieren finde ich gut. Viel Glück. Ich habe das mal einezeitlang konsequent durchgezogen (https://wiki.raumzeitlabor.de/wiki/Chaotic_Congress_Cinema_Mannheim) aber die Reaktionen waren eher verhalten.

**Comment by silsha** [comment]
Scheint inzwischen donnerstags stattzufinden. Ich schließ das mal. 🐺
