### ISSUE TITLE
Audio-/Videosetup im Hauptraum

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#5]
Der aktuelle Status ist (vermutlich) Katastrophal, falls es einen Status gibt.

@Cheatha und @slowpoketail arbeiten an einer neuen Lösung. Helft ihnen! :cat:

**Comment by slowpoketail** [comment]
Der letzte Stand (von vor einer Weile™) ist, dass @Cheatha und ich eine grobe Planung für das Setup hatten. Der nächste Schritt wäre, das ganze zu finalisieren, und uns dann konkret Hardware rauszusuchen. Nach dem F+R (aber vor dem Congress!) wird es dann auch nochmal mindestens ein Meeting geben.

**Comment by slowpoketail** [comment]
Es gibt jetzt https://github.com/raumzeitlabor/vhs.

**Comment by tabascoeye** [comment]
Der wichtigste Teil ist Aufzeichnung von Vorträgen.
Wir hatten jetzt schon 2-3 Vorträge die nicht aufgezeichnet wurden und es ärgert mich mega.

**Comment by steeph-k** [comment]
Es waren auf jeden Fall mehr als 3, die nicht aufgezeichnet wurden. Manche aus Gründen, andere vermutlich ohne guten Grund. Ein Problem ist, dass nicht alle Vorträge vorher auf der Mailingliste angekündigt werden und dann niemand anwesend ist, der sich zuständig fühlt. Ein anderer, dass früher als erwartet ohne Ankündigung angefangen wird und es dann unpassend erscheint, zu unterbrechen, um die Kamera aufzubauen. Für beides hat das Projekt VHS Lösungsideen. Mehr zu VHS dann dort. https://github.com/raumzeitlabor/vhs/issues/1

**Comment by s1lvester** [comment]
@Cheatha done?

**Comment by Cheatha** [comment]
Joa, man kann im Hauptraum wieder problemlos Audio/Video konsumieren. Würde dieses Issue schließen und weitere Verbesserungen (Recording, etc.) woanders diskutieren/planen.
