### ISSUE TITLE
Sanierung der Werkstatt

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#50]
# Probleme
1. Platz für maschinen geht aus
2. kein wirklich nützlicher Materialvorrat. Jedes noch so kleine Projekt involviert eine Einkaufstour
# Ideen
- [x] Lochbretter an die Wände als werkzeughalter. (Frage: Gewichtsprobleme?) Das würde die Kunststoff-Schubladen entlasten und mehr Übersciht und Erreichbarkeit herstellen. mann sieht gleich, was da ist und kommt gut ran. 
- [ ] Kleinmateriallager. Kleinmaterial wie Profilhölzer u.Ä. könnten wir in bescheidener Anzahl bevorraten und gegen Kreuze aufm Cashsystem abrechnen wie im Kiosk. Macht Gelegenheitsbastlern das Leben leichter
- [x] ggf. Auslagern des Sandstrahlers und Kompressors ins hintere Lager. Ersatzhalber kann man die wiederbefüllbaren Kartuschen verwenden (siehe https://github.com/raumzeitlabor/rzl-tuwat/issues/47 ) (hat sich erledigt, wird wohl nicht passieren)

hat sonst noch jemand Ideen, Probleme oder Anmerkungen?

**Comment by s1lvester** [comment]
Ich bin dafür den gesamten Kompressor und die Sandstrahlkabine ins Getränkelager auszulagern. Ich benutze die Kabine aber auch oft genug und bin dagegen sie weg zu werfen.

**Comment by abrock** [comment]
Eine Dose Druckluft reicht bei weitem nicht um die Stickmaschine zu säubern, daher bin ich dagegen den Kompressor ins Getränkelager auszulagern.
Die Sandstrahlkabine würd ich eher im Hochregallager deponieren, falls wir ein Gerät anschaffen das da stehen muss wo die Kabine im Moment steht.

**Comment by else** [comment]
Der Kompressor war die größte Fehlanschaffung überhaupt. Ist super laut, nimmt viel Platz weg und wird nie genutzt. Verkaufen?

**Comment by lutoma** [comment]
Ich finde den Kompressor eigentlich schon recht cool, was halt fehlt sind ein paar mehr Anwendungsfälle bzw. die Utensilien dafür. Eine Auslagerung ins Getränkelager könnte aber sinnvoll sein.

**Comment by s1lvester** [comment]
In einem Punkt muss ich @else schon recht geben: für unseren usecase ist das Teil wirklich überdosiert. 

Vor allem wenn man gewissenhaft den Druck wieder ablässt nach Benutzung hat man pro Einsatz mehrere hunderte Liter Luft um sonst komprimiert. 

Die Überlegung den Kompressor gegen ein sehr viel kleineres Modell mit kleinem Tank und gerne auch mit Schalldämmung auszutauschen kann ich nur unterstützen.

**Comment by abrock** [comment]
Kompressoren mit kleinerem Drucktank haben keine nennenswert kleinere Stellfläche und der aktuelle Kompressor steht schon an einer Stelle, die höchstens für ein Regal nutzbar wäre, an das man dann schlecht drankommt.

Die letzten beiden Male als ich die Sandstrahlkabine benutzt habe habe ich mehr als einen Kessel voll Luft verbraucht, ein kleinerer Kompressor wäre da deutlich öfter angesprungen.

Über einen Verkauf können wir reden, wenn wir einen für unsere Anwendungen äquivalenten Ersatz in der Werkstatt stehen haben.

**Comment by silsha** [comment]
Was für Eigenschaften muss ein neuer Kompressor haben, außer dass er kleiner ist? Für ~130€ (erster Treffer auf Google, geht sicher noch was) gibt es anscheinend 50L Geräte.

![](http://i.ebayimg.com/t/STAHLMANN-Druckluft-Kompressor-50-Liter-50l-50-Liter-50L-/00/s/MTIwMFgxMjAw/z/9c4AAOSwDNdV1wz0/$_12.JPG)

**Comment by abrock** [comment]
@silsha 

An einen neuen Kompressor habe ich folgende Anforderungen:

- kleinere Stellfläche
- so leicht und kompakt, dass man ihn nach Benutzung sinnvoll wegräumen kann, z.B. ins Hochregallager
- flüsterleise (ansonsten ist ein Tausch eher sinnlos)
- Genug Luftdurchsatz um halbwegs kontinuierlich mit der Sandstrahlkabine arbeiten zu können
- bezahlbar

Das Ding, das du da herausgesucht hast erfüllt keinen einzigen dieser Punkte, das passt wahrscheinlich noch nichtmal unter die Tische in der Werkstatt. Die Preiskategorie kannst du auch vergessen, leise Kompressoren sind sauteuer.

**Comment by lutoma** [comment]
Den aktuellen zu verkaufen _und_ dann noch einen (ggf. sogar teureren) zu kaufen halte ich für groben Unfug. Aktuell wird der Kompressor ja nur von einer Person genutzt, so weit ich das überblicke, da muss nicht noch mehr Geld rein versenkt werden.

Daher sind die sinnvollen Optionen, die ich sehe:
* Kompressor behalten und versuchen aktiveren Nutzen dafür zu finden. Vielleicht irgendwelchen Farbsprühkram in Kombination mit dem Laser/3D-Drucker, dunno. Oder den Sandstrahler aktiver bewerben. So viel Platz nimmt er auf jeden Fall auch nicht weg, weil er eher in die horizontale geht.
* Kompressor verkaufen und davon irgendetwas allgemeinnützigeres kaufen.

**Comment by Bfritz0815** [comment]
Lutomas Idee, mehr Anwendungszwecke für den Kompressor zu finden gefällt mir. Lasst uns das Thema auf eine separate Diskussion nehmen ud dort Vorschläge sammeln. Villeicht entsteht ja ein neues Projekt: https://github.com/raumzeitlabor/rzl-tuwat/issues/55

**Comment by Bfritz0815** [comment]
BTW: so ungefähr wie auf dem Bild hier vom Hackerspace Ffm e.V. in Oberursel bei Frankfurt könnt ich mir das mitm Materialvorrat vorstellen: 
http://www.hackerspace-ffm.de/wiki/index.php?title=Datei:Lasermaterial.jpg

Das braucht nicht mehr Platz als eine Etage im Schwerlastregal. Alternativ könnte man es auch im Fablab unter einen Tisch packen.

**Comment by steeph-k** [comment]
Naja, unter den Tischen im Fablab dürfte der Ort im RZL mit dem wenigsten Platz sein.

Ein Lochbrett für Werkzeug halte ich für sinnvoll, auch wenn es nicht viel Platz einsparen wird. An der Wand zum Flur wird das Gewicht kein Problem sein. Hier ein Vorschlag:
http://www.amazon.de/dp/B00NOV3QBM/
http://www.amazon.de/dp/B00M4D51VE

**Comment by Kunsi** [comment]
Zum Kompressor ... Warum den nicht ins Getränjelager stellen (vgl. #51) und dafür dann Strim und Luft in die Werkstatt legen?

**Comment by blabber** [comment]
> Zum Kompressor ... Warum den nicht ins Getränjelager stellen (vgl. #51) und dafür dann Strim und Luft in die Werkstatt legen?

https://github.com/raumzeitlabor/rzl-tuwat/issues/51#issuecomment-202836251

**Comment by Kunsi** [comment]
Bei dem Kommentar ging es doch darum, dass da aktiv jemand arbeitet. Bei meiner Idee stünde da nur ein Kompressor, der ferngesteuert auf anforderung Luft produziert ...

**Comment by blabber** [comment]
Die Idee Strom ins Lager zu legen wurde in https://github.com/raumzeitlabor/rzl-tuwat/issues/53 diskutiert und abgelehnt.

**Comment by Bfritz0815** [comment]
@steeph-k na wenn wir den Inhalt von ein paar von den Kunststoff-Schubladenregalen (hinten in der Werkstatt) mit dem Lochbrett untergebracht bekommen, haben wir auch mehr Platz und können dort leichtes Kleinmaterial lagern. 

Sobald das Getränkelager mal etwas ausgemistet ist und wir auch mal von der bestehenden 2.Ebene für Kleinkram Gebrauch machen, könnten wir auch welche von den Transportboxen aus der Werkstatt ins Lager schaffen. (Ich meine die Boxen für fablab-Geräte die derzeit unter den Tischen der Werkstatt stehen)
Dort könnten wir dann stattdessen auch ne Rollbox mit Material unterbringen.
