### ISSUE TITLE
Getränkelager Ausbau (was: Getränkelager entrümpeln)

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#51]
More space= more possibilities

Das Hauptlager/Getränkelager nutzen wir derzeit deutlich unter den Möglichkeiten. 
Wenn wir bestimmte Dinge auf die 2.Ebene schaffen und auch mal was wegschmeissen, bringt das schon was. Dann fällt es leichter, dort ein- und auszuladen und der Ausbau der 2.Ebene geht auch leichter. 

Langfristig profitiert davon das Getränkelager und wir gewinnen Möglichkeiten. e.g. 
- (2 Punkte zurückgezogen weil Lager und kein Werkraum. Siehe Diskussion unten)
- Häufiger nötigen Event-Kram könnten wir so unterbringen, dass wir leichter drankommen
  ...

Daher hier ein paar Punkte, die imho nen Versuch wert wären um da mal Bewegung rein zu bekommen:
- [ ] Alte regalplatten auf der 2. Ebene wegschmeissen? Warum sollten wir die noch behalten?
- [x] Glasfaserkabel rollen und Stromkabel Verschnitte. Noch brauchbar? Falls ja: ins blechregal der 2. Ebene
- [ ] alte Farben und Maler Equipment. Entsorgen? Brauchbares UND nötiges auf 2. Ebene
- [x] da familienduellgerät fliegt immer ncoh rum (hinten links) (see https://github.com/raumzeitlabor/rzl-tuwat/issues/18 ) Kann jemand den in der Issue beschreibenen Ausbau des Tasters vornehmen?
- [x] Christbaumständer und diverse Vortragsmaterialien auf die 2. Ebene
- [x] Eventdinge sortieren, ggf wegwerfen und in 2. Ebene
- [ ] Kacheln vom Laborbereich. Frage: entsorgen?
- [ ] Alter Zigarettenautomat. Frage: verkaufen / entsorgen? 
- [ ] Säcke mit Gips und Zement. Mal ehrlich Leute: wer braucht die noch irgendwann die nächsten 24 Monate? 
- [ ] Alte Poliermaschine: Gibts dafür überhaupt noch Ersatzteile für die Bürsten? Hat noch jemand vor, die zu nutzen? Wer macht die nutzbar oder kauft Ersatz falls das nicht geht?
- [ ] Große Kiste Ikea mit Reserve Gläsern. Frage: brauchen wir so viele?
- [x] Quarzsand-Säcke abdichten und auf 2. Ebene verstauen.

**Comment by s1lvester** [comment]
+1 für ne Drehbank  :heart_eyes:

**Comment by Bfritz0815** [comment]
war ja mal im Gespräch. wurde dann aber wg Sicherheit und Platzbedarf abgewiesen. Im Getränkelager ist (nach Ausbau) Platz und da das Ding separat abzuschliessen ist, kommt da auch keiner hin, der nicht sollte.

**Comment by Don42** [comment]
Wir haben da hinten keinen Strom und müssten Kabel über die komplette Strecke legen.
Daher ist alles was irgendwie Strom verbraucht eher unpraktisch.

**Comment by Bfritz0815** [comment]
@Don42  Oh! You sure? Major problemo. Wäre die Frage, ob da nicht in Zukunft ne Verkabelung hin sollte. 

Das wäre allein schon wegen der Beleuchtung sinnvoll. 
Beim Rumräumen ist es schon mehr als scheisse, wenn das Licht per Timer ausgeht. 
Besonders wenn man auf der 2. Etage und evtl. noch alleine ist. Im Dunkeln mit den Füßen nach der Leiter angeln ist eher 0 von 10. Wenn wir das Lager irgendwann in brauchbarer ausgebaut haben, wird wohl öfter jemand daran rumwerken auch wenn evtl. keine Maschinen dort sind. 


Update: war grade hinten: Es liegen Kabel (hinter der derzeitigen 2.Ebene kommen die von der Decke runter). Es sind nur diese Fragen offen:

1. Wieviel geben die Leitungen her?
2. Kann die jemand anschließen?
3. Wie würde das abgerechnet werden? (Mit Vermieter reden)

Wenn das Aufräumen durch ist, kann ich ja ne issue dazu anlegen...

**Comment by Don42** [comment]
@Bfritz0815 Entweder wir bräuchten einen extra Stromzähler den der Vermieter installieren müsste oder wir legen Kabel bis hinter und schließen die bei uns an den Sicherungskasten.

**Comment by steeph-k** [comment]
Wenn wir noch Platz im Sicherungskasten haben wäre letzteres ja auch kein Problem. Da ist doch überall abgehängte Decke, oder? Ich wäre beim Kabelziehen dabei.

**Comment by Don42** [comment]
@steeph-k Die letzten 10m durch den Raum ist keine abgehängte Decke.

**Comment by Bfritz0815** [comment]
@Don42 @steeph-k hab dafür mal ne eigene Issue aufgemacht

**Comment by tabascoeye** [comment]
Das Ding ist ein **Lager**. Kein Vollwertiger Raum. Wir zahlen dafür auch keine Miete wie für einen Raum. Dort Strom separat hinlegen und das Licht separat schaltbar machen wird uns seriöslich Geld und Stress mit Mutlu kosten.
Nicht sicher ob sinnvoll.

Bei ner Drehbank wird der Aspekt mit "Licht geht nach xMinuten aus" noch viel lustiger.
Außerdem kommen noch viele weitere Aspekte dazu, wenn wir plötzlich "Aufenthaltsräume" aus den Lagern machen:
* Keine Heizung
* Wie stellt man sicher, dass der Hauptraum dann nich offen gelassen wird auch wenn dort keiner mehr ist?
* Die Chance, dass jemand dich findet, wenn dir dort was passsiert ist noch viel geriner, als es im Hautpraum ist (auch: Haftpflicht)

Das Lager zu mehr zu machen, als es ist (again: **Lager**) halte ich für unüberlegt.

**Comment by s1lvester** [comment]
Die Diskussion sollte damit dann durch sein. Das Ding muss Lager bleiben.

Aufräumen muss man es trotzdem.

**Comment by steeph-k** [comment]
Zu "Alte regalplatten auf der 2. Ebene wegschmeissen? Warum sollten wir die noch behalten?":
An der hinteren Wand im Getränkelager könnten wir ein Regal aufbauen und dort viele der Sachen unterbringen, die jetzt im Weg rumliegen. Wie Platten sehen ja noch gut aus und ziemlich stabil.

**Comment by steeph-k** [comment]
Zu "Große Kiste Ikea mit Reserve Gläsern. Frage: brauchen wir so viele?":
Wenn ich das richtig gesehen habe, dann sind auch bei Veranstaltungen im RZL die Gläser im Schrank mehr als genug. Übrige könnten wir also verkaufen oder spenden.

**Comment by Bfritz0815** [comment]
close weil die Diskussion nur ablenkt
