### ISSUE TITLE
Leuchtsymbole fuer die Lichtschalter

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#52]
Bei dunklen Räumen (wg Filmabend oder anderen Gründen) sind Lichtschalter teils schwer im Raum zu lokalisieren (siehe E/Ä-Ecke). 
Andere (siehe Lichtschalter im Hauptraum neben der Tür) haben mehrere Teilschalter die im Dunkeln (Filmabend) schwer auseinanderzuhalten sind. 

Hier wäre es nice, wenn die im Dunkeln etwas leuchten/glimmen würden. 
Ich könnte mir dazu 2 Möglichkeiten denken:

1. Einfache Nachleuchtende Aufkleber in Formen zu schneiden
2. Irgendein LED-gizmo zu entwerfen, das auf/in die Schalter kommt. (Bitte nur durch Leute, die auch sicherstellen können, dass einem dann nicht Haushaltsstrom durch die Finger strömt...)

**Comment by tabascoeye** [comment]
Am besten nimmt man da Nachleuchtende PVS Folie, die man mit evtl unserem Scheidplotter bearbeiten kann:
http://www.orafol.com/gp/europe/de/produkte/druckmaterialien-produktdetails/items/oralux-9300-luminescent-cast

**Comment by steeph-k** [comment]
Klar, die kann mit dem Potter geschnitten werden. Falls jemand Nachleuchtende Farbe (z.B. als Spray) übrig hat wäre es aber billiger, Maskierungsfolie zu plotten. Davon ist im Raum da. Für so eine kleine Sache wäre ein Dose Farbe aber wohl nicht viel billiger als die Folie. Andererseits wäre dann eine fast volle Dose Leuchtfarbe und immer noch ein paar Meter Maskierungsfolie, sowie andere freie Flächen in den Räumen übrig.

**Comment by Bfritz0815** [comment]
also bei den Sprays sind die Erfahrungen recht durchwachsen. Folie ist sicher vom Ergebnis her und direkt im Raum bearbeitbar: Werkstücke (i.e. Lichtschalter) müssen zum Besprühen rausgebracht werden, zum Bekleben nicht. Ausserdem lädt das Vorhandensein solcher Folie zu mehr Versuchen damit ein.

**Comment by tabascoeye** [comment]
![img_20160430_155953](https://cloud.githubusercontent.com/assets/111893/14936717/2d09ae3a-0ef4-11e6-8a28-470395052640.jpg)
Ich hatte noch von der Klebefolie die mir der GloRope typ mal gegeben hat.
Hab im Hauptraum den Block und die 4 Schalter markiert. In der E-Ecke die 4 an den Sitzplätzen.

==> fixed?

**Comment by Bfritz0815** [comment]
@tabascoeye improved but not fixed. Thanks. 

# Tests:

- [x] überhaupt mal Auffindbarkeit der Lichtschalter im Dunkeln.
- [ ] Unterscheidbarkeit der Schalter. (i.e. Will mal schnell in der Küche an machen ohne die Vortrags-Zuschauer zu blenden)

**Comment by tabascoeye** [comment]
der Quickfix wäre mit einem schwarzen Edding auf die Leuchtfolie einen Buchstaben zu malen.
Also "K, L, T, B" für Küche, Lager, Tafel, Beamer.

**Comment by Bfritz0815** [comment]
Jemand hat den Quickfix im Hauptraum angebracht, ich hab dann noch die Schalter in der E/Ä-Ecke beschriftet. 

**closed successfully**
