### ISSUE TITLE
Strom im Getränkelager

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#53]
Abgeleitet aus https://github.com/raumzeitlabor/rzl-tuwat/issues/51

- Anschluss
- so anschliessen, dass die Abrechnung klappt
- Wo und wieviele Steckdosen?
- Lichtschalter und Beleuchtung im G-Lager

**Comment by Bfritz0815** [comment]
@Don42 
wg 
> Die letzten 10m durch den Raum ist keine abgehängte Decke.

Wo genau meinst du?
Ich bin die Strecke abgelaufen. das sieht so aus:
- oberhalb unseres Sicherungskastens in der Werkstatt ist ein Durchbruch in der Mauer zum Flur
- die abgeh. Decke ist im Flur durchgängig bis zum Flur-Ende
- am Flur-Ende ist eine Freifläche vor dem Getränkelager. dort ist keine abgeh. Decke aber an der Wand zum Getränkelager hin sind reichlich Möglichkeiten, Stromkabel langzuführen. Tatsächlich laufen da schon einige Kabel aus der Zwischendecke entang

Sollte also kein prinzipielles Problem sein, da ne Strippe hinzuziehen.

**Comment by Don42** [comment]
@Bfritz0815 Den Freiraum meinte ich.

**Comment by lutoma** [comment]
Wenn wir dort tatsächlich ein Stromkabel hinlegen, wäre es denke ich auch eine gute Idee, gleich ein Netzwerkkabel mitzulegen, für Zukunftssicherheit™. Gibt sicher ein paar Anwendungsbereiche dafür, Temperaturmessungen oder so.

**Comment by tabascoeye** [comment]
na klar. paar hundert Meter Kabel kaufen und in der kack Zwischendecke bis nach ganz hinten verlegen.
* Kostet ordentlich Kohle für unklaren Mehrwert
* Hat keiner Bock drauf
* Müsste erstmal mit Mutlu geklärt werden
* Ich will gar nicht so genau wissen, was alles in der Zwischendecke lauert (Im Nebenraum waren da unklare, offene Leitungen, Haken, Bretter, etc)

**Comment by abrock** [comment]
Ich stimme tabascoeye zu, wir müssten auch mindestens 5x4mm² Leitungen verlegen, wenn nicht sogar 5x6mm² weil sonst der Spannungsabfalls bis zum Getränkelager zu groß wird, insbesondere bei großen Verbrauchern wie Kompressor.

**Comment by s1lvester** [comment]
yup. Kein Strom. --> close?

**Comment by steeph-k** [comment]
Nur der Vollständigkeit halber noch der Hinweis, dass der Punkt "Hat keiner Bock drauf" nicht ganz korrekt ist, da ich ja schon angeboten hatte, die Leitung zu legen. Das Angebot steht, sollte das noch mal interessant werden.
