### ISSUE TITLE
Anwendungsmöglichkeiten des Kompressors

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#55]
Was könnte man denn noch so mit nem Kompressor anstellen?

(hervorgegangen aus https://github.com/raumzeitlabor/rzl-tuwat/issues/50#issuecomment-204434039 und https://github.com/raumzeitlabor/rzl-tuwat/issues/47)

**Comment by Bfritz0815** [comment]
Wie sehr eignet sich der Kompressor für Spraypainting?

Wer hat Erfahrung mit Spraypainting? 

Was müssten wir tun, um mehr spraypainten zu können? 
Spraykabine? Abluft? Atemschutz? Location dafür? etc.

**Comment by Bfritz0815** [comment]
Warum denk ich gerade beim Kompressor an "Raumzeit-Orgel"? Hmmm...

**Comment by abrock** [comment]
> Wie sehr eignet sich der Kompressor für Spraypainting?

Sehr gut. Hat einen Öl/Wasserabscheider, einen einstellbaren Druckminderer und einen großen Druckspeicher, so dass man lange sprühen kann ohne dass der Kompressor wieder anspringt.

> Wer hat Erfahrung mit Spraypainting?

echox

> Was müssten wir tun, um mehr spraypainten zu können?

Darf jemand herausfinden, der tatsächlich sprühen will.

> Warum denk ich gerade beim Kompressor an "Raumzeit-Orgel"? Hmmm...

Falscher Kompressor.

**Comment by lutoma** [comment]
Airhockey-Tisch! *duck* Wobei der dafür vermutlich nicht genug durchsatz hat

**Comment by hax404** [comment]
>> Wer hat Erfahrung mit Spraypainting?

> echox

Er hat da einen kleinen Kompressor für feinere Dinge im Hochregallager.

**Comment by silsha** [comment]
Da das hier eher eine Diskussion mit offenem Ende als ein Issue ist, schließ ich das mal. :3 Wenn das jemand anders sieht, einfach wieder öffnen.
