### ISSUE TITLE
Laserabluftsituation verbessern

### ISSUE THREAD

**Issue by lutoma** [raumzeitlabor/rzl-tuwat#56]
In letzter Zeit lasern Leute irgendwelchen Kram, der massiv stinkt und auch echt nicht gesund wirkt. Vermutlich irgendwas mit Plastik? Das ist schon beim durch das Fablab laufen auf dem Weg in den Workshopraum ziemlich unangenehm, ich weiß nicht wie Leute es längere Zeit in dem Raum währenddessen aushalten. Das zieht wenn man mal die Türen offen lässt auch ziemlich fies in den Workshop- und Hauptraum rüber und braucht ewig zum lüften.

**Comment by steeph-k** [comment]
Liest udn schreibt Abrock hier mit? Es gab da doch schon mal Pläne, die Abluft des Lasers und der Dunstabzugshaube oberhalb der Fenster direkt aus dem Gebäude zu blasen. Oder blieb es bisher bei der Idee?

**Comment by tabascoeye** [comment]
Steeph hat einen neuen Filter bestellt. ==> close for now?

**Comment by steeph-k** [comment]
Na gut. Ich denke hier geht es schon auch um eine grundsetzlich bessere Abluftlösung. Aber das angesprochene Problem dürfte ja erst mal behoben sein.
