### ISSUE TITLE
Lost and found April 2016

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#57]
Aufm Tisch neben Tardis Steht die lost-and-found-Kiste. Der Aktuelle Inhalt ist hier fotografisch dokumentiert: https://drive.google.com/folderview?id=0B29VNm8D-Mz5UFdyUnVnbEJmanc&usp=sharing

Wir haben da: 
- 1 regenjacke (blau)
- 1 Schal (blau)
- 1 paar hanschuhe (dk grau)
- n textilien mit incl. Stickvlies (to textillager? jemand privat?)
- pinkes USB-Ladekabel
- schwarzes Netzteil mit festem Kabel
- Kleinkram f Küche und E-basteln
- alte metrorechnung (wessen? schon abgerechnet?)
- 2 Klappboxen (labled Give-away)

**Comment by steeph-k** [comment]
Von den pinken USB-Kabeln hat mal jemand einige für den Raum angeschafft. Die sollten in der USB-Kabel-Kiste in Regal am Eingang liegen. Es scheint mir, USB-Kabel und -Netzteile sind im RZL was in Büros Kugelschreiber sind. Ich habe mal noch 30 kurze Kabel bestellt. Diesmal in verschiedenen Farben.

**Comment by s1lvester** [comment]
Alles weg soweit.
