### ISSUE TITLE
Schilder auf Gelände aufhängen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#58]
Um das RaumZeitLabor leichter zu finden könnten wir Schilder aufhängen.

Auf dem Gelände gibt es schon geeignete Plätze für Schilder, auf denen z.B. schon Delta Werbetechnik.
Wir könnten selbst Schilder machen und sie einfach dazu hängen oder vorher den Vermieter fragen, was der davon hält.

**Comment by steeph-k** [comment]
Ich werde bei Gelegenheit mal Schildmaterial (keine Ahnung wie man das nennt, ist bei Delta abgefallen) mitbringen und entweder bei selbiger oder der nächsten Gelegenheit auch zuschneiden und beschriften. 

Wie kontaktiert man denn den Vermieter am besten? Ich gehöre nicht zu den Leuten, die ihn schon mal kennen gelernt haben.

**Comment by silsha** [comment]
@steeph-k Bist du auf info@? Dort einfach mal nach Multu - oder vermutlich besser noch nach Csörsz suchen (möchte die Adressen hier nicht öffentlich posten).

Ich würde die Schilder vermutlich ohne nachfragen aufhängen. Schadet niemanden, ist nicht von der Laune des Vermieters abhängig und wenn er was dagegen hat kann man sie ja noch entfernen.

**Comment by tabascoeye** [comment]
solange die Wetterfest und an den vorgesehenen Plätzen (zB wo auch schon die delta schilder sind) aufgehängt werden statt wit Gaffa tape ausgedruckte DinA4 Blätter, wird die Akzeptanz von Mutlu hoch sein denke ich

**Comment by steeph-k** [comment]
Ich bin erst nächste Woche wieder im RZL. Wenn mir jemand vorher die 
Maße für ein Schild schreibt, kann ich sie schon mal zuschneiden und 
muss nicht die ganze Platte mitnehmen. WIe viel brauchen wir eigendlich? 
Drei? Sind die gleich groß?

**Comment by silsha** [comment]
Ich denke zwei reichen. Eins an die Stange am Tor und eins zu den anderen Schildern bei Johnson Controls.
Interessanterweise haben wir schon ein richtiges™ Schild am Grillplatz.

**Comment by lutoma** [comment]
Ich habe gesehen, dass Delta auch einfach vorne bei der Straße (beim Haupttor links die Boveristraße runter bis zu der ersten Kreuzung) eines ihrer Schilder zu einem anderen Werbeschild dazugehängt haben, das könnte vielleicht auch nützlich sein.

**Comment by steeph-k** [comment]
Die Schilder auf dem Gelände hängen jetzt. Ich schau mir am Dienstag mal an, wo das in der Boveriestraße ist und ob wir uns da noch unterbringen können.

**Comment by silsha** [comment]
@lutoma Meinst du sowas? http://www.mannheimer-stadtreklame.de/hinweisschilder.html

**Comment by lutoma** [comment]
So was in der Art, wobei Delta da einfach nur ein pfeilförmiges Plastikschild mit Kabelbindern dran gemacht hat, also nicht ganz so fancy.

**Comment by silsha** [comment]
Issue scheint erstmal erledigt zu sein. 🐱

**Comment by steeph-k** [comment]
Die verwendete Plotterfolie ist billige Messestandfolie, die für Indoor-Anwendungen vorgesehen ist und nur eine Woche halten soll. Das ist eben die schwarze Folie, die wir haben. Meiner Erfahrung nach kann man die auch auf ein dreckiges Auto kleben und mindestens ein Jahr lang rum fahren. Aber falls sie abfällt, war das vom Hersteller so vorgesehen. Außerdem habe ich den Pfeil auf dem einen Schild nicht gut getroffen. So hebt er sich von den anderen ab. Falls sich daran jemand stört: Kein Problem, kann man einfach austausche, da es nur Messestandfolie ist.

Das Deltaschild mit Kabelbindern ist mir bisher noch nicht aufgefallen.

**Comment by tabascoeye** [comment]
Wenn wir hier von oracal "exhibitionCal" reden, ist "billig" wohl nicht ganz treffend ;o)
Ich kann aber bestätigen, dass die den Outdooreinsatz gut ab kann.
Vor einer Weile hatte ich da was auf der Heckscheibe (außen!) und dem Ding war auch Regen und das Wischerblatt egal...

**Comment by steeph-k** [comment]
Ich meinte billig im Vergleich zu solcher, die für den Outdoor-Einsatz empfohlen wird.
