### ISSUE TITLE
Vorschaubilder im Wiki sind kaputt; ImageMagick fehlt

### ISSUE THREAD

**Issue by lutoma** [raumzeitlabor/rzl-tuwat#59]
Sichtbar z.B. hier https://wiki.raumzeitlabor.de/wiki/Datei:RaumZeitLabor_-_Logo_-_Schwarz.svg

Fehlermeldung: `Fehler beim Erstellen des Vorschaubildes: /bin/bash: convert: command not found`

**Comment by docsteel** [comment]
Ist gefixt.

**Comment by lutoma** [comment]
@docsteel merci.
