### ISSUE TITLE
Hochregallager durchgehen, Sachen identifizieren, Mitglieder ansprechen

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#6]
Ungenutzte Dinge im Hochregallager identifizieren, Eigentümer herausfinden und zum mitnehmen bewegen. Wenn Eigentümer = RZL: Verwendung zur Diskussion stellen.

**Comment by maikf** [comment]
Wurde auf dem ersten Format&Reinstall entrümpelt.
Mitglieder wurden benachrichtigt laut ML.
