### ISSUE TITLE
API endpunkte reparieren

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-tuwat#60]
https://status.raumzeitlabor.de/api/full.json
https://status.raumzeitlabor.de/api/simple

funktionieren nicht mehr. Müsste mal gefixt werden.

**Comment by Don42** [comment]
Weiß jemand woher genau die kommen?

**Comment by blabber** [comment]
> Weiß jemand woher genau die kommen?

Ohne das jetzt wirklich zu wissen, scheint https://github.com/raumzeitlabor/raumzeitstatus ein guter Kandidat zu sein.

> https://status.raumzeitlabor.de/api/simple

Stattdessen kann https://status.raumzeitlabor.de/api/simple.json verwendet werden. Nur Achtung: Nur weil da json draufsteht ist noch lange kein json drin.

RaumZeitStatus Geekend, anyone?

**Comment by blabber** [comment]
Noch ein kurzer Nachtrag zu den verfügbaren Endpoints: Es gibt auch noch https://status.raumzeitlabor.de/cosm.json. Allerdings sind hier auch viele Felder leer, beziehungsweise mit '?' gefüllt oder änder sich nicht. Ich tippe aber mal, dass das die Quelle ist aus der sich er Infoscreen speist.

Zumindest die Temperatur verändert sich öfter mal und wird verwendet um sie auf https://status.raumzeitlabor.de auszuspiegeln.

**Comment by tabascoeye** [comment]
Der Infoscreen lutscht die Daten direkt aus dem Xively Feed. Ich denke das cosm.json ist aber auch nur ein request an die Xively API.

Müsste man alles mal Bulldozern.

**Comment by Ranlvor** [comment]
Ich hab mir das gerade mal angeschaut und… ewww. Ew ew ew ew ew.

api/status.json wird auf irgendein PHP-Skript umgebogen, das sich den Status per MQTT holt.
api/<alles andere> geht per reverse Proxy auf eine Perl-Anwendung. Diese bekommt ihre Updates via HTTP-Post-Request.
update/ ist eine Apache, der statische Files ausliefert und man kann mit den passenden Zugangsdaten die Daten in update/ via WebDAV auch über den Apache schreiben.

Jetzt muss ich „nur noch“ rausfinden was davon gebraucht wird, was davon kaputt ist und wo ich das fixen muss.

**Comment by Ranlvor** [comment]
Ich deprecate hiermit /update/ und /cosm.json. Aufrufe aus letzterem von der Statusseite habe ich auskommentiert.

/api/status.json funktioniert und bei /api/ grübel ich noch, wie ich das am wenigsten scheiße repariere.

**Comment by Ranlvor** [comment]
Ich habe jetzt /api/full.json in PHP mit MQTT neu implementiert, das funktioniert jetzt. /api/stream/full.json ist weiterhin kaputt. Wer das braucht sollte besser MQTT nutzen.

**Comment by s1lvester** [comment]
Danke!
