### ISSUE TITLE
InfoScreen inhaltlich neu machen oder rearieren

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-tuwat#61]
* Internet up/downstream tut schon lange nicht <br>
  (braucht sicher ein Skript auf der firebox o.ä. das den Xively Endpunkt aktualisiert)
* Es laden nicht immer alle Graphen (problem im JS?)
* Die VRN Haltestellenanzeige geht nicht mehr<br>
Es gibt aber inzwischen ein OpenData Projekt bei der RNV, da sollte man schick an die Infos kommen
* Angemeldete Geräte geht nicht mehr (braucht auch ein Sktip auf der Firebox oder den APs?)
* Kontostand und Mitgliederzahl werden manuell geupdatet. Aber das Skript bei @tiefpunkt scheint nicht mehr zu tun...
* Die TODO Liste hat keinen Inhalt. Könnte zB die Issues hier in rzl-tuwat listen mit QR-Codes als links

**Comment by Don42** [comment]
Wenn man schon dabei ist, könnte man vielleicht mal von Xively weg in Anbetracht der Tatsache das man dort keine Gratis Accounts mehr bekommt und wir einfach noch alte API Keys haben. Grafana plus eines der Backends wäre vermutlich am einfachsten.

**Comment by silsha** [comment]
Ich arbeite gerade an einer neuen Version. Den aktuellen Stand gibt es bei [silsha/infoscreen-v6](https://github.com/silsha/infoscreen-v6).

![screen shot 2016-06-10 at 21 27 26](https://cloud.githubusercontent.com/assets/31850/15976301/2d93cdc6-2f52-11e6-852f-37526c33e78b.png)

**Comment by silsha** [comment]
Soo, der Infoscreen v6 ist soweit, dass er live gehen kann. Ich habe das gestern mal ausprobiert - über VGA bekomme ich aber kein Full HD. Später sollte rechts und unten noch jeweils eine Zeile frei sein für Widgets (oder wir machen sie insgesamt größer). 

Die SD-Karte vom Raspberry ging kaputt, weswegen die neu geflasht und so eingerichtet werden muss, dass im Browser http://cashdesk.rzl:3030 aufgerufen wird. @lutoma bestellte neue SD-Karten.

Unter https://github.com/silsha/infoscreen-v6/issues gibt es noch ein paar offenes Issues. Wenn sich jemand damit beschäftigen möchte, nehme ich gerne Pull Requests an.

![img_2090](https://cloud.githubusercontent.com/assets/31850/16000247/7f9f2d40-314b-11e6-9125-6726f700072d.JPG)

**Comment by silsha** [comment]
@lutoma Was ist da der aktuelle Stand?

**Comment by silsha** [comment]
Funktioniert grundsätzlich wieder.

Manchmal ist das Bild auf dem Monitor nach rechts verschoben. Ich schätze aber, dass das am Raspberry und nicht am Infoscreen liegt.

Außerdem müsste die Zeitzone korrekt eingestellt werden, damit der Kalender und die ÖPNV-Abfahrten richtig funktionieren.

**Comment by s1lvester** [comment]
done. Neue broser.c: https://github.com/raumzeitlabor/kiosk-browser/commit/12289103cd60f0744572ca5d0be6e15043a373d8
