### ISSUE TITLE
Spamfilter und/oder grey-listing auf dem mailman installieren

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-tuwat#62]
Wir bräuchten vor Info@ und evtl. vorstand@ mal einen Spamfilter.

Die jetzige Situation ist recht unbefriedigend, nicht nur weil auf info@ reichlich spam aufläuft, sondern weil der auch noch zur Folge hat, dass valide Member unsubscribed werden, wenn ihr mailserver den Spam der von info@ kommt blockt/bounct.

Ist schon mehrfach passiert und induziert nur Stress und Arbeit.

**Comment by silsha** [comment]
Kann das Problem bestätigen. Wurde auch mehrfach von info@ gekickt und habe es nun aufgegeben.

**Comment by silsha** [comment]
Wer fühlt sich denn aktuell für unsere Mailinglisten zuständig? Gibt es das NOC-Team noch? 🐱

**Comment by docsteel** [comment]
Ich bau da mal was.

**Comment by lutoma** [comment]
Ich habe bei Postfix da immer ziemlich viel gute Erfahrungen mit `postscreen` gemacht, insbesondere weil das DNSBLs ranken kann.

**Comment by docsteel** [comment]
Ich hab da jetzt erstmal ein Greylisting mit `postgrey` gebaut, detaillierter Spamfilter kommt noch.

**Comment by uwap** [comment]
Ist das noch auf eurer to do? @docsteel @Ranlvor

**Comment by uwap** [comment]
Da vom NOC Team keine Antwort mehr kam, schließe ich das Issue jetzt und gehe mal davon aus, dass da kein Interesse mehr dran besteht was zu ändern. @docsteel @Ranlvor @hax404

**Comment by steeph-k** [comment]
Das halte ich für eine falsche Schlussfolgerung. Die Situation ist weiterhint aus den von tabascoeye Gründen unbefriedigend.

**Comment by hax404** [comment]
Idee: Statt Verteiler, wo Emails weiterverteilen, geteilte (IMAP-)Postfächer. Dann müssen die SPAM-Emails nicht durch restriktive Filter von Gmail & Co durch.
Geteilte Postfächer stelle ich mir so vor: Ein Postfach für info@ und eins für vorstand@. Die Zugangsdaten werden dann den Personen bekannt gegeben, die Interesse haben. Da wird dann mit einer Ordnerstruktur für
  * unbearbeitete Mails (INBOX)
  * bearbeitete Mails
  * Spam

gearbeit. Genaueres kann sich jemand anderes überlegen.
Wer wie früher Emails in sein eigenes Postfach zugestellt haben möchte, kann sich einen fetchmail einrichten.

**Comment by steeph-k** [comment]
Das ist ja mal wieder Denken außerhalb der Kiste hier. Aber meines Erachtens würde sich das nicht lohnen. Der Spam müsste ja trotzdem noch ausgefiltert werden.

**Comment by tabascoeye** [comment]
Ich finde das Spamaufkommen inzwischen sehr erträglich.
Die Frage ist, ob die bounce-kicks noch andauern und ob man nicht dem Mailman beibringen kann, bounces von gmail und co zu akzeptieren und nicht weiter zu versuchen, mails zuzustellen.
==> wenn Spam nicht mehrfach versucht wird an gmail Konten zuzustellen, trotz spam bounce von gmail, dann gibts auch keine kickbans

**Comment by steeph-k** [comment]
On 23.10.2017 09:27, TabascoEye wrote:
> Ich finde das Spamaufkommen inzwischen sehr erträglich.

Erträglich mag es sein. Aber da habe ich andere Ansprüche. Von den seit 
1.9. von der Info-Liste bei mir angekommenen Mails sind 85% Spam. Wir 
haben also mehr als fünfmal so viel Spam wie Ham. Jeden Monat mehr als 
50 solcher Mails, das finde ich nicht akzeptabel. Das meiste kann ich 
zwar problemlos rausfiltern. Aber das heißt dann doch wohl, dass die 
auch vor dem Absenden hätten rausgefiltert werden können.

**Comment by Ranlvor** [comment]
Habe mal den Spamfilter von info@ etwas aggressiver eingestellt. Sobald der „X-Spam-Level: *“-Header vom Spamfilter gesetzt wird landet die Mail jetzt (hoffentlich) in der Moderationsqueue. Bei einer kleinen Stichprobe in meinem Mailclient konnte ich keine Mail finden, die dieses Level hat und die ich vermissen würde.

**Comment by steeph-k** [comment]
On 23.10.2017 19:02, Ranlvor wrote:
>
> Habe mal den Spamfilter von info@ etwas aggressiver eingestellt. 
> Sobald der „X-Spam-Level: *“-Header vom Spamfilter gesetzt wird landet 
> die Mail jetzt (hoffentlich) in der Moderationsqueue.
>
Cool. Danke schön! Das dürfte mehr als die Hälfte wegfiltern.

> Bei einer kleinen Stichprobe in meinem Mailclient konnte ich keine 
> Mail finden, die dieses Level hat und die ich vermissen würde.
>
Dito.

**Comment by uwap** [comment]
Also die letzten Tage kam so gar kein Spam mehr auf info@. Close, @Ranlvor?

**Comment by steeph-k** [comment]
Ich bin zufriden. Danke für die Änderung!

Also ich wollte eigentlich bis heute abwarten und es dann schließen. Aber da du explizit @Ranlvor fragst, warte ich mal noch ein bisschen.

**Comment by Ranlvor** [comment]
Wenn ihr meint, dass das gut genug ist um das Ticket zu schließen will ich nicht widersprechen.
