### ISSUE TITLE
Tür in der E-Ecke ist defekt

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-tuwat#63]
Wie von @slowpoketail auf Twitter gezeigt geht die Tür in der E-Ecke aus dem Leim.
(http://log.raumzeitlabor.org/post/145379878631/t%C3%BCr-kaputt)

Die Konstruktion ist eh etwas weird. Das Türblatt ist offenbar mal mit einer zusätzlichen Leiste verbreitert worden und an dieser Leiste sind die Schraniere befestigt.

Es sieht so aus, als könnte man das mit einer großen Schrabzwinge und Holzleim und/oder Schrauben fixen kann.

Vielleicht kann sich die @abrock school of engineering hier verdingen ;o)

**Comment by abrock** [comment]
Ich habe die Tür ausgehängt, geleimt, geschraubt und wieder montiert.

http://log.raumzeitlabor.org/post/145765288086

**Comment by tabascoeye** [comment]
hübsche Arbeit. Danke :o)
