### ISSUE TITLE
Updateworkflow für docker-container auf citizenfour

### ISSUE THREAD

**Issue by hax404** [raumzeitlabor/rzl-tuwat#65]
Wir brauchen eine Möglichkeit, docker-container (halb)automatisch mit Updates zu versorgen. Hat das jemand schonmal gemacht und kann da was empfehlen?
Aktuell erfolgt nach dem Stop der Container per systemd.service ein docker pull https://github.com/raumzeitlabor/nginx-proxy/blob/master/reverse-proxy.service

**Comment by docsteel** [comment]
Ein frisches Base Image mit aktuellen Updates drin wäre auch schon mal was.

**Comment by s1lvester** [comment]
Siehe Conversation über ML und Ansible. Close?
