### ISSUE TITLE
Regale am Eingang: defrag

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#66]
# Meine Vorstellung zu dem Regal am Eingang ist:
1. Zubehör, das man oft braucht, liegt da an einem sehr zentralen Ort im Raum. 
2. Es sollte übersichtlich sein, damit man diese oft gebrauchten Dinge schnell findet
3. "Dinge" bezieht sich hier auf Dinge, die ansonsten keinen klaren Ort im Raum haben. Bereichs-Spezifische Instrumente sollten im jwlg. Bereich lagern. (e.g. Oszilloskop gehört erstmal in die E-Ecke, nicht in x verschiedene Orte im Raum)
## Daher gehören da rein:
- häufig gebrauchte Kabel
- generische, oft gebrauchte Zubehörteile
## Nicht dort hin gehören folgende Dinge:
- Messgeräte (gehört in: E-Ecke, Fablab oder Werkstatt) (aus Regel 3)
- Verbrauchsmaterial (gehört in: E-Ecke, Fablab oder Werkstatt) (aus Regel 1 und 3)
- Projekt-Kisten (dafür ist IMHO das Hochregal gedacht) (aus Regel 2 und 3)
- alter Kram, der nur noch selten bis gar nicht gebraucht wird (Lager oder wegräumen) (aus Regel 1 und 2)
# Sofern wir uns da einig sind, ergibt sich folgendes Bild:
1. Im Regal am Eingang liegen n Kisten mit Stuff.
2. Für m < n gilt: es sind exakt m Kisten fürs RZL nötig.
3. Für x + y = m gilt: es ist nötig, dass exakt x Kisten dort im Regal stehen. Und: Es ist nötig, dass y Kisten an anderen Orten stehen als dem Regal am Eingang. 
## Daher:

Liste der Kisten, die derzeit im Regal am Eingang stehen mit Anmerkungen:
- [x]  "Zeitschaltuhren": wie oft wird das gebraucht?
- [x]  "Schlösser" fuers Picking-Üben: Ich seh das wie bei den Projekten. Passt gut ins Hochregal
- [x]  "Siebdruck": ins Fablab?
- [x]  "Projektkiste Freifunk": Ins Hochregal? Oder noch nötig? (Es beinhaltet Kaltgerätekabel. Braucht das ne getrennte Kiste im Regal? Wozu brauchts die da in Bereitschaft? Kann Freifunk nicht einfach die RZL-Kaltgertekabel nehmen, wenn da kurzfristig im Raum was gebraucht wird? Oder sind das Arbeitsmaterialien zum festen Verbauen? Dann könnten die ja in Hochregal zu den anderen Projektdingen)
- [x]  "E-Eck-Module": Sieht aus wie ne mixed-stuff Kiste. Ist kaum befüllt. Defrag. 
- [x]  Kiste mit Bügelperlen: Fablab? Noch nötig?
- [x]  "Handyladegeräte Multimeter Magnete": Sollte lieber "diverses" heissen. Multimeter in E-Ecke, Magnete zu den anderen in der Küche. Die Handyladegeräte finden sicher auch ein besseres Zuhause
- [x] "Leuchtmittel": Brauchen wir selten. Ins (Getränke)Lager (auf 2.Ebene ins Regal)
- [x] "CFD Chaos Familien Duell": Ist das ein regelmäßig benötigtes Ding? Eher was fürs (Getränke)Lager
- [ ] "Serielle / Parallelkabel": An Museum oder team Retro?
- [ ] "SCSI / Spezialkabel": An Museum oder team Retro?

**Comment by steeph-k** [comment]
Projektkiste Freifunk/Kaltgerätekabel: Da die Kaltgerätekabelkiste nicht mehr da ist, vermute ich da eher, dass eine Kistenumfunktionierung ohne Kistenumbeschriftung stattgefunden hat. Eine nachträgliche Kistenumbeschriftung sollte den Punkt lösen.

**Comment by Bfritz0815** [comment]
@Cheatha Frage: Die Kiste "Projektkiste Freifunk" im Regal am Eingangsbereich: Ist das so wie steeph vermutet, dass die nicht wirklich Freifunk ist sondern nur vergessen wurde, die umzubeschriften?

**Comment by Bfritz0815** [comment]
@Don42 Ich würd gerne die Schlösser fürs Picking (derzeit im Regal am Eingang) ins Hochregal, in eine Schublade oder an einen anderen geeigneten Ort transferieren um im Eingangsregal Platz zu schaffen. Meinungen zu geeigneten Orten? (Ich könnte z.B. die linke Hälfte von Tardis 1 0xF1 anbieten)

**Comment by Bfritz0815** [comment]
@Unicorn-rzl FYI: ich hab die Kiste Siebdruck ins Hochregal verlegt. Location HR-C6 (Ja, das hat jetzt ein koordinatensystem: A-D = x-Achse-links-nach-rechts; 0-8 = y-Achse-unten-nach-oben)

**Comment by Cheatha** [comment]
@Bfritz0815 @steeph-k Ich glaube mich zu erinnern, dass das noch eine Kiste aus »Freifunk Mannheim«-Zeiten ist. Und da sich offensichtlich auf kein Freifunk-Krams darin befindet spricht nichts gegen eine Umbeschriftung ;)

**Comment by Bfritz0815** [comment]
@Don42 FYI: ich hab jetzt die Kiste mit dem Picking-equipment ins Hochregal: HR-D2 (Ja, das hat jetzt ein koordinatensystem: A-D = x-Achse-links-nach-rechts; 0-8 = y-Achse-unten-nach-oben) 
Weils so schwer ist, hab ich das unterhalb von Kopfhöhe platziert. 
Allerding sist die Kiste schon so etwas haevy. Will man die evtl ausmisten bzw. in mehrere kleinere Kisten aufteilen? Dann könnte man die ja auch hintereinander in Tardis-1-Schubladen packen. Die linke Hälfte von 0xF! ist ja frei.

**Comment by Bfritz0815** [comment]
Ich hab jetzt alle nicht-notwendigen Boxen ins linke der beiden Regale gestellt.

**Comment by Bfritz0815** [comment]
Die folgenden Kisten sind ins Hochregal in HR-A6 gewandert: 

- Bügelperlen
- "CFD Chaos Familien Duell"
- Leuchtmittel
- Zeitschaltuhren

**Comment by Bfritz0815** [comment]
Übrigens: Alle Dinge, die nach meiner Vorstellung auf jeden Fall da bleiben können, sind im Rechten der beiden Regale.

Sortierung: Je Strom, desto unten, je I/O desto oben. 

Im linken Regal sind Dinge, die ich in Zukunft wegstellen werde,sofern sie nicht vorher jemand defragt oder woanders hin stellt. 

Die Kiste mit "E-Ecke Module" ist jetzt in der E-Ecke auf der Ä-Ecken-Seite. 

@slowpoketail Will Team RETRO die 2 Kisten mit Parallel und Serial-Kabeln/"Spezial-Kabel" zu sich tun? Die braucht ja wohl sonst keiner mehr im Routinebetrieb. Daher wären die bei euch imho am Besten aufgehoben. Deine Meinung dazu?

**Comment by docsteel** [comment]
@Bfritz0815 die Seriell/Paralell Kabel braucht man immer mal wieder für Netzwerk/Elektronik Basteleien. Bitte nicht entsorgen. Notfalls in Richtung E-Ecke verlagern.

**Comment by Bfritz0815** [comment]
@docsteel von Entsorgen war nie die Rede. "Museum" war ja auch mehr humoristisch. 

Vorschlag:
- ein Basisbestand (z.B. je 2 Stück) wandet in die E-Ecke und bleibt dort: Nehmen, Nutzen, zurücktun. (i.e. kein Mitnehmen nach Hause, kein nur mal schnell "über Nacht" in einem Projekt verbaut lassen o.Ä.)
- alle Weiteren gehen an Team Retro

Den Basisbestand werde ich dann demnächst in die E-Ecke bringen und einen geeigneten Ort dafür finden. 

Hintergrund: 
Ich finds ja sowieso nice, wenn von Team Retro her soweit auf strukturierte Ablage der Items geachtet wird, dass man unverbaute Komponenten wie Kabel u.A. auch mal ausleihen kann. 
Retro muss ja hier nicht auf Retro-Games im engeren Sinne eingeschränkt sein. 
Je einfacher da Komponenten zugänglich sind, desto leichter können da mehr Leute dazukommen.

**Comment by s1lvester** [comment]
Is ziemlich aufgeräumt. In der E-Ecke ist aber nicht wirklich platz für mehr Kabels, oder?
