### ISSUE TITLE
Homekitbridge fixen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-tuwat#67]
Auf cashdesk.rzl läuft eine Homekitbridge, welches Homekitbefehle von iOS Geräten annimmt und sie zu unserer Lichtsteuerung schickt.

Da iOS 10 eine Home App mitliefert, mit welcher man dann das RaumZeitLabor steuern kann, könnte die wieder in Betrieb genommen werden.

**Comment by silsha** [comment]
Funktioniert wieder. Alle Geräte die im openHAB hinterlegt sind, können nun mit iOS-Geräten gesteuert werden.
Falls jemand mit iOS 10 Zugriff darauf möchte, einfach direkt bei mir melden.

**Comment by silsha** [comment]
Ist wieder kaputt. 🐱

**Comment by Cheatha** [comment]
Vielleicht wäre es eine Idee das in eine eigene VM/Dienst zu packen statt irgendwo mitlaufen zu lassen ;)

**Comment by silsha** [comment]
Ja, wäre es. Müsste nur mal jemand™ machen. 😸

**Comment by silsha** [comment]
Geht größtenteils. Nutze glaube eh nur ich, daher schließe ich das hier mal 🖖
