### ISSUE TITLE
Stromverbrauch und Sicherheit

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#68]
Eben (18:25) fragte mich yocky, ob ich die e-ecke benutzt hätte, da dort noch ein Lötkolben an war. 
Da ich die E-Ecke nicht benutzt habe und seit heute Mittag im Raum bin, können wir mal davon ausgehen, dass das Gerät seit Gestern durchlief. 
Über die Stromrechnung brauchen wir uns unter solchen Umständen keine Gedanken machen - die füllt sich von selbst. 
Auch find ich das vom Brandschutzaspekt her eher minder-geil, dass das Teil die ganze Zeit durchläuft. 
(Bitte auch bedenken: wir haben auch noch andere Hitzequellen: Reflow-Ofen etc.)

Übrigens: Bevor jetzt jemand loslegt von wegen "muss man halt mehr aufpassen":
Ich war vor ca 2 Stunden kurz in der E/Ä-Ecke ohne an den Arbeitsplätzen zu sein. Hätte es eine Art Anzeigelampe o.Ä. gegeben, hätte ich dann das Gerät bemerkt und abgestellt. Allerdings hat das Gerät nur ein unbeleuchtetes LCD-Display, sodass es nicht bemerkbar war. 
Gut möglich, dass auch der/die Verursacher/in durch ne zwischenzeitliche Ablenkung das Gerät aus den Augen verloren hat. 

Nun hat Yocky da was ganz interessantes vorgeschlagen: Wie wärs, die E-Ecke (ausser dem Server-Rack) an einen Anschluss zu hängen, der sich bei Türschluss abschaltet. 

Besonders vor dem Hintergrund, dass im Raum auch schonmal Leute ruhen, wäre auch eine zusätzliche Anzeigelampe an der E-Ecken-Tür recht sinnvoll. (z.B. sobald der Verbrauch über x geht, leuchtet die Lampe)
# Ideen/Todos
- [ ] in der E/Ä-Ecke alles ausser dem Server-Rack auf anschlüsse umstellen, die sich bei Abschliessen des Raums selbst ausschalten
- [ ] digital-Strommesser an die E/Ä-Ecken-Versorgung (gesamt und/oder für einzelne Plätze)
- [ ] Anzeige-LED bei der Tür der E-Ecke
- [ ] Darstellung des Verbrauchs nach Bereich des Raums als Diagramm aufm Statusscreen ? Oder ne Tile mit mini-tiles, die den Status verschiedener Systeme anzeigen?

Wenn es dafür ne brauchbare Lösung gibt, könnten wir die später auch für Fablab und Werkstatt ausrollen (T-Shirt-Presse und Kompressor sollten im Zweifel auch nicht die ganze Nacht hindurch laufen)

**Comment by s1lvester** [comment]
Finde ich eine hervorgagende Idee. Werkstatt und Fablab sowie Workshop-Raum sind eigentlich durch die Schaltung mit dem Notaus-Taster relativ safe (zumal ich den Eindruck habe, dass der auch meistens verwendet wird.) Evtl. könnte jemand mit Licence-to-kill auch eine solche Notaus-Leichten-Kombi vor der Tür zur E/Ä-Ecke anbringen?

Super geil wäre natürlich auch folgendes szenario:
Member will Tür abschließen --> ALARM! es sind noch Verbraucher eingeschaltet!!!

**Comment by tabascoeye** [comment]
Es gibt ein NodeRed in dem noch die Rule angelegt ist, eine Weile nach dem Tür schließen, alle Funksteckdosen abzuschalten.
Tut nur nicht zur Zeit (?)

**Comment by Ranlvor** [comment]
Ich habe die Regel im NodeRed gefunden. Sie versucht Dinge über das FHEM zu schalten, das scheint aber nicht so ganz zu funktionieren. Habe das mal testweise auf das OpenHAB umgestellt, da geht es. Allerdings ist unser NodeRed deprecated.

**Comment by Bfritz0815** [comment]
@Ranlvor naja, abgesehen davon, dass die funkerei scheints öfters hakt, ham wir auch einfach keine Funksteckdosen in der E/Ä-ecke sitzen. Ich dachte wirklich an "Saft weg auf Zuleitungs-Ebene" (ausser f d Anschlüsse des Server-Racks)

**Comment by uwap** [comment]
Eventuell wäre für die E/Ä-Ecke auch ein Notaus wie im Fablab interessant. Ansonsten wäre die Frage ob man da nicht ein Sonoff fest verbauen kann? cc @Ranlvor

**Comment by Ranlvor** [comment]
Fest verbauter Sonoff wäre die Frage: Wo baut man den hin, dass man gut an den Knopf kommt um ihn einzuschalten, falls das WLAN aus irgendeinem Grund streikt und man in der E-Ecke werkeln will. Und will man überhaupt da automatisch abschalten? Man will ja zum Beispiel keinen Reflowvorgang abbrechen, nur weil jemand die Tür absperrt.

Schütz im Sicherungskaten und gut sichtbare Statusanzeige wie bei der Werkstatt würde ich besser finden, aber ich kann schwer abschätzen wie teuer und aufwendig das ist.

Ich meine mich zu erinnern, dass das Rack separat abgesichert ist, das heißt man müsste „nur“ die Steuerkabel verlegen und die Stromkabel im Sicherungskasten auf einen Schütz legen. Sollte das nicht getrennt sind müsste man wohl mehr umbauen.

**Comment by s1lvester** [comment]
Gab auf Twitter zuletzt einige Bilder von durchgebrannten Sonoff-Modulen. Also keinen Ganzen Raum dran hängen :-)

**Comment by Ranlvor** [comment]
Wir haben gerade 7 unbelegte Sonoff S20. Davon könnte man 2 zwischen Lötarbeitsplätzen und Steckdosen montieren und damit die Lötarbeitsplätze beim Raum-absperren automatisch abschalten. Einschalten würde man bei Bedarf manuell per Knopfdruck auf den Hardwarebutton.

Frage ist: Machen oder nicht machen?

**Comment by Bfritz0815** [comment]
Auf jeden fall machen

**Comment by Ranlvor** [comment]
erledigt.

**Comment by Ranlvor** [comment]
Map zeigt jetzt an, wenn die Lötkolben an sind, kann sie aber (absichtlich) nicht schalten.
