### ISSUE TITLE
infoscreen kaputt

### ISSUE THREAD

**Issue by s1lvester** [raumzeitlabor/rzl-tuwat#69]
Infoscreen-Server ist kaputt.

cashdesk.rzl:3030/rzl ist down.

**Comment by silsha** [comment]
Schaue ich mir an. Ich glaube der infoscreen webserver startet nach einem Reboot nicht automatisch.

**Comment by s1lvester** [comment]
BTW: #69 (hrhrhrhrhrhr :eggplant: )

**Comment by s1lvester** [comment]
@docsteel Hat auch das automagisch gefixt. Thx.
