### ISSUE TITLE
Benutzbaren Zustand der Elektroecke herstellen

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#7]
Die Elektroecke hat vier Arbeitsplätze. Davon können maximal zwei benutzt werden, weil die Stellfläche unter den Tischen in der einen Ecke als Lagerfläche angesehen wird.
- [x] Dinge identifizieren
- [x] Eigentümer herausfinden
- [x] zum Mitnehmen animieren/entsorgen
- [x] Rollbares Regal besorgen/bauen, um Platinenbelichter und Reflowofen dort unterzubringen und unter dem Tisch zu verstauen (Feli)
- [x] Alten OP-Monitor abbauen

**Comment by Don42** [comment]
Da stehen zwei kleine Kartons mit Spielen von mir, die waren für die Retro Gamer.
Wurden meines Wissens noch nicht katalogisiert und eingelagert.

**Comment by else** [comment]
Dann am besten wieder mitnehmen und nicht drauf warten, bis der Tag kommen wird.

**Comment by felicitus** [comment]
Ich werde demnächst ein rollbares Regal bauen, um darauf Platinenbelichter und Reflowofen unterzubringen, sodaß beides nicht mehr auf dem Tisch rumsteht

**Comment by felicitus** [comment]
Der OP-Monitor wurde AFAIR noch nie groß verwendet, deshalb könnte man den Abbauen und entsorgen. Wurde wohl damals von Niklas oder so gespendet.

**Comment by else** [comment]
Der hat auch das Problem, das er erst nach ein paar Minuten hell genug wird. Bin auch für entsorgen.

**Comment by Bfritz0815** [comment]
Habe den Monitor entsorgt und die Arbeitsfläche etwas defragmentiert. 
Vom Monitor sind noch ein Paar Teile übrig: VGA-, DVI-, Kaltgeräte-Kabel. 
Die Wandhalterung hab ich mal dran gelassen, die stört nicht und hat glaubich das passende Schraubmuster für Monitore nach VESA ( http://www.vesa-halterung.de/vesa-ermitteln.html ).

**Comment by Bfritz0815** [comment]
Stand Ätzecke aktuell:

- [x] Dinge identifizieren (alles ID'd)
- [ ] Eigentümer herausfinden (90%)
- [x] zum Mitnehmen animieren/entsorgen
- [ ] Rollbares Regal besorgen/bauen, um Platinenbelichter und Reflowofen dort unterzubringen und unter dem Tisch zu verstauen (Feli) (Work in progress)
- [x] Alten OP-Monitor abbauen

**Comment by felicitus** [comment]
Rollwagen für Belichter und Reflowofen ist fertig. http://log.raumzeitlabor.org/post/132484917851/rollwagen-f%C3%BCr-belichter-und-reflowofen

**Comment by Bfritz0815** [comment]
@abrock HI, dein Digital-Oszi  steht in der E/Ä-Ecke auf der Ä-Seite inmitten dem ganzen Geraffel. Ist das Absicht oder kann man den wieder oben in die E-Ecke stellen?

**Comment by abrock** [comment]
Ich hab das nicht da hin, das sollte in der E-Ecke stehen.
