### ISSUE TITLE
Funksteckdosen

### ISSUE THREAD

**Issue by s1lvester** [raumzeitlabor/rzl-tuwat#71]
Alle wissen(tm): Die Funksteckdosen sind defekt. Ich schlage folgenden Plan vor:
1. Triage: Wo ist der Sender Verbaut - Welche VM steuert ihn und mal wieder: Wer hat Access?
   1.1 Related: Wie ist der Status des OpenHAB (@maikf)?
2. Fuzzing: An welchen Stellen im Raum funktoniert der Sender, Wo ist ne gute Position und wo brauchen wir evtl Repeater?
3. ...
4. Profit.

Ich hab mir mal ein paar Funkmodule bestellt. Die kommen aber aus Shenzen und brauchen noch.

**Comment by s1lvester** [comment]
Also related: #68

**Comment by tabascoeye** [comment]
Aus RF Sicht war das zu der Zeit, als alles ging nie ein Problem. Kann mir nicht vorstellen, dass wir mehr Sender oder Repeater brauchen.

**Comment by s1lvester** [comment]
Okay. Laut Wki (https://wiki.raumzeitlabor.de/wiki/Funksteckdosen)
- soll der Sender im Rack liegen.
- soll unter http://www.infra.rzl:8083/fhem laufen. **(Scheint down zu sein)**

**Comment by Ranlvor** [comment]
Ich hab mir das Thema mal angeschaut...

Stand laut Wiki: Der Sender liegt **auf** dem Rack und hat überall Empfang
Stand laut „Ich hab in's Rack geguckt“: Der Sender liegt **ganz unten im** Rack hinter einer Metallplatte und das „manchmal hilft 2x klicken“ deute ich als „hat schlechten Empfang“
Vorschlag: USB-Kabel verlängern und wieder auf's Rack damit

Das aktuell überhaupt nix läuft ist laut Wiki ein Softwareproblem ausgelöst durch rausziehen und wieder einstecken des Funkmoduls. Laut Wiki wäre das durch shutdown + reboot zu lösen. Ich kann die nötige VM auch herunterfahren, allerdings habe ich nicht die Berechtigungen sie anschließend wieder zu starten und ich weiß nicht, ob sie das automatisch tut, also hab ich das bisher nicht probiert.

**Comment by tabascoeye** [comment]
uff. Ketzerische Frage: Sollten wir das vll auf einem RasPI3 o.ä. laufen lassen, damit das unabhängig von Mate ist?

**Comment by s1lvester** [comment]
Dafür. 

Der raspi vom infoscreen liegt auch schön zentral im Hauptraum. Dann kann sich der dongle sogar selbst ausschalten. 

Als Friedensangebot bezüglich meiner Docker-Kätzerei würde ich anbieten ein ansible Script schreiben, dass den infoscreen Browser, das serielle irc Terminal und die rf-Bridge konfiguriert. 

Gerne auch mit @ranlvor zusammen weil er ja schon die bridge kennt.

**Comment by Ranlvor** [comment]
Bevor du dir zu viel Arbeit mit dem Infoscreen-PI machst möchte ich dich daran erinnern, dass der Infoscreen meiner Wahrnehmung nach mit Abstand der PI ist, der am häufigsten an kaputter SD-Karte stirbt.

**Comment by s1lvester** [comment]
Naja. Zwei mal im letzten Jahr. Deswegen hab ich ja [hier](https://github.com/raumzeitlabor/kiosk-browser) nicht nur das repo geforkt, sondern auch eine kurze doku dazu geschrieben. Damit ging Wiederaufsetzten eigentlich easy. 

Is doch nur noch ein Grund für ein ansible-script, weil 1. wird wieder kaputt gehen und 2. mit script noch einfacher wieder aufzusetzen? Gerade isses ja so, dass sich @maikf und @lutoma sich mit dem Public-IRC-Terminal arbeit gemacht haben, und wenn die SD jetzt das nächste mal stirbt isses weg und jemand muss sich wieder von neuem reinfuxxen.

**Comment by Ranlvor** [comment]
Ich hab die SD-Karte mal auf's Datengrab kopiert, kann man mit dd restoren

**Comment by s1lvester** [comment]
Grrrrrr. Hör bitte auf meine komplex eingebildeten und vollkommen unrealistisch überzogenen Problemdarstellungen mit einfachen und pragmatischen Lösungen zu torpedieren 😜😗🙃

Bist du Freitag/Samstag da? Dann könnten wir mal darüber schauen. Mich würde interessieren wie weit du mit dem du Zeug gekommen bist. 

@maikf

**Comment by Ranlvor** [comment]
bin dieses Wochenende nicht da. Nächste Woche Samstag vielleicht?

**Comment by s1lvester** [comment]
@docsteel Hat es automagisch gefixt. How? I dunno. Doc?

**Comment by Ranlvor** [comment]
How: Ich lag falsch mit dem „man muss es nur rebooten“. @docsteel hat das Pass-Through des Senders neu konfiguriert und es damit gefixt. Außerdem hat @hax404 mir Zugriff auf Mate gegeben, damit sollte das „ich will, aber kann nicht“ bei mir endgültig erledigt sein.

Ich würde das Issue noch gerne offen halten als Reminder an mich beim nächsten mal, wenn ich im RZL bin, mir eine Dose zu schnappen und Reichweitenanalyse zu betreiben und zu dokumentieren. Ich möchte wissen, ob der aktuelle Zustand weit genug geht oder nicht.

(Bin kein Member der RZL-Github-Organisation und kann das Issue nicht wieder öffnen.)

**Comment by Ranlvor** [comment]
Habe gerade geguckt und getestet: Der Sender hängt nicht mehr ganz unten im Rack sondern in der Mitte und kann jetzt auch Dosen im Workshopraum schalten. Denke damit ist das Thema erledigt.

**Comment by Ranlvor** [comment]
(bitte wieder schließen, bin zwar RaumZeitLabor member auf Github, aber ich sehe trotzdem keinen close-Button)

**Comment by tabascoeye** [comment]
alles nicht so einfach. Jetzt sollte der button da sein ;o)
