### ISSUE TITLE
Schublade "Backpapier und Folien" defekt

### ISSUE THREAD

**Issue by s1lvester** [raumzeitlabor/rzl-tuwat#72]
Oh Hai!
Die Front o.g. Schublade ist defekt.

NEED: Holzleim. Falls jemand zu Hause hat bitte Schublade ausräumen, Front leimen und mit Schraubzwingen für $stunden fixieren.

**Comment by steeph-k** [comment]
In der Werkstatt liegen eigentlich immer zwei bis drei Tuben Holzleim, meistens direkt am Eingang auf dem Elektrokanal. Außerdem sollte on der mit "Kleber" beschrifteten Schublade in TARDIS1 auch welcher sein.

**Comment by s1lvester** [comment]
STATUS: WIP.

Bitte bei Gelegenheit morgen die Schublade wieder einbauen. Danke.

**Comment by s1lvester** [comment]
STATUS: DONE.
