### ISSUE TITLE
Benutzerhandbuch fürs RZL

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#73]
Angeregt auf dem Plenum 15.1.2017 als Einstiegshilfe für neue Mitglieder und Mitglieder, die schon länger nicht mehr da waren. 

Inhalte wären:

- Space-Kultur
- Howtos
- Common-Knowlege
- u.v.m.

Ich würde das gerne als Wikiseite aufziehen (erst in DE, dann in EN). 

Meinungen? Fragen? Anregungen?

**Comment by blabber** [comment]
Es gibt da auch noch das "alte" Mitgliederhandbuch das man aktualiseren, erweitern oder zumindest als Grundlage nutzen kann: https://github.com/raumzeitlabor/mitgliederhandbuch

**Comment by hax404** [comment]
Ich habe mal beim „alten Mitgliederhandbuch“ aktualisiert, was ich für notwendig halte. Jemand anderes kann sich (das mal ansehen)[https://github.com/raumzeitlabor/mitgliederhandbuch/pull/1] und mergen.

**Comment by s1lvester** [comment]
Aktuelle Version wurde ins Wiki gespeichert.

https://wiki.raumzeitlabor.de/wiki/Handbuch
