### ISSUE TITLE
RZL winterfest machen

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#74]
Hallo,
besser spät als nie:

- [x] Magnete besorgen für in die Unterkante der Vorhänge (ca. 20 Stck in 3x3x3 mm)
- [x] Deckenventilator über Tardis reaktivieren (und hier posten, wie man das an/aus-schaltet)
- [x] Deckenventilator über Tardis per fernstuerbar machen über tablet

**Comment by tabascoeye** [comment]
Soweit ich weiß wollen sich u.a. @Cheatha und @Ranlvor die Funksteckdosen und OpenHAB Situation anschauen.
Ich würde vorschlagen, dass wir noch mehr von den Dingern kaufen und mehr Dinge einzeln an solche Steckdosen hängen.
Momentan hängt zB ein großer Stromkreis mit vielen Geärten auf dem Olypm an einer Steckdose. Unter den Geräten ist auch Annette. Um was zu drucken muss ich also ca 10 Geräte bestromen. Das ist ziemlich doof.

- [ ] Deckenventilator sollte auch eine eigene Funksteckdose bekommen
- [ ] Skripte sollten alle Funksteckdosen beim Schließen des Raums abschalten

**Comment by Ranlvor** [comment]
Das Skript für allen Funksteckdosen beim Schließen des Raumes einen Abschaltbefehl zu geben ist im Nodered vorhanden und aktiv. Nur leider schalten die Steckdosen nicht mit 100% Zuverlässigkeit

**Comment by abrock** [comment]
Eher 5x5x5mm Magnete

**Comment by steeph-k** [comment]
Ist bekannt, wieso die Steckdosen nicht zuverlässig schalten? Ist das evtl. mit einem stärkeren Sender oder mehr Sendern zu lösen? Sonst könnte man die Routine zum Abschalten doch bestimmt um eine Strommessung direkt nach dem Schalten erweitern. Wenn immer noch Strom fließt muss eben gleich noch mal geschaltet werden.

**Comment by Ranlvor** [comment]
Die Unzuverlässigkeit scheint nicht von der Entfernung von Steckdose und Sender abzuhängen. Habe das mit einer Dose im Hauptraum vs. einer Dose in der Werkstatt getestet.

Wie und ob man die Strommessung triggern kann ist mir nicht bekannt. Wenn man die Steckdosen schon befragt kann man auch einfach ihre Schaltzustandsmeldung befragen, das ist vermutlich zuverlässiger als die Strommessung.

**Comment by tabascoeye** [comment]
ack. Deshalb habe wir ja die "teuren" Funksteckdosen genommen, die auch Rückmelden.

**Comment by Ranlvor** [comment]
Ich habe mal das Kabel verfolgt und stellte fest, dass der Deckenventilator über der Tardis in der gleichen Mehrfachdose steckt wie Anette. Technisch gesehen ist er also über den Punkt „Rechner und Drucker, Olymp“ im infra.rzl schaltbar.

**Comment by tabascoeye** [comment]
ja das habe ich so hingebaut, weil der Ventilatorstecker einfach so ungestöpselt rumlag.
Finds aber doof, zwei Rechner, zwei Monitore und eine Xerox Workstation unter Strom zu setzen, damit sich ein ventilator dreht ;o)

**Comment by felicitus** [comment]
Drucker, 2 Rechner, 2 Monitore und den Ventilator an einer Funksteckdose? Das sollte dringend umgebaut werden.
