### ISSUE TITLE
tardis 0x04 public kann das weg?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#77]
inhalt: eine handvoll 3d gedruckte getriebe.

Fragen:
- wem gehört?
- was ist das?
- kann das weg?

**Comment by s1lvester** [comment]
Kann weg, denke ich.

**Comment by uwap** [comment]
Mail mit Deadline und Foto auf die ML?

**Comment by s1lvester** [comment]
Wurde entsorgt --> Found - Kiste.
Schublade freigegeben.
