### ISSUE TITLE
schubladen 0x06 und 0x07 dashies arsenal

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#78]
0x06/07 is dashie noch da? Braucht er das arsenal noch?

**Comment by tabascoeye** [comment]
zusätzlich dazu steht im Textillager iirc noch eine riesige IKEA Kiste mit Zeug von Dashie...

**Comment by uwap** [comment]
Die Kiste steht jetzt im Hauptraum. Bitte räumt das Zeug weg.

**Comment by tabascoeye** [comment]
brainfreeze kümmert sich. Die Schubladen bleiben natürlich. Dashie ist noch Mitglied.
