### ISSUE TITLE
tardis 0x10 who is lordeis?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#79]
wer ist lordeis? Braucht er das noch?

- wer ist lordeis?
- kann/will er/sie mal nen User-Artikel im wiki anlegen?

steht auch auf der liste hier:
https://wiki.raumzeitlabor.de/wiki/Tardis_nutzer

**Comment by s1lvester** [comment]
Ping @tabascoeye

**Comment by tabascoeye** [comment]
✅ ist noch Mitglied

**Comment by s1lvester** [comment]
Na dann ist ja alles gut. Weitergehen.
