### ISSUE TITLE
Werkstatt aufräumen

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-tuwat#8]
Die Werkstatt ist unbenutzbar.

- [ ] überflüssige Dinge entsorgen
- [ ] Ordnung herstellen

**Comment by Bfritz0815** [comment]
Fazit heute:
Schwerlastregal fertig, Arbeitsflächen frei, Müll weg. 
Noch offen: Material auf Tardis2.

**Comment by Bfritz0815** [comment]
heute: 
- auf Tardis2 entrümpelt
- brauchbares Material in Scherlastregal
- nur überlanges Material auf Tardis 2 (daher leichter)

Ready for Testing

**Comment by s1lvester** [comment]
Eigentlich kann man das Projekt als abgeschlossen bezeichnen. Tardis 2 ist jetzt ein reduziertes Materiallager und jede Menge stuff wurde mit entsprechenden owner-stickern versehen. Ich hoffe es bleibt eine Zeit lang so.

Danke an alle die angepackt haben!

**Comment by Bfritz0815** [comment]
@else fertig zur Abnahme

**Comment by else** [comment]
:+1:
