### ISSUE TITLE
tardis 0x20 waffensammlung

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#83]
20 ehemals drahti, nun waffen

- wem gehören die nerf-waffen?
- bitte schublade in besitz nehmen, zahlen, labeln und in wiki eintragen oder den inhalt weg und neu labeln

**Comment by blabber** [comment]
Ich habe drahti mal darauf angesprochen und er kann nicht nachvollziehen warum das "ehemals drahti" sein sollte. Er ist zwar aus beruflichen Gründen gerade kaum im RZL, möchte aber seinen Privatkram und die Schublade gerne behalten.
