### ISSUE TITLE
tardis 0x21 labelfehler oder unaufgeräumt

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#85]
21 ehemals drahti. Privatkram v drahti ist drin. Kann der weg?

please relabel or clear and update wiki

**Comment by blabber** [comment]
Ich habe drahti mal darauf angesprochen und er kann nicht nachvollziehen warum das "ehemals drahti" sein sollte. Er ist zwar aus beruflichen Gründen gerade kaum im RZL, möchte aber seinen Privatkram und die Schublade gerne behalten.

**Comment by Bfritz0815** [comment]
das "ehemals" kommt daher, dass das label am arsch ist: Task: relabel

**Comment by s1lvester** [comment]
Wurde gelabelt.
