### ISSUE TITLE
lists.raumzeitlabor.de Zertifikat ist abgelaufen

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-tuwat#86]
Aktuell lässt sich https://lists.raumzeitlabor.de/ nicht aufrufen, da HSTS aktiviert und das Zertifikat abgelaufen ist. Da Wiki und Blog aufgerufen werden können, vermute ich mal, dass lists.raumzeitlabor.de einfach vergessen wurde.

**Comment by blabber** [comment]
@docsteel, hast du beim letencrypt rollout lists.raumzeitlabor.de übersehen?

**Comment by docsteel** [comment]
fixed. Das Zertifikat musste noch auf einem anderen Server installiert werden.

**Comment by blabber** [comment]
Danke 👍
