### ISSUE TITLE
raumzeitlabor@ hakt immer noch

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-tuwat#87]
Irgendwie hakt raumzeitlabor@ immer noch. Die Mails die ich gestern an die ML geschickt habe kamen nie an.

Der Mailman Reminder zum 1. März hat mir dann auch gezeigt ich hätte raumzeitlabor@ gar nicht abonniert. Hab dann als lists.raumzeitlabor.de wieder ging geschaut und konnte mich sowohl im Archiv als auch in meinen Optionen einloggen. Ich war also wohl doch irgendwie im System raumzeitlabor@ zugeordnet.

Wie bei der IT-Crowd gelernt habe ich dann beschlosse mein Abo abzubestellen und dann neu zu abonnieren, aber ich bekam keine Confirmationmail von Mailman. Seitdem kann ich mich auch nicht mehr im Archiv oder in den Optionen einloggen.

@Ranlvor war so nett mal mitzutesten und auch er erhält keine Mails von mailman.

Mehr Infos kann ich leider nicht bieten, aber vielleicht kann @Ranlvor noch was ergänzen.

**Comment by Ranlvor** [comment]
Was ich getestet habe/weiß:

- E-Mail von einer E-Mail-Adresse, die nicht Mitglied der Liste ist, landet in der Moderationsqueue (gut)
- Ich, als Moderator der Liste, bekomme keine Hinweismail „hey, du musst da was moderieren“ (schlecht)
- Wenn ich die Mail ablehne bekomme ich, als Absender der E-Mail, keine Hinweismail über die Ablehnung (schlecht)
- Mails an netzwerk@ funktionieren ordnungsgemäß
- laut @blabber funktionieren auch Mails an vorstand@ ordnungsgemäß.

**Comment by Ranlvor** [comment]
Waren von einem UTF-8-Bug in Mailman betroffen: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=750525
