### ISSUE TITLE
Openhab/Funksteckdosen defekt

### ISSUE THREAD

**Issue by slowpoketail** [raumzeitlabor/rzl-tuwat#89]
Irgendwas™ ist mit dem Openhab kaputt, die Funksteckdosen lassen sich nicht ansteuern. Scheint ein Softwareproblem zu sein. Das NOC müsste mal und so.

**Comment by s1lvester** [comment]
http://infra.rzl:8080/openhab.app --> 404

**Comment by docsteel** [comment]
> http://infra.rzl:8080/openhab.app --> 404

Works for me.

Evtl. falschen DNS eingetragen?

Geht das per IP? http://172.22.36.202:8080/openhab.app

**Comment by s1lvester** [comment]
ja geht per ip.

liegt aber nicht an meinem dns, weil es von dem Tablet in der Küche auch 
nicht geht.

**Comment by Ranlvor** [comment]
Ich habe infra.rzl einmal durchgestartet, daher war das OpenHab kurzzeitig nicht verfügbar. Gelöst hat das das Problem leider nicht. Das OpenHab-Webinterface ist jetzt wieder da, aber scheint die Steckdosen nicht zu schalten.

**Comment by docsteel** [comment]
USB Device wird bei einem VM Reboot nicht sauber erkannt. USB Device ab- und wieder anstecken sollte helfen. Evtl. danach den OpenHAB Service einmal neu starten

**Comment by tabascoeye** [comment]
würde es vll Sinn machen das ganze Funksteckdosengedönz(tm) auf e.g. einen RasPI3 zu packen und auf die Beamerplattform zu legen?
* bessere "Funkung"
* Unabhängig von fiesen USB-pass-through Dingern in VMs

Den OpenHAB Kram wollte sich auch @Cheatha mal anschauen. Das gibts ja inzwischen in viel hübscher, als was wir haben...

**Comment by Ranlvor** [comment]
Gerade getestet. Geht.

Ich werde niemanden aufhalten, der das ganze auf einem PI machen will. Ich würde nur dazu raten Maßnahmen zu treffen, die die Schreibvorgänge auf die SD-Karte minimieren. Bin gerade nämlich ein altes Backup des Infoscreens am wiederherstelen, weil's bei dem schon wieder die SD-Karte zersägt hat.
