### ISSUE TITLE
SD-Karte Infoscreen kaputt

### ISSUE THREAD

**Issue by Ranlvor** [raumzeitlabor/rzl-tuwat#90]
Der Infoscreen wollte heute nicht booten und hat jede Menge systemd-Log-Fehler auf dem Terminal ausgegeben. Beim Versuch die Karte zu lesen meinte sie nach 1 GB, dass das alles war, obwohl das eine 16 GB Karte ist. Beim Versuch ein altes Backup der SD-Karte wiederherzustellen hat mein Kernel jede Menge 
```
[ 6051.581168] mmcblk0: timed out sending r/w cmd command, card status 0x400e00
[ 6051.581261] mmcblk0: timed out sending r/w cmd command, card status 0x400e00
[ 6051.581358] mmcblk0: timed out sending r/w cmd command, card status 0x400e00
[ 6051.581452] mmcblk0: timed out sending r/w cmd command, card status 0x400e00
```
geworfen.

Fazit: SD-Karte ist kaputt. Ich habe ein Backup davon, aber man sollte Maßnamen treffen, die die Schreibvorgänge reduzieren damit die nächste Karte länger hält.

**Comment by Ranlvor** [comment]
`Mar  7 18:32:44 tadpole kernel: [ 6833.592687] mmcblk0: mmc0:b368 SMI-S 1.00 GiB`

Die SD-Karte meldet sich bei mir auch nur als 1 GB-Karte.

**Comment by tabascoeye** [comment]
was. zum.
Könnte man das nicht mal als ro Dateisystem bauen und alles in einer Ramdisk laufen lassen? evtl. Mit RasPI2 oder 3?

**Comment by Ranlvor** [comment]
Dafür. Genau sowas meine ich mit „Maßnamen treffen, die die Schreibvorgänge reduzieren“. Gerade Webbrowser sind in der Regel nicht sehr freundlich zu Flash-Speicher.

**Comment by s1lvester** [comment]
https://hallard.me/raspberry-pi-read-only/

**Comment by tabascoeye** [comment]
du hast den job ;o)

**Comment by s1lvester** [comment]
done.
s. hier: https://gist.github.com/s1lvester/b501c1234f4f43805b16bf76051c80d5

in /root liegen 2 bash-scripte um zwischen ro und rw zu switchen.

**Comment by Kunsi** [comment]
Alternativ OverlayFS deployen.
