### ISSUE TITLE
Tardis 0x 33 Hog

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#92]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Hog vorstellen?

**Comment by tabascoeye** [comment]
hog is nicht mehr Mitglied im RZL ❌ 
Mail an Liste mit Frist ==> danach Leerung

**Comment by Bfritz0815** [comment]
Macht das der Vorstand? Danke.

**Comment by s1lvester** [comment]
Email an rzl@rzl am 25.04. mit Frist zum 07.05.

**Comment by Bfritz0815** [comment]
@s1lvester kam bisher ne Antwort/Reaktion?

**Comment by Bfritz0815** [comment]
Habe die Schublade zusammen mit @s1lvester geleert. Der Inhalt ist aktuell in der Lost-and-Found und wird dann entsprechend abgewickelt.
