### ISSUE TITLE
tardis 0x3b Xalynrae

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#93]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Xalynrae vorstellen?

**Comment by Don42** [comment]
Ist das vllt ein "Talynrae"?

**Comment by Bfritz0815** [comment]
@Don42 kann sein. Dann hat das aber jemand echt scheisse beschriftet. Diese Task wäre dann also "richtig labeln"

**Comment by Bfritz0815** [comment]
TODO:

- [ ] https://wiki.raumzeitlabor.de/wiki/Benutzer:Talynrae in Tardis verlinken
- [ ] Label richtig beschriften

**Comment by tabascoeye** [comment]
Talynrae ist noch Mitglied.

**Comment by s1lvester** [comment]
Wurde gelabeltetete
