### ISSUE TITLE
tardis 0x46 wer ist Kristin? Krishna? Krishan? Unleserlich

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#94]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Kristin vorstellen?

**Comment by tabascoeye** [comment]
Vermutlich @probot128 (https://github.com/probot128).
Ist noch Mitglied ✅

**Comment by s1lvester** [comment]
Wurde gelabelthjghg
