### ISSUE TITLE
tardis 0x48 wer is hexelena?

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#95]
1. noch member?
2. hat er/sie noch Bedarf an der Schublade?
3. Mag er/Sie sich per Wall-of-nerds oder Wiki-Seite Laborant:Hexelena vorstellen?

**Comment by tabascoeye** [comment]
hexelena ist kein RZL Mitglied mehr ❌
Mail auf Liste mit Frist => dann Leerung

**Comment by Bfritz0815** [comment]
macht das der Vorstand? Thx.

**Comment by s1lvester** [comment]
Email am 25.04. auf rzl@rzl.
Frist zum 07.05.2017

**Comment by Bfritz0815** [comment]
@s1lvester kam bisher ne Antwort/Reaktion?

**Comment by Bfritz0815** [comment]
Habe die Schublade zusammen mit @s1lvester geleert. Der Inhalt ist aktuell in der Lost-and-Found und wird dann entsprechend abgewickelt.
