### ISSUE TITLE
tardis 0x49 kisl

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#96]
1.  noch Bedarf an der Schublade?
2. mag kisl nen github accnt hier ins team nehmen?

**Comment by s1lvester** [comment]
Ping @tabascoeye

**Comment by tabascoeye** [comment]
Kisl ist noch Mitglied, falls das die Frage war.

**Comment by s1lvester** [comment]
Na dann ist ja alles gut. Weitergehen.
