### ISSUE TITLE
Einkaufen Getränke

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#98]
- loscher mate
- alternative mate
- oettinger
- koffeinfreie getränke

**Comment by s1lvester** [comment]
Stand 12.03.17 17:00 befinden sich noch exat 36 Kisten Mate im Lager. Dazu 2 Palletten Leergut ClubMate und eine Palette Leergut Öttinger

Habe derzeit kein Auto aber Zeit.
